//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int32_t exit(void);
int32_t exit2(void);
int32_t exit3(void);
int32_t function_1d008600(void);
int32_t function_1d008e3c(int32_t * a1);
int32_t function_1d0105a4(int32_t a1);
int32_t function_1d010aec(int32_t a1);
int32_t function_1d011104(int32_t a1, uint32_t a2);
int32_t function_1d011494(int32_t a1, int32_t a2, uint32_t a3, int32_t a4, int32_t a5, uint32_t a6);
int32_t function_1d013480(int32_t * a1);
int32_t function_1d01501c(void);
int32_t function_1d015d40(int32_t a1);
int32_t function_1d015dd0(int32_t * a1);
int32_t function_1d016074(int32_t * a1);
int32_t function_1d016384(int32_t * a1);
int32_t function_1d017074(int32_t * a1);
int32_t function_1d0172b4(void);
int32_t function_1d01854c(void);
int32_t function_1d01c068(int32_t a1, int32_t a2);
int32_t function_1d01c2b8(int32_t a1, int32_t a2);
int32_t function_1d01c2e4(int32_t a1, int32_t a2);
int32_t pthread_cond_destroy(int32_t * a1);
int32_t pthread_cond_destroy2(int32_t * a1);
int32_t pthread_cond_destroy3(void);
int32_t time(int32_t a1);

// ------------------------ Functions -------------------------

// Address range: 0x1d008600 - 0x1d00869c
int32_t function_1d008600(void) {
    // 0x1d008600
    if (*(int32_t*)0xa0013290 < 101) {
        // 0x1d008694
        return 8;
    }
    int32_t v1 = 938; // bp-24, 0x1d008624
    if (*(int32_t*)0xa0013310 < 3) {
        // 0x1d008660
        __asm_ins(2, 4, 4);
    } else {
        // 0x1d00863c
        __asm_ins(15, 4, 4);
    }
    // 0x1d008674
    __asm_ins(1, 15, 1);
    // 0x1d008694
    return pthread_cond_destroy2(&v1);
}

// Address range: 0x1d008e3c - 0x1d0090ec
int32_t function_1d008e3c(int32_t * a1) {
    int32_t v1 = (int32_t)a1;
    *(char *)a1 = 0;
    *(char *)(v1 + 1) = 0;
    int32_t v2 = v1 + 2; // 0x1d008e50
    *(char *)v2 = 0;
    *(char *)(v1 + 3) = 0;
    int32_t v3 = v1 + 4; // 0x1d008e58
    *(char *)v3 = 0;
    *(char *)(v1 + 5) = 0;
    char * v4 = (char *)(v1 + 6); // 0x1d008e60
    *v4 = 0;
    char * v5 = (char *)(v1 + 7); // 0x1d008e64
    *v5 = 0;
    *(int16_t *)a1 = (int16_t)*(int32_t*)0xa00135d4;
    int32_t v6 = *(int32_t*)0xa00135d0; // 0x1d008e78
    *(int16_t *)v2 = (int16_t)((int32_t)(0x51eb851f * (int64_t)v6 / 0x2000000000) - (v6 >> 31));
    int32_t v7; // 0x1d008e3c
    int32_t v8; // 0x1d008e3c
    if (*(int32_t*)0xa00131b8 < 4) {
        // 0x1d008f8c
        v8 = 0;
        goto lab_0x1d008f94;
    } else {
        int32_t v9 = *(int32_t*)0xa00131d8; // 0x1d008eb4
        v7 = v9;
        if (v9 >= 4) {
            // 0x1d00905c
            v7 = v9;
            if (*(int32_t*)0xa0013104 >= 4) {
                // 0x1d008ecc
                v7 = v9;
                if (*(int32_t*)0xa00130b4 >= 4) {
                    unsigned char v10 = *(char*)0xa00130ae; // 0x1d009078
                    unsigned char v11 = *(char*)0xa00130af; // 0x1d009080
                    *(int16_t *)v3 = 256 * (int16_t)v10 | (int16_t)v11;
                    *v4 = *(char*)0xa00131ac ^ -128;
                    v8 = 0;
                    if (*(int32_t*)0xa00131b8 >= 4) {
                        // 0x1d009074
                        v7 = *(int32_t*)0xa00131d8;
                        goto lab_0x1d008ee0;
                    } else {
                        goto lab_0x1d008f94;
                    }
                } else {
                    goto lab_0x1d008ee0;
                }
            } else {
                goto lab_0x1d008ee0;
            }
        } else {
            goto lab_0x1d008ee0;
        }
    }
  lab_0x1d008f94:
    // 0x1d008f94
    __asm_ins(v8, 0, 1);
    *v5 = (char)__asm_ins((int32_t)*(char*)0xa001356e, 1, 1);
    *v5 = (char)__asm_ins(function_1d01854c(), 2, 1);
    *v5 = (char)__asm_ins((int32_t)(exit() != 0), 3, 1);
    int32_t v12 = 1; // 0x1d008fdc
    if (*(int32_t*)0xa0013104 >= 4) {
        // 0x1d008fe0
        v12 = *(int32_t*)0xa00130b4 < 4;
    }
    // 0x1d008ff0
    *v5 = (char)__asm_ins(v12, 4, 1);
    int32_t v13 = 1; // 0x1d009010
    if (*(int32_t*)0xa00131b8 >= 4) {
        // 0x1d009014
        v13 = *(int32_t*)0xa00131d8 < 4;
    }
    // 0x1d009024
    *v5 = (char)__asm_ins(v13, 5, 1);
    *v5 = (char)__asm_ins((int32_t)*(char*)0xa001356f, 6, 1);
    int32_t result = __asm_ins((int32_t)(*(int32_t*)0xa0013228 == 0), 7, 1); // 0x1d009050
    *v5 = (char)result;
    return result;
  lab_0x1d008ee0:
    // 0x1d008ee0
    v8 = 0;
    if (v7 >= 4) {
        // 0x1d0090b0
        v8 = 0;
        if (*(int32_t*)0xa0013104 >= 4) {
            // 0x1d008ef8
            v8 = 0;
            if (*(int32_t*)0xa00130b4 >= 4) {
                // 0x1d0090c8
                v8 = 0;
                if (*(int32_t*)0xa0013228 == 0) {
                    goto lab_0x1d008f94;
                } else {
                    // 0x1d008f10
                    v8 = 0;
                    if (__asm_ext(*(int32_t*)0xa0013220, 16, 1) == 0) {
                        goto lab_0x1d008f94;
                    } else {
                        // 0x1d008f20
                        v8 = 0;
                        if (*(char*)0xa001356e == 0) {
                            // 0x1d008f30
                            v8 = 0;
                            if (*(char*)0xa001356f == 0) {
                                // 0x1d008f40
                                if (exit() == 0) {
                                    goto lab_0x1d008f60;
                                } else {
                                    // 0x1d008f50
                                    v8 = 0;
                                    if (function_1d0172b4() == 0) {
                                        goto lab_0x1d008f94;
                                    } else {
                                        goto lab_0x1d008f60;
                                    }
                                }
                            } else {
                                goto lab_0x1d008f94;
                            }
                        } else {
                            goto lab_0x1d008f94;
                        }
                    }
                }
            } else {
                goto lab_0x1d008f94;
            }
        } else {
            goto lab_0x1d008f94;
        }
    } else {
        goto lab_0x1d008f94;
    }
  lab_0x1d008f60:
    // 0x1d008f60
    v8 = 0;
    if (function_1d01854c() == 0) {
        // 0x1d008f70
        v8 = 1;
        if ((*(int32_t*)0xa00131ac & 0xc00000) == 0x800000) {
            goto lab_0x1d008f94;
        } else {
            // 0x1d008f8c
            v8 = 0;
            goto lab_0x1d008f94;
        }
    } else {
        goto lab_0x1d008f94;
    }
}

// Address range: 0x1d0090ec - 0x1d009220
int32_t time(int32_t a1) {
    // 0x1d0090ec
    int32_t v1; // bp-16, 0x1d0090ec
    int32_t v2; // bp-24, 0x1d0090ec
    if (*(char*)0xa001356d == 0) {
        // 0x1d009180
        if (a1 != 0) {
            // 0x1d009218
            return -0x5fff0000;
        }
    } else {
        int32_t v3 = 0; // 0x1d00910c
        if (*(int32_t*)0xa0013100 != 0) {
            // 0x1d009110
            v3 = __asm_ins(0, 23, 1);
        }
        // 0x1d009134
        v1 = v3;
        v2 = 936;
        if (a1 != 0) {
            // 0x1d009148
            *(int32_t*)0xbf8860e8 = 32;
            // 0x1d009218
            return function_1d015dd0(&v2);
        }
        // 0x1d009164
        pthread_cond_destroy(&v2);
        *(int32_t*)0xbf8860e4 = 32;
    }
    // 0x1d009188
    if (*(int32_t*)0xa0013568 == 0) {
        // 0x1d009194
        v2 = 101;
        function_1d008e3c(&v1);
        function_1d017074(&v1);
        function_1d013480(&v2);
    }
    // 0x1d0091c0
    if (*(int32_t*)0xa00131f8 != 0) {
        // 0x1d0091cc
        if (__asm_ext(*(int32_t*)0xa00131f4, 24, 1) != 0) {
            // 0x1d009218
            return function_1d008600();
        }
    }
    // 0x1d0091e0
    if (*(int32_t*)0xa0013218 != 0) {
        // 0x1d0091ec
        if (__asm_ext(*(int32_t*)0xa0013214, 24, 1) != 0) {
            // 0x1d009218
            return function_1d008600();
        }
    }
    // 0x1d009200
    if (*(char*)0xa001356d == 0) {
        // 0x1d009218
        return 0;
    }
    // 0x1d009218
    return function_1d008600();
}

// Address range: 0x1d00e840 - 0x1d00ea68
int32_t exit2(void) {
    // 0x1d00e840
    *(int32_t*)0xbf881074 = 0x2000000;
    *(int32_t*)0xbf885220 = 255;
    *(int32_t*)0xbf885200 = 255;
    *(int32_t*)0xbf885300 = 0;
    *(int32_t*)0xbf885310 = 0;
    *(int32_t*)0xbf885320 = 0;
    *(int32_t*)0xbf885330 = 0;
    *(int32_t*)0xbf8852e0 = 0;
    *(int32_t*)0xbf885230 = 159;
    *(int32_t*)0xbf885210 = 159;
    *(int32_t*)0xbf885070 = *(int32_t*)0xbf885070 % 16;
    *(char*)0xbf885080 = (char)__asm_ins(1, 0, 1);
    uint32_t v1 = __asm_ext(-0x5ffffc00, 0, 29); // 0x1d00e8cc
    *(int32_t*)0xbf8852d0 = v1 / 0x1000000;
    *(int32_t*)0xbf8852c0 = v1 / 0x10000;
    *(int32_t*)0xbf885270 = v1 / 256;
    int32_t v2 = 0; // 0x1d00e904
    int32_t v3 = 0; // 0x1d00e904
    *(int32_t *)(v2 - 0x5ffffc00) = 0;
    *(int32_t *)(v2 - 0x5ffffbfc) = 0;
    v3++;
    v2 = 8 * v3;
    while (v3 != 16) {
        // 0x1d00e908
        *(int32_t *)(v2 - 0x5ffffc00) = 0;
        *(int32_t *)(v2 - 0x5ffffbfc) = 0;
        v3++;
        v2 = 8 * v3;
    }
    // 0x1d00e928
    *(char*)0xbf885250 = (char)__asm_ins(1, 1, 1);
    *(int32_t*)0xbf885260 = 0;
    *(char*)0xbf885250 = (char)__asm_ins(0, 5, 1);
    *(char*)0xbf885250 = (char)__asm_ins(0, 1, 1);
    if ((*(int32_t*)0xbf885200 & 8) != 0) {
        *(int32_t*)0xbf885200 = 8;
        *(char*)0xa0000484 = 0;
        *(char*)0xa00004d4 = 0;
        *(int32_t*)0xa00004d4 = __asm_ins(0, 8, 16);
        while ((*(int32_t*)0xbf885200 & 8) != 0) {
            // 0x1d00e980
            *(int32_t*)0xbf885200 = 8;
            *(char*)0xa0000484 = 0;
            *(char*)0xa00004d4 = 0;
            *(int32_t*)0xa00004d4 = __asm_ins(0, 8, 16);
        }
    }
    // 0x1d00e9b0
    int32_t v4; // 0x1d00e840
    *(int32_t *)(v4 - 0x7f2c) = 1;
    *(int32_t *)(v4 - 0x7f24) = 1;
    *(int32_t *)(v4 - 0x7ef4) = 0;
    *(int32_t *)(v4 - 0x7ef0) = 0;
    *(int32_t *)(v4 - 0x7f10) = 0;
    int32_t v5 = -0x5ffffe00; // 0x1d00e9e4
    int32_t v6 = -0x5ffffdf0; // 0x1d00e9e4
    int32_t v7 = 0; // 0x1d00e9e4
    *(int32_t *)v6 = 0;
    *(int32_t *)v5 = 0;
    int32_t v8 = v7 + v4;
    *(char *)(v8 - 0x7edc) = 0;
    *(char *)(v8 - 0x7f0c) = 0;
    v7++;
    v5 += 4;
    v6 += 4;
    while (v7 != 4) {
        // 0x1d00e9e8
        *(int32_t *)v6 = 0;
        *(int32_t *)v5 = 0;
        v8 = v7 + v4;
        *(char *)(v8 - 0x7edc) = 0;
        *(char *)(v8 - 0x7f0c) = 0;
        v7++;
        v5 += 4;
        v6 += 4;
    }
    // 0x1d00ea10
    *(int32_t*)0xa0000210 = -0x5ffffbf0;
    *(int32_t*)0xbf885300 = 13;
    *(int32_t*)0xa0000404 = __asm_ext(v4 - 0x7f18, 0, 29);
    *(int16_t *)-0x5ffffbfe = (int16_t)__asm_ins(64, 0, 10);
    *(int16_t *)-0x5ffffc00 = 132;
    *(char *)(v4 - 0x7f28) = 0;
    *(int32_t *)(v4 - 0x7eec) = 0;
    return 132;
}

// Address range: 0x1d0105a4 - 0x1d0105b4
int32_t function_1d0105a4(int32_t a1) {
    // 0x1d0105a4
    int32_t v1; // 0x1d0105a4
    return (int32_t)*(char *)(a1 - 0x7f44 + v1);
}

// Address range: 0x1d010aec - 0x1d010d20
int32_t function_1d010aec(int32_t a1) {
    switch (a1) {
        case 3: {
            // 0x1d010b24
            *(int32_t*)0xbf8860e4 = 512;
            *(int32_t*)0xbf8860c4 = 512;
            *(int32_t*)0xbf805820 = 160;
            while ((*(int32_t*)0xbf805810 & 0x1f000000) == 0) {
                // continue -> 0x1d010bb8
            }
            // 0x1d010c4c
            *(int32_t*)0xbf805820 = 0;
            while ((*(int32_t*)0xbf805810 & 0x1f000000) == 0) {
                // continue -> 0x1d010c58
            }
            // 0x1d010c68
            *(int32_t*)0xbf8860e8 = 512;
            *(int32_t*)0xbf8860c4 = 512;
            return 0;
        }
        case 4: {
            // 0x1d010b40
            *(int32_t*)0xbf886064 = 256;
            *(int32_t*)0xbf886044 = 256;
            *(int32_t*)0xbf805c20 = 160;
            while ((*(int32_t*)0xbf805c10 & 0x1f000000) == 0) {
                // continue -> 0x1d010be8
            }
            // 0x1d010c78
            *(int32_t*)0xbf805c20 = 0;
            while ((*(int32_t*)0xbf805c10 & 0x1f000000) == 0) {
                // continue -> 0x1d010c84
            }
            // 0x1d010c94
            *(int32_t*)0xbf886068 = 256;
            *(int32_t*)0xbf886044 = 256;
            return 0;
        }
        case 2: {
            // 0x1d010b08
            *(int32_t*)0xbf8861a4 = 512;
            *(int32_t*)0xbf886184 = 512;
            *(int32_t*)0xbf805a20 = 160;
            while ((*(int32_t*)0xbf805a10 & 0x1f000000) == 0) {
                // continue -> 0x1d010b88
            }
            // 0x1d010c20
            *(int32_t*)0xbf805a20 = 0;
            while ((*(int32_t*)0xbf805a10 & 0x1f000000) == 0) {
                // continue -> 0x1d010c2c
            }
            // 0x1d010c3c
            *(int32_t*)0xbf8861a8 = 512;
            *(int32_t*)0xbf886184 = 512;
            return 0;
        }
    }
    // 0x1d010d18
    return 0;
}

// Address range: 0x1d011104 - 0x1d0112bc
int32_t function_1d011104(int32_t a1, uint32_t a2) {
    switch (a1) {
        case 3: {
            // 0x1d011154
            *(int32_t*)0xbf8860e4 = 512;
            *(int32_t*)0xbf8860c4 = 512;
            *(int32_t*)0xbf805820 = (1 << a2 % 4) % 128 | 128;
            while ((*(int32_t*)0xbf805810 & 0x1f000000) == 0) {
                // continue -> 0x1d01120c
            }
            // 0x1d011288
            *(int32_t*)0xbf8860e8 = 512;
            *(int32_t*)0xbf8860c4 = 512;
            return 512;
        }
        case 4: {
            // 0x1d01117c
            *(int32_t*)0xbf886064 = 256;
            *(int32_t*)0xbf886044 = 256;
            *(int32_t*)0xbf805c20 = (1 << a2 % 4) % 128 | 128;
            while ((*(int32_t*)0xbf805c10 & 0x1f000000) == 0) {
                // continue -> 0x1d011238
            }
            // 0x1d0112a4
            *(int32_t*)0xbf886068 = 256;
            *(int32_t*)0xbf886044 = 256;
            return 256;
        }
        case 2: {
            // 0x1d011128
            *(int32_t*)0xbf8861a4 = 512;
            *(int32_t*)0xbf886184 = 512;
            *(int32_t*)0xbf805a20 = (1 << a2 % 4) % 128 | 128;
            while ((*(int32_t*)0xbf805a10 & 0x1f000000) == 0) {
                // continue -> 0x1d0111e0
            }
            // 0x1d01126c
            *(int32_t*)0xbf8861a8 = 512;
            *(int32_t*)0xbf886184 = 512;
            // 0x1d01127c
            return 512;
        }
    }
    // 0x1d01127c
    return 512;
}

// Address range: 0x1d011494 - 0x1d011770
int32_t function_1d011494(int32_t a1, int32_t a2, uint32_t a3, int32_t a4, int32_t a5, uint32_t a6) {
    switch (a1) {
        case 3: {
            // 0x1d0114ec
            *(int32_t*)0xbf8860e4 = 512;
            *(int32_t*)0xbf8860c4 = 512;
            // break -> 0x1d011520
            break;
        }
        case 4: {
            // 0x1d011508
            *(int32_t*)0xbf886064 = 256;
            *(int32_t*)0xbf886044 = 256;
            // break -> 0x1d011520
            break;
        }
        case 2: {
            // 0x1d0114d0
            *(int32_t*)0xbf8861a4 = 512;
            *(int32_t*)0xbf886184 = 512;
            // break -> 0x1d011520
            break;
        }
    }
    char v1; // bp-7, 0x1d011494
    if (a4 == 0) {
        // 0x1d011560
        v1 = a3 / 8;
    } else {
        // 0x1d011530
        v1 = a3 / 0x200000;
        __asm_ins(0, 0, 5);
        __asm_ext(a3, 16, 2);
    }
    int32_t * v2 = (int32_t*)0xbf805a20; // 0x1d011494
    int32_t * v3 = (int32_t*)0xbf805a10; // 0x1d011494
    int32_t result = 2; // 0x1d011494
    switch (a1) {
        case 3: {
            // 0x1d0115c0
            v2 = (int32_t*)0xbf805820;
            v3 = (int32_t*)0xbf805810;
            goto lab_0x1d0115d0;
        }
        case 4: {
            // 0x1d0115ac
            v2 = (int32_t*)0xbf805c20;
            v3 = (int32_t*)0xbf805c10;
            goto lab_0x1d0115d0;
        }
        case 2: {
            goto lab_0x1d0115d0;
        }
        default: {
            return result;
        }
    }
  lab_0x1d0115d0:;
    uint32_t v4 = a6 % 256; // 0x1d011498
    int32_t v5 = v4 < 8 ? v4 : 8;
    int32_t v6 = &v1;
    *v2 = (int32_t)*(char *)(v6 - 1);
    int32_t v7 = v6 + 1; // 0x1d0115e4
    int32_t v8; // bp-2, 0x1d011494
    while (v6 != (int32_t)&v8) {
        // 0x1d0115dc
        v6 = v7;
        *v2 = (int32_t)*(char *)(v6 - 1);
        v7 = v6 + 1;
    }
    // 0x1d0115f4
    while ((*v3 & 0x1e000000) < 0x6000000) {
        // continue -> 0x1d0115f4
    }
    int32_t * v9 = (int32_t*)0xbf805a20; // 0x1d011494
    int32_t * v10 = (int32_t*)0xbf805a10; // 0x1d011494
    result = 2;
    switch (a1) {
        case 3: {
            // 0x1d011668
            v9 = (int32_t*)0xbf805820;
            v10 = (int32_t*)0xbf805810;
            goto lab_0x1d011678;
        }
        case 4: {
            // 0x1d011654
            v9 = (int32_t*)0xbf805c20;
            v10 = (int32_t*)0xbf805c10;
            goto lab_0x1d011678;
        }
        case 2: {
            goto lab_0x1d011678;
        }
        default: {
            return result;
        }
    }
  lab_0x1d011678:
    // 0x1d011678
    if (a5 == 0) {
        if (v5 != 0) {
            // 0x1d0116b4
            *v9 = 0;
        }
    } else {
        // 0x1d011690
        if (v5 != 0) {
            int32_t v11 = a5 + 1;
            *v9 = (int32_t)*(char *)a5;
            int32_t v12 = v11; // 0x1d0116a8
            while (v11 != v5 + a5) {
                // 0x1d01169c
                v11 = v12 + 1;
                *v9 = (int32_t)*(char *)v12;
                v12 = v11;
            }
        }
    }
    // 0x1d0116c8
    while ((*v10 & 0x1f000000) < 0x1000000 * v5) {
        // continue -> 0x1d0116cc
    }
    // 0x1d011700
    result = 2;
    switch (a1) {
        case 3: {
            // 0x1d011734
            *(int32_t*)0xbf8860e8 = 512;
            *(int32_t*)0xbf8860c4 = 512;
            result = 512;
            // break -> 0x1d011768
            break;
        }
        case 4: {
            // 0x1d011750
            *(int32_t*)0xbf886068 = 256;
            *(int32_t*)0xbf886044 = 256;
            result = 256;
            // break -> 0x1d011768
            break;
        }
        case 2: {
            // 0x1d011718
            *(int32_t*)0xbf8861a8 = 512;
            *(int32_t*)0xbf886184 = 512;
            result = 512;
            // break -> 0x1d011768
            break;
        }
    }
    // 0x1d011768
    return result;
}

// Address range: 0x1d013480 - 0x1d013710
int32_t function_1d013480(int32_t * a1) {
    int32_t v1 = (int32_t)a1;
    int32_t v2; // 0x1d013480
    if ((*(int32_t *)(v2 - 0x7f3c) & 32) != 0) {
        int32_t v3 = *(int32_t*)0xa0000cf8; // 0x1d0134a8
        uint32_t v4 = *(int32_t*)0xa0000cf4; // 0x1d0134b0
        uint32_t v5 = v4 % 0x1000; // 0x1d0134b4
        if (v5 != (v3 + 1) % 0x1000) {
            int32_t * v6 = (int32_t *)(v1 + 4); // 0x1d0134d8
            uint32_t v7 = *v6; // 0x1d0134d8
            int32_t v8 = __asm_ext(v7, 28, 1); // 0x1d0134dc
            int32_t v9; // 0x1d013480
            if (v8 == 0) {
                // 0x1d013504
                v9 = v4 % 2048;
            } else {
                // 0x1d0134e8
                v9 = __asm_ext(*v6, 10, 18) | 0x40000 * v5 & 0x1ffc0000;
            }
            int32_t v10 = 16 * v3 & 0xfff0; // 0x1d0134c4
            uint32_t v11 = v7 % 16; // 0x1d0134e4
            __asm_ins(v9, 0, 29);
            __asm_ins(v8, 29, 1);
            __asm_ins(v11, 30, 2);
            *(int32_t *)(v10 - 0x5ffff300) = __asm_ins(v11 / 4, 30, 2);
            __asm_ins(5, 27, 3);
            *(int32_t *)(v10 - 0x5ffff304) = __asm_ins(*(int32_t *)(v2 - 0x7f38), 0, 27);
            __asm_lwl(*(int32_t *)(v1 + 11));
            int32_t v12 = __asm_lwr(*(int32_t *)(v1 + 8)); // 0x1d013548
            __asm_lwl(*(int32_t *)(v1 + 15));
            int32_t v13 = __asm_lwr(*(int32_t *)(v1 + 12)); // 0x1d013550
            *(int32_t *)(v10 - 0x5ffff2fc) = v12;
            *(int32_t *)(v10 - 0x5ffff2f8) = v13;
            uint32_t v14 = (*(int32_t*)0xa0000cf8 + 1) % 0x1000; // 0x1d01356c
            if (*(int32_t*)0xa0000cf4 % 0x1000 != v14) {
                // 0x1d013580
                *(int32_t*)0xa0000cf8 = v14;
            }
        }
    }
    int32_t v15 = *(int32_t*)0xa00008e8 % 64; // 0x1d013624
    int32_t result2; // 0x1d013480
    if (v15 == *(int32_t*)0xa00008ec % 64) {
      lab_0x1d0136ec:;
        int32_t result = function_1d016074(a1); // 0x1d0136f0
        if (result != 0) {
            // 0x1d0136fc
            return result;
        }
        int32_t v16 = *(int32_t*)0xa00008ec; // 0x1d013680
        uint32_t v17 = (v16 + 1) % 64; // 0x1d01368c
        if (*(int32_t*)0xa00008e8 % 64 == v17) {
            // 0x1d0136d8
            *(int32_t*)0xa00008f0 = *(int32_t*)0xa00008f0 + 1;
            result2 = 0;
        } else {
            int32_t v18 = 16 * v16 & 1008; // 0x1d0136a0
            *(int32_t *)(v18 - 0x5ffff70c) = v17;
            *(int32_t *)(v18 - 0x5ffff708) = *(int32_t *)(v1 + 4);
            *(int32_t *)(v18 - 0x5ffff704) = *(int32_t *)(v1 + 8);
            *(int32_t *)(v18 - 0x5ffff700) = *(int32_t *)(v1 + 12);
            *(int32_t*)0xa00008ec = v17;
            result2 = 1;
        }
        // 0x1d0136fc
        return result2;
    }
    int32_t v19 = *(int32_t *)(16 * v15 - 0x5ffff70c); // bp-32, 0x1d013654
    while (function_1d016074(&v19) != 0) {
        int32_t v20 = *(int32_t*)0xa00008e8; // 0x1d013670
        int32_t v21 = *(int32_t*)0xa00008ec; // 0x1d013594
        int32_t v22 = v21; // 0x1d0135a0
        int32_t v23 = v20; // 0x1d0135a0
        if ((v21 ^ v20) % 64 != 0) {
            // 0x1d0135a4
            v23 = (v20 + 1) % 64;
            *(int32_t*)0xa00008e8 = v23;
            v22 = *(int32_t*)0xa00008ec;
        }
        int32_t v24 = v23 % 64; // 0x1d013624
        if (v24 == v22 % 64) {
            goto lab_0x1d0136ec;
        }
        v19 = *(int32_t *)(16 * v24 - 0x5ffff70c);
    }
    int32_t v25 = *(int32_t*)0xa00008ec; // 0x1d0135b4
    uint32_t v26 = (v25 + 1) % 64; // 0x1d0135c0
    if (*(int32_t*)0xa00008e8 % 64 == v26) {
        // 0x1d01360c
        *(int32_t*)0xa00008f0 = *(int32_t*)0xa00008f0 + 1;
        result2 = 0;
    } else {
        int32_t v27 = 16 * v25 & 1008; // 0x1d0135d4
        *(int32_t *)(v27 - 0x5ffff70c) = v26;
        *(int32_t *)(v27 - 0x5ffff708) = *(int32_t *)(v1 + 4);
        *(int32_t *)(v27 - 0x5ffff704) = *(int32_t *)(v1 + 8);
        *(int32_t *)(v27 - 0x5ffff700) = *(int32_t *)(v1 + 12);
        *(int32_t*)0xa00008ec = v26;
        result2 = 1;
    }
    // 0x1d0136fc
    return result2;
}

// Address range: 0x1d013710 - 0x1d0139a0
int32_t pthread_cond_destroy2(int32_t * a1) {
    int32_t v1 = (int32_t)a1;
    int32_t v2; // 0x1d013710
    if ((*(int32_t *)(v2 - 0x7f3c) & 128) != 0) {
        int32_t v3 = *(int32_t*)0xa0000cf8; // 0x1d013738
        uint32_t v4 = *(int32_t*)0xa0000cf4; // 0x1d013740
        uint32_t v5 = v4 % 0x1000; // 0x1d013744
        if (v5 != (v3 + 1) % 0x1000) {
            int32_t * v6 = (int32_t *)(v1 + 4); // 0x1d013768
            uint32_t v7 = *v6; // 0x1d013768
            int32_t v8 = __asm_ext(v7, 28, 1); // 0x1d01376c
            int32_t v9; // 0x1d013710
            if (v8 == 0) {
                // 0x1d013794
                v9 = v4 % 2048;
            } else {
                // 0x1d013778
                v9 = __asm_ext(*v6, 10, 18) | 0x40000 * v5 & 0x1ffc0000;
            }
            int32_t v10 = 16 * v3 & 0xfff0; // 0x1d013754
            uint32_t v11 = v7 % 16; // 0x1d013774
            __asm_ins(v9, 0, 29);
            __asm_ins(v8, 29, 1);
            __asm_ins(v11, 30, 2);
            *(int32_t *)(v10 - 0x5ffff300) = __asm_ins(v11 / 4, 30, 2);
            __asm_ins(7, 27, 3);
            *(int32_t *)(v10 - 0x5ffff304) = __asm_ins(*(int32_t *)(v2 - 0x7f38), 0, 27);
            __asm_lwl(*(int32_t *)(v1 + 11));
            int32_t v12 = __asm_lwr(*(int32_t *)(v1 + 8)); // 0x1d0137d8
            __asm_lwl(*(int32_t *)(v1 + 15));
            int32_t v13 = __asm_lwr(*(int32_t *)(v1 + 12)); // 0x1d0137e0
            *(int32_t *)(v10 - 0x5ffff2fc) = v12;
            *(int32_t *)(v10 - 0x5ffff2f8) = v13;
            uint32_t v14 = (*(int32_t*)0xa0000cf8 + 1) % 0x1000; // 0x1d0137fc
            if (*(int32_t*)0xa0000cf4 % 0x1000 != v14) {
                // 0x1d013810
                *(int32_t*)0xa0000cf8 = v14;
            }
        }
    }
    int32_t v15 = *(int32_t*)0xa00004dc % 64; // 0x1d0138b4
    int32_t result2; // 0x1d013710
    if (v15 == *(int32_t*)0xa00004e0 % 64) {
      lab_0x1d01397c:;
        int32_t result = function_1d016384(a1); // 0x1d013980
        if (result != 0) {
            // 0x1d01398c
            return result;
        }
        int32_t v16 = *(int32_t*)0xa00004e0; // 0x1d013910
        uint32_t v17 = (v16 + 1) % 64; // 0x1d01391c
        if (*(int32_t*)0xa00004dc % 64 == v17) {
            // 0x1d013968
            *(int32_t*)0xa00004e4 = *(int32_t*)0xa00004e4 + 1;
            result2 = 0;
        } else {
            int32_t v18 = 16 * v16 & 1008; // 0x1d013930
            *(int32_t *)(v18 - 0x5ffffb18) = v17;
            *(int32_t *)(v18 - 0x5ffffb14) = *(int32_t *)(v1 + 4);
            *(int32_t *)(v18 - 0x5ffffb10) = *(int32_t *)(v1 + 8);
            *(int32_t *)(v18 - 0x5ffffb0c) = *(int32_t *)(v1 + 12);
            *(int32_t*)0xa00004e0 = v17;
            result2 = 1;
        }
        // 0x1d01398c
        return result2;
    }
    int32_t v19 = *(int32_t *)(16 * v15 - 0x5ffffb18); // bp-32, 0x1d0138e4
    while (function_1d016384(&v19) != 0) {
        int32_t v20 = *(int32_t*)0xa00004dc; // 0x1d013900
        int32_t v21 = *(int32_t*)0xa00004e0; // 0x1d013824
        int32_t v22 = v21; // 0x1d013830
        int32_t v23 = v20; // 0x1d013830
        if ((v21 ^ v20) % 64 != 0) {
            // 0x1d013834
            v23 = (v20 + 1) % 64;
            *(int32_t*)0xa00004dc = v23;
            v22 = *(int32_t*)0xa00004e0;
        }
        int32_t v24 = v23 % 64; // 0x1d0138b4
        if (v24 == v22 % 64) {
            goto lab_0x1d01397c;
        }
        v19 = *(int32_t *)(16 * v24 - 0x5ffffb18);
    }
    int32_t v25 = *(int32_t*)0xa00004e0; // 0x1d013844
    uint32_t v26 = (v25 + 1) % 64; // 0x1d013850
    if (*(int32_t*)0xa00004dc % 64 == v26) {
        // 0x1d01389c
        *(int32_t*)0xa00004e4 = *(int32_t*)0xa00004e4 + 1;
        result2 = 0;
    } else {
        int32_t v27 = 16 * v25 & 1008; // 0x1d013864
        *(int32_t *)(v27 - 0x5ffffb18) = v26;
        *(int32_t *)(v27 - 0x5ffffb14) = *(int32_t *)(v1 + 4);
        *(int32_t *)(v27 - 0x5ffffb10) = *(int32_t *)(v1 + 8);
        *(int32_t *)(v27 - 0x5ffffb0c) = *(int32_t *)(v1 + 12);
        *(int32_t*)0xa00004e0 = v26;
        result2 = 1;
    }
    // 0x1d01398c
    return result2;
}

// Address range: 0x1d013aac - 0x1d013bb8
int32_t pthread_cond_destroy(int32_t * a1) {
    uint32_t v1 = (int32_t)a1;
    int32_t v2; // 0x1d013aac
    if ((*(int32_t *)(v2 - 0x7f3c) & 8) == 0) {
        // 0x1d013ba4
        return function_1d015d40(v1);
    }
    int32_t v3 = *(int32_t*)0xa0000cf8; // 0x1d013ac8
    if ((*(int32_t*)0xa0000cf4 ^ v3 + 1) % 0x1000 == 0) {
        // 0x1d013ba4
        return function_1d015d40(v1);
    }
    int32_t * v4 = (int32_t *)(v1 + 4); // 0x1d013af8
    uint32_t v5 = *v4; // 0x1d013af8
    int32_t v6 = __asm_ext(v5, 28, 1); // 0x1d013afc
    int32_t v7; // 0x1d013aac
    if (v6 == 0) {
        // 0x1d013b24
        v7 = v1 % 2048;
    } else {
        // 0x1d013b08
        v7 = __asm_ext(*v4, 10, 18) | 0x40000 * v1 & 0x1ffc0000;
    }
    int32_t v8 = 16 * v3 & 0xfff0; // 0x1d013ae4
    uint32_t v9 = v5 % 16; // 0x1d013b04
    __asm_ins(v7, 0, 29);
    __asm_ins(v6, 29, 1);
    __asm_ins(v9, 30, 2);
    *(int32_t *)(v8 - 0x5ffff300) = __asm_ins(v9 / 4, 30, 2);
    __asm_ins(3, 27, 3);
    *(int32_t *)(v8 - 0x5ffff304) = __asm_ins(*(int32_t *)(v2 - 0x7f38), 0, 27);
    __asm_lwl(*(int32_t *)(v1 + 11));
    int32_t v10 = __asm_lwr(*(int32_t *)(v1 + 8)); // 0x1d013b68
    __asm_lwl(*(int32_t *)(v1 + 15));
    int32_t v11 = __asm_lwr(*(int32_t *)(v1 + 12)); // 0x1d013b70
    *(int32_t *)(v8 - 0x5ffff2fc) = v10;
    *(int32_t *)(v8 - 0x5ffff2f8) = v11;
    uint32_t v12 = (*(int32_t*)0xa0000cf8 + 1) % 0x1000; // 0x1d013b8c
    if (*(int32_t*)0xa0000cf4 % 0x1000 != v12) {
        // 0x1d013ba0
        *(int32_t*)0xa0000cf8 = v12;
    }
    // 0x1d013ba4
    return function_1d015d40(v1);
}

// Address range: 0x1d01501c - 0x1d015030
int32_t function_1d01501c(void) {
    // 0x1d01501c
    return (int32_t)*(char*)0xa00001e8;
}

// Address range: 0x1d015d40 - 0x1d015dd0
int32_t function_1d015d40(int32_t a1) {
    int32_t v1 = function_1d01c068(1, 1); // 0x1d015d58
    int32_t result = 0; // 0x1d015d5c
    if (v1 != 0) {
        // 0x1d015d64
        __asm_lwl(*(int32_t *)(a1 + 3));
        int32_t v2 = __asm_lwr(1); // 0x1d015d68
        __asm_lwl(*(int32_t *)(a1 + 7));
        int32_t v3 = __asm_lwr(*(int32_t *)(a1 + 4)); // 0x1d015d70
        __asm_lwl(*(int32_t *)(a1 + 11));
        int32_t v4 = __asm_lwr(*(int32_t *)(a1 + 8)); // 0x1d015d78
        __asm_lwl(*(int32_t *)(a1 + 15));
        int32_t v5 = __asm_lwr(*(int32_t *)(a1 + 12)); // 0x1d015d80
        __asm_swl(v2, *(int32_t *)(v1 + 3));
        __asm_swr(v2, *(int32_t *)v1);
        __asm_swl(v3, *(int32_t *)(v1 + 7));
        __asm_swr(v3, *(int32_t *)(v1 + 4));
        __asm_swl(v4, *(int32_t *)(v1 + 11));
        __asm_swr(v4, *(int32_t *)(v1 + 8));
        __asm_swl(v5, *(int32_t *)(v1 + 15));
        __asm_swr(v5, *(int32_t *)(v1 + 12));
        function_1d01c2b8(1, 1);
        function_1d01c2e4(1, 1);
        result = 1;
    }
    // 0x1d015dc0
    return result;
}

// Address range: 0x1d015dd0 - 0x1d015e60
int32_t function_1d015dd0(int32_t * a1) {
    int32_t v1 = function_1d01c068(1, 2); // 0x1d015de8
    int32_t result = 0; // 0x1d015dec
    if (v1 != 0) {
        int32_t v2 = (int32_t)a1;
        __asm_lwl(*(int32_t *)(v2 + 3));
        int32_t v3 = __asm_lwr(1); // 0x1d015df8
        __asm_lwl(*(int32_t *)(v2 + 7));
        int32_t v4 = __asm_lwr(*(int32_t *)(v2 + 4)); // 0x1d015e00
        __asm_lwl(*(int32_t *)(v2 + 11));
        int32_t v5 = __asm_lwr(*(int32_t *)(v2 + 8)); // 0x1d015e08
        __asm_lwl(*(int32_t *)(v2 + 15));
        int32_t v6 = __asm_lwr(*(int32_t *)(v2 + 12)); // 0x1d015e10
        __asm_swl(v3, *(int32_t *)(v1 + 3));
        __asm_swr(v3, *(int32_t *)v1);
        __asm_swl(v4, *(int32_t *)(v1 + 7));
        __asm_swr(v4, *(int32_t *)(v1 + 4));
        __asm_swl(v5, *(int32_t *)(v1 + 11));
        __asm_swr(v5, *(int32_t *)(v1 + 8));
        __asm_swl(v6, *(int32_t *)(v1 + 15));
        __asm_swr(v6, *(int32_t *)(v1 + 12));
        function_1d01c2b8(1, 2);
        function_1d01c2e4(1, 2);
        result = 1;
    }
    // 0x1d015e50
    return result;
}

// Address range: 0x1d016074 - 0x1d016128
int32_t function_1d016074(int32_t * a1) {
    int32_t result = function_1d0105a4(3); // 0x1d01608c
    if (result == 0 || (function_1d010aec(3) & 4) != 0) {
        // 0x1d016114
        return 0;
    }
    int32_t v1 = (int32_t)a1;
    int32_t * v2 = (int32_t *)(v1 + 4); // 0x1d0160b0
    uint32_t v3 = *v2; // 0x1d0160b0
    int32_t v4 = __asm_ext(v3, 28, 1); // 0x1d0160b4
    int32_t v5 = 3; // 0x1d0160bc
    if (v4 != 0) {
        // 0x1d0160c0
        v5 = __asm_ext(*v2, 10, 18) | 0xc0000;
    }
    // 0x1d0160e4
    function_1d011494(3, 0, v5, v4, v1 + 8, v3 % 16);
    function_1d011104(3, 0);
    // 0x1d016114
    return result;
}

// Address range: 0x1d016384 - 0x1d016438
int32_t function_1d016384(int32_t * a1) {
    int32_t result = function_1d0105a4(2); // 0x1d01639c
    if (result == 0 || (function_1d010aec(2) & 4) != 0) {
        // 0x1d016424
        return 0;
    }
    int32_t v1 = (int32_t)a1;
    int32_t * v2 = (int32_t *)(v1 + 4); // 0x1d0163c0
    uint32_t v3 = *v2; // 0x1d0163c0
    int32_t v4 = __asm_ext(v3, 28, 1); // 0x1d0163c4
    int32_t v5 = 2; // 0x1d0163cc
    if (v4 != 0) {
        // 0x1d0163d0
        v5 = __asm_ext(*v2, 10, 18) | 0x80000;
    }
    // 0x1d0163f4
    function_1d011494(2, 0, v5, v4, v1 + 8, v3 % 16);
    function_1d011104(2, 0);
    // 0x1d016424
    return result;
}

// Address range: 0x1d017074 - 0x1d017230
int32_t function_1d017074(int32_t * a1) {
    int32_t v1 = (int32_t)a1 + 4; // 0x1d017090
    int32_t * v2 = (int32_t *)v1; // 0x1d017090
    int32_t v3 = *v2; // 0x1d017090
    int32_t v4; // 0x1d017074
    char * v5 = (char *)(v4 - 0x7fb0);
    int32_t v6 = 0; // 0x1d01709c
    if (__asm_ext(v3, 25, 1) != 0) {
        // 0x1d0170a0
        v6 = (int32_t)(*v5 % 2 ^ 1);
    }
    int32_t v7 = *v2; // 0x1d0170ac
    int32_t v8 = __asm_ext(v7, 25, 1); // 0x1d0170b0
    char v9 = v8; // 0x1d0170b8
    *v5 = v9;
    uint16_t v10 = *(int16_t *)v1; // 0x1d0170bc
    *(int32_t *)(v4 - 0x7fa8) = (int32_t)v10;
    *(int32_t *)(v4 - 0x7fa4) = 200;
    int32_t v11 = __asm_ext(v7, 24, 1); // 0x1d0170cc
    uint32_t v12 = __asm_ext(v7, 27, 1); // 0x1d0170d4
    if (*(int32_t*)0xa0013668 == 0) {
        goto lab_0x1d0171d0;
    } else {
        if (v12 % 256 == 0) {
            goto lab_0x1d017134;
        } else {
            // 0x1d0170fc
            if (*(char*)0xa001366f == 0) {
                // 0x1d01710c
                *(char*)0xa001365d = 1;
                int32_t * v13 = (int32_t *)(v4 - 0x7fb4); // 0x1d017118
                if (*v13 == 0) {
                    // 0x1d017124
                    *v13 = 1;
                    *(int32_t *)(v4 - 0x7fbc) = 3;
                }
                goto lab_0x1d0171d0;
            } else {
                goto lab_0x1d017134;
            }
        }
    }
  lab_0x1d0171d0:
    if (v6 != 0) {
        int32_t * v14 = (int32_t *)(v4 - 0x7fb4); // 0x1d0171d8
        if (*v14 == 1) {
            // 0x1d0171e4
            *v14 = 2;
        }
    }
    // 0x1d0171f0
    *(int32_t*)0xa0013668 = 100;
    *(char*)0xa001366c = (char)v11;
    *(char*)0xa001366d = v9;
    *(char*)0xa001366e = (char)v6;
    *(char*)0xa001366f = (char)v12;
    *(char*)0xa0013670 = (char)((v3 & 0x74000000) != 0);
    return -0x5ffec9d4;
  lab_0x1d017134:
    // 0x1d017134
    if (*(char*)0xa001365c != 0) {
        // 0x1d017140
        if ((v11 | v8) % 256 == 0 == (*(char*)0xa001366c != 0)) {
            // 0x1d01715c
            if (*(char*)0xa001363d == 0) {
                // 0x1d017168
                if (*(char*)0xa0013655 == 0) {
                    // 0x1d017174
                    if (*(char*)0xa001366d == 0) {
                        char v15 = *(char *)(v4 - 0x7faf); // 0x1d017184
                        if (v10 == 0 != (*(int32_t *)(v4 - 0x7fac) == 0 || v15 == 1)) {
                            // 0x1d01719c
                            if (function_1d01501c() == 0) {
                                // 0x1d0171ac
                                *(char*)0xa001365d = 1;
                                *(char *)(v4 - 0x7fe8) = 0;
                                int32_t * v16 = (int32_t *)(v4 - 0x7fb4); // 0x1d0171b8
                                if (*v16 == 0) {
                                    // 0x1d0171c4
                                    *v16 = 1;
                                    *(int32_t *)(v4 - 0x7fbc) = 13;
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    goto lab_0x1d0171d0;
}

// Address range: 0x1d017288 - 0x1d017290
int32_t exit(void) {
    // 0x1d017288
    int32_t v1; // 0x1d017288
    return *(int32_t *)(v1 - 0x7fb4);
}

// Address range: 0x1d0172b4 - 0x1d0172d8
int32_t function_1d0172b4(void) {
    // 0x1d0172b4
    int32_t v1; // 0x1d0172b4
    int32_t v2 = *(int32_t *)(v1 - 0x7fb4); // 0x1d0172b4
    int32_t result = 1; // 0x1d0172bc
    if (v2 != 0) {
        // 0x1d0172c0
        result = v2 == 1 ? (int32_t)*(char *)(v1 - 0x7fe8) : 0;
    }
    // 0x1d0172d0
    return result;
}

// Address range: 0x1d01854c - 0x1d018560
int32_t function_1d01854c(void) {
    // 0x1d01854c
    return (int32_t)*(char*)0xa00133b2;
}

// Address range: 0x1d01a5f4 - 0x1d01a78c
int32_t pthread_cond_destroy3(void) {
    // 0x1d01a5f4
    int32_t v1; // 0x1d01a5f4
    char * v2 = (char *)(v1 - 0x7f18); // 0x1d01a5f4
    if (*v2 % 32 != 1) {
        // 0x1d01a784
        return 1;
    }
    char result = *(char *)(v1 - 0x7f14); // 0x1d01a608
    if (result != 0) {
        // 0x1d01a784
        return result;
    }
    char * v3 = (char *)(v1 - 0x7f17); // 0x1d01a618
    if (*v3 == 6) {
        // 0x1d01a62c
        switch (*(char *)(v1 - 0x7f15)) {
            case 33: {
                // 0x1d01a650
                if (*(char *)(v1 - 0x7f28) == 1) {
                    // 0x1d01a664
                    *(int32_t*)0xa0000480 = -0x62fe4cbe;
                    *(int16_t *)-0x5ffffb78 = 9;
                    *(char*)0xa0000484 = -64;
                }
                // break -> 0x1d01a6ac
                break;
            }
            case 34: {
                // 0x1d01a68c
                *(int32_t*)0xa0000480 = -0x62fe4d14;
                *(int16_t *)-0x5ffffb78 = 29;
                *(char*)0xa0000484 = -64;
                // break -> 0x1d01a6ac
                break;
            }
        }
    }
    // 0x1d01a6ac
    if ((*v2 & 96) != 32) {
        // 0x1d01a784
        return 32;
    }
    unsigned char result4 = *v3; // 0x1d01a6c0
    if (result4 == 3) {
        // 0x1d01a748
        *(int32_t*)0xa0000480 = v1 - 0x7ed7;
        *(int16_t *)-0x5ffffb78 = 1;
        *(char*)0xa0000484 = -127;
        return -0x5ffffb80;
    }
    if (result4 < 4) {
        // 0x1d01a6dc
        if (result4 != 2) {
            // 0x1d01a6e8
            return -0x60000000;
        }
        // 0x1d01a708
        *(int32_t*)0xa0000480 = v1 - 0x7ed8;
        *(int16_t *)-0x5ffffb78 = 1;
        *(char*)0xa0000484 = -63;
        return -0x5ffffb80;
    }
    // 0x1d01a6f0
    switch (result4) {
        case 10: {
            // 0x1d01a72c
            *(char*)0xa0000484 = -128;
            unsigned char result2 = *(char *)(v1 - 0x7f15); // 0x1d01a73c
            *(char *)(v1 - 0x7ed8) = result2;
            return result2;
        }
        case 11: {
            // 0x1d01a770
            *(char*)0xa0000484 = -128;
            char result3 = *(char *)(v1 - 0x7f16); // 0x1d01a77c
            *(char *)(v1 - 0x7ed7) = result3;
            // 0x1d01a784
            return result3;
        }
    }
    // 0x1d01a6e8
    return result4;
}

// Address range: 0x1d01c068 - 0x1d01c0ac
int32_t function_1d01c068(int32_t a1, int32_t a2) {
    int32_t v1 = *(int32_t *)(4 * a1 - 0x5ffffe08) + 64 * a2; // 0x1d01c080
    if (__asm_ext(*(int32_t *)(v1 + 864), 10, 1) == 0) {
        // 0x1d01c0a4
        return 0;
    }
    // 0x1d01c094
    return *(int32_t *)(v1 + 880) | -0x60000000;
}

// Address range: 0x1d01c2b8 - 0x1d01c2e4
int32_t function_1d01c2b8(int32_t a1, int32_t a2) {
    int32_t result = *(int32_t *)(4 * a1 - 0x5ffffe08) + 64 * a2; // 0x1d01c2d0
    *(int32_t *)(result + 856) = 0x2000;
    return result;
}

// Address range: 0x1d01c2e4 - 0x1d01c310
int32_t function_1d01c2e4(int32_t a1, int32_t a2) {
    int32_t result = *(int32_t *)(4 * a1 - 0x5ffffe08) + 64 * a2; // 0x1d01c2fc
    *(int32_t *)(result + 856) = 8;
    return result;
}

// Address range: 0x1d01c53c - 0x1d01c544
int32_t exit3(void) {
    // 0x1d01c53c
    int32_t result; // 0x1d01c53c
    __asm_di(result);
    return result;
}

// --------------------- Meta-Information ---------------------

// Detected functions: 25
