//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int32_t exit(void);
int32_t exit2(void);
int32_t function_1d027174(int32_t result, uint16_t a2, int32_t a3);
int32_t Stolx(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t Stolx2(int32_t a1, int32_t a2, uint32_t a3, int32_t a4);

// ------------------------ Functions -------------------------

// Address range: 0x1d01609c - 0x1d0162c4
int32_t exit(void) {
    // 0x1d01609c
    *(int32_t*)0xbf881074 = 0x2000000;
    *(int32_t*)0xbf885220 = 255;
    *(int32_t*)0xbf885200 = 255;
    *(int32_t*)0xbf885300 = 0;
    *(int32_t*)0xbf8852e0 = 0;
    *(int32_t*)0xbf885230 = 159;
    *(int32_t*)0xbf885210 = 159;
    uint32_t v1 = *(int32_t*)0xbf885070 % 16; // 0x1d0160d4
    *(int32_t*)0xbf885070 = v1;
    uint32_t v2 = __asm_ext(-0x5ffffc00, 0, 29); // 0x1d0160e0
    *(int32_t*)0xbf885070 = v1;
    *(char*)0xbf885080 = (char)__asm_ins(1, 0, 1);
    *(int32_t*)0xbf885310 = 0;
    *(int32_t*)0xbf8852d0 = v2 / 0x1000000;
    *(int32_t*)0xbf885320 = 0;
    *(int32_t*)0xbf8852c0 = v2 / 0x10000;
    *(int32_t*)0xbf885330 = 0;
    *(int32_t*)0xbf885270 = v2 / 256;
    *(int32_t*)0xa0000400 = 0;
    *(int32_t*)0xa0000404 = 0;
    *(int32_t*)0xa0000408 = 0;
    *(int32_t*)0xa000040c = 0;
    *(int32_t*)0xa0000410 = 0;
    *(int32_t*)0xa0000414 = 0;
    *(int32_t*)0xa0000418 = 0;
    *(int32_t*)0xa000041c = 0;
    *(int32_t*)0xa0000420 = 0;
    *(int32_t*)0xa0000424 = 0;
    *(int32_t*)0xa0000428 = 0;
    *(int32_t*)0xa000042c = 0;
    *(int32_t*)0xa0000430 = 0;
    *(int32_t*)0xa0000434 = 0;
    *(int32_t*)0xa0000438 = 0;
    *(int32_t*)0xa000043c = 0;
    *(int32_t*)0xa0000440 = 0;
    *(int32_t*)0xa0000444 = 0;
    *(int32_t*)0xa0000448 = 0;
    *(int32_t*)0xa000044c = 0;
    *(int32_t*)0xa0000450 = 0;
    *(int32_t*)0xa0000454 = 0;
    *(int32_t*)0xa0000458 = 0;
    *(int32_t*)0xa000045c = 0;
    *(int32_t*)0xa0000460 = 0;
    *(int32_t*)0xa0000464 = 0;
    *(int32_t*)0xa0000468 = 0;
    *(int32_t*)0xa000046c = 0;
    *(int32_t*)0xa0000470 = 0;
    *(int32_t*)0xa0000474 = 0;
    *(int32_t*)0xa0000478 = 0;
    *(int32_t*)0xa000047c = 0;
    *(char*)0xbf885250 = (char)__asm_ins(1, 1, 1);
    *(int32_t*)0xbf885260 = 0;
    *(char*)0xbf885250 = (char)__asm_ins(0, 5, 1);
    *(char*)0xbf885250 = (char)__asm_ins(0, 1, 1);
    if ((*(int32_t*)0xbf885200 & 8) != 0) {
        *(int32_t*)0xbf885200 = 8;
        *(char*)0xa0000484 = 0;
        *(char*)0xa00004d4 = 0;
        *(int32_t*)0xa00004d4 = __asm_ins(0, 8, 16);
        while ((*(int32_t*)0xbf885200 & 8) != 0) {
            // 0x1d0161f0
            *(int32_t*)0xbf885200 = 8;
            *(char*)0xa0000484 = 0;
            *(char*)0xa00004d4 = 0;
            *(int32_t*)0xa00004d4 = __asm_ins(0, 8, 16);
        }
    }
    // 0x1d016218
    int32_t v3; // 0x1d01609c
    *(int32_t *)(v3 - 0x7efc) = 1;
    *(int32_t *)(v3 - 0x7ef4) = 1;
    *(int32_t *)(v3 - 0x7ec4) = 0;
    *(int32_t *)(v3 - 0x7ec0) = 0;
    *(int32_t *)(v3 - 0x7ee0) = 0;
    *(char *)(v3 - 0x7eac) = 0;
    *(char *)(v3 - 0x7edc) = 0;
    *(char *)(v3 - 0x7eab) = 0;
    *(char *)(v3 - 0x7edb) = 0;
    *(char *)(v3 - 0x7eaa) = 0;
    *(char *)(v3 - 0x7eda) = 0;
    *(char *)(v3 - 0x7ea9) = 0;
    *(char *)(v3 - 0x7ed9) = 0;
    *(int32_t*)0xbf885300 = 13;
    *(int32_t*)0xa0000404 = __asm_ext(v3 - 0x7ee8, 0, 29);
    *(int16_t *)-0x5ffffbfe = (int16_t)__asm_ins(64, 0, 10);
    *(int32_t*)0xa0000200 = 0;
    *(int16_t *)-0x5ffffc00 = 132;
    *(int32_t*)0xa0000214 = 0;
    *(char *)(v3 - 0x7ef8) = 0;
    *(int32_t*)0xa0000204 = 0;
    *(int32_t*)0xa0000218 = 0;
    *(int32_t*)0xa0000208 = 0;
    *(int32_t*)0xa000021c = 0;
    *(int32_t*)0xa000020c = 0;
    *(int32_t*)0xa0000210 = -0x5ffffbf0;
    *(int32_t *)(v3 - 0x7ebc) = 0;
    return -0x5ffffbf0;
}

// Address range: 0x1d023a94 - 0x1d023d88
int32_t Stolx2(int32_t a1, int32_t a2, uint32_t a3, int32_t a4) {
    // 0x1d023a94
    char v1; // 0x1d023a94
    int32_t v2; // 0x1d023a94
    if (a4 == 0) {
        // 0x1d023a94
        int32_t v3; // 0x1d023a94
        v1 = v3;
    } else {
        // 0x1d023ad4
        *(int32_t *)a4 = 0;
        v1 = *(char *)&v2;
    }
    int32_t v4 = v1; // 0x1d023ad8
    int32_t v5 = *(int32_t*)0xa0013cac; // 0x1d023ae0
    v2 = v5;
    int32_t v6 = a1; // 0x1d023afc
    int32_t v7 = a1; // 0x1d023afc
    int32_t v8 = v4; // 0x1d023afc
    if ((*(int16_t *)((2 * v4 & 510) + v5) & 324) != 0) {
        v6++;
        int32_t v9 = (int32_t)*(char *)v6; // 0x1d023b04
        v7 = v6;
        v8 = v9;
        while ((*(int16_t *)((2 * v9 & 510) + v5) & 324) != 0) {
            // 0x1d023b04
            v6++;
            v9 = (int32_t)*(char *)v6;
            v7 = v6;
            v8 = v9;
        }
    }
    int32_t v10 = v7; // 0x1d023a94
    int32_t v11 = 43; // 0x1d023a94
    switch (v8) {
        case 45: {
            // 0x1d023cb8
            v10 = v7 + 1;
            v11 = 45;
            // break -> 0x1d023b3c
            break;
        }
        case 43: {
            v10 = v7 + 1;
            v11 = 43;
            // break -> 0x1d023b3c
            break;
        }
    }
    if (a3 == 1 || a3 >= 37) {
        // 0x1d023b54
        if (a2 != 0) {
            *(int32_t *)a2 = a1;
        }
        // 0x1d023b64
        return 0;
    }
    int32_t v12 = a3; // 0x1d023a94
    int32_t v13 = v10; // 0x1d023a94
    char v14; // 0x1d023a94
    int32_t v15; // 0x1d023a94
    int32_t v16; // 0x1d023a94
    int32_t v17; // 0x1d023a94
    int32_t v18; // 0x1d023a94
    int32_t v19; // 0x1d023a94
    int32_t v20; // 0x1d023a94
    int32_t v21; // 0x1d023a94
    switch (a3) {
        case 0: {
            char v22 = *(char *)v10; // 0x1d023cc0
            v14 = v22;
            v21 = 10;
            v18 = v10;
            v15 = v10;
            if (v22 == 48) {
                // 0x1d023d54
                v19 = 8;
                v16 = v10;
                if (__asm_ins(0, 5, 1) == 88) {
                    // 0x1d023d74
                    v12 = 16;
                    v13 = v10 + 2;
                    goto lab_0x1d023ba4;
                } else {
                    goto lab_0x1d023bb4;
                }
            } else {
                goto lab_0x1d023bcc;
            }
        }
        case 16: {
            char v23 = *(char *)v10; // 0x1d023d14
            v14 = v23;
            v21 = 16;
            v18 = v10;
            v15 = v10;
            if (v23 == 48) {
                // 0x1d023d24
                v2 = 48;
                v20 = 16;
                v17 = v10;
                if (__asm_ins(0, 5, 1) == 88) {
                    // 0x1d023d38
                    v12 = 16;
                    v13 = v10 + 2;
                    goto lab_0x1d023ba4;
                } else {
                    goto lab_0x1d023bbc;
                }
            } else {
                goto lab_0x1d023bcc;
            }
        }
        default: {
            goto lab_0x1d023ba4;
        }
    }
  lab_0x1d023ba4:;
    char v24 = *(char *)v13; // 0x1d023ba4
    v19 = v12;
    v16 = v13;
    v14 = v24;
    v21 = v12;
    v18 = v13;
    v15 = v13;
    if (v24 == 48) {
        goto lab_0x1d023bb4;
    } else {
        goto lab_0x1d023bcc;
    }
  lab_0x1d023bb4:
    // 0x1d023bb4
    v2 = 48;
    v20 = v19;
    v17 = v16;
    goto lab_0x1d023bbc;
  lab_0x1d023bcc:;
    int16_t v28 = *(int16_t *)(*(int32_t*)0xa001372c + 2 * (int32_t)v14); // 0x1d023c0c
    int32_t v29 = function_1d027174(-0x62fd8fd4, v28, v21); // 0x1d023c14
    int32_t v30 = v29 + 0x62fd8fd4; // 0x1d023c24
    v2 = v30;
    int32_t v31 = 0; // 0x1d023c24
    int32_t v32 = v15; // 0x1d023c24
    int32_t v33 = 0; // 0x1d023c24
    int32_t v34; // 0x1d023a94
    if (v29 != 0) {
        int32_t v35 = 0;
        int32_t v36 = 0x1000000 * v30 / 0x1000000; // 0x1d023be0
        int32_t v37 = v36 + v35 * v21; // 0x1d023bec
        int32_t v38 = v15 + 1; // 0x1d023bf0
        int32_t v39 = *(int32_t*)0xa001372c; // 0x1d023c04
        int16_t v40 = *(int16_t *)(2 * (int32_t)*(char *)v38 + v39); // 0x1d023c0c
        int32_t v41 = function_1d027174(-0x62fd8fd4, v40, v21); // 0x1d023c14
        int32_t v42 = v41 + 0x62fd8fd4; // 0x1d023c24
        v2 = v42;
        int32_t v43 = v38; // 0x1d023c24
        v31 = v35;
        v34 = v36;
        v32 = v38;
        v33 = v37;
        while (v41 != 0) {
            // 0x1d023be0
            v35 = v37;
            v36 = 0x1000000 * v42 / 0x1000000;
            v37 = v36 + v35 * v21;
            v38 = v43 + 1;
            v39 = *(int32_t*)0xa001372c;
            v40 = *(int16_t *)(2 * (int32_t)*(char *)v38 + v39);
            v41 = function_1d027174(-0x62fd8fd4, v40, v21);
            v42 = v41 + 0x62fd8fd4;
            v2 = v42;
            v43 = v38;
            v31 = v35;
            v34 = v36;
            v32 = v38;
            v33 = v37;
        }
    }
    // 0x1d023c28
    if (v32 == v18) {
        // 0x1d023d40
        if (a2 != 0) {
            // 0x1d023d4c
            *(int32_t *)a2 = a1;
        }
        // 0x1d023b64
        return 0;
    }
    uint32_t v44 = v33;
    char v45 = *(char *)(v21 - 0x62fd8ffc); // 0x1d023c3c
    int32_t v46 = v32 - v15 - (int32_t)v45; // 0x1d023c44
    int32_t result; // 0x1d023a94
    if (v46 < 0) {
        // 0x1d023d08
        result = v11 == 45 ? -v44 : v44;
        goto lab_0x1d023c78;
    } else {
        // 0x1d023c50
        if (v44 < v34 || v46 != 0) {
            goto lab_0x1d023c5c;
        } else {
            // 0x1d023cec
            if (v31 == (v44 - v34) / v21) {
                // 0x1d023d08
                result = v11 == 45 ? -v44 : v44;
                goto lab_0x1d023c78;
            } else {
                goto lab_0x1d023c5c;
            }
        }
    }
  lab_0x1d023bbc:;
    int32_t v25 = v17 + 1;
    char v26 = *(char *)v25; // 0x1d023bc0
    int32_t v27 = v25; // 0x1d023bc4
    v14 = v26;
    v21 = v20;
    v18 = v17;
    v15 = v25;
    while (v26 == 48) {
        // 0x1d023bc0
        v25 = v27 + 1;
        v26 = *(char *)v25;
        v27 = v25;
        v14 = v26;
        v21 = v20;
        v18 = v17;
        v15 = v25;
    }
    goto lab_0x1d023bcc;
  lab_0x1d023c78:
    // 0x1d023c78
    if (a2 != 0) {
        // 0x1d023c84
        *(int32_t *)a2 = v32;
        return result;
    }
    // 0x1d023b64
    return result;
  lab_0x1d023c5c:
    // 0x1d023c5c
    *(int32_t*)0xa0013a3c = 34;
    result = -1;
    if (a4 != 0) {
        // 0x1d023c70
        *(int32_t *)a4 = 1;
        result = -1;
    }
    goto lab_0x1d023c78;
}

// Address range: 0x1d025254 - 0x1d025410
int32_t Stolx(int32_t a1, int32_t a2, int32_t a3, int32_t a4) {
    int32_t v1 = *(int32_t*)0xa0013cac; // 0x1d02527c
    int32_t v2 = a1; // 0x1d0252a4
    int32_t v3 = a1; // 0x1d0252a4
    int32_t v4; // 0x1d025254
    int32_t v5 = 0x1000000 * v4 / 0x1000000; // 0x1d0252a4
    if ((*(int16_t *)(v1 + (2 * v4 & 510)) & 324) != 0) {
        v2++;
        int32_t v6 = (int32_t)*(char *)v2; // 0x1d0252ac
        v3 = v2;
        v5 = v6;
        while ((*(int16_t *)((2 * v6 & 510) + v1) & 324) != 0) {
            // 0x1d0252ac
            v2++;
            v6 = (int32_t)*(char *)v2;
            v3 = v2;
            v5 = v6;
        }
    }
    // 0x1d0252cc
    int32_t v7; // bp-32, 0x1d025254
    int32_t v8 = a2 == 0 ? (int32_t)&v7 : a2; // 0x1d02529c
    int32_t v9; // 0x1d025254
    int32_t v10; // 0x1d025254
    int32_t v11; // 0x1d025254
    int32_t v12; // 0x1d025254
    int32_t v13; // 0x1d025254
    switch (v5) {
        case 45: {
            goto lab_0x1d0253b0;
        }
        case 43: {
            goto lab_0x1d0253b0;
        }
        default: {
            int32_t v14 = Stolx2(v3, v8, a3, a4); // 0x1d0252ec
            int32_t * v15 = (int32_t *)v8; // 0x1d0252f0
            int32_t v16 = *v15; // 0x1d0252f0
            v11 = v14;
            v13 = v16;
            v9 = 43;
            if (v16 == v3) {
                *v15 = a1;
                v12 = v14;
                v10 = 43;
                goto lab_0x1d0253d4;
            } else {
                goto lab_0x1d0252fc;
            }
        }
    }
  lab_0x1d0253b0:;
    int32_t v17 = v3 + 1; // 0x1d0253b0
    int32_t v18 = Stolx2(v17, v8, a3, a4); // 0x1d0253c0
    int32_t * v19 = (int32_t *)v8; // 0x1d0253c4
    int32_t v20 = *v19; // 0x1d0253c4
    v11 = v18;
    v13 = v20;
    v9 = v5;
    if (v20 == v17) {
        // 0x1d0253d0
        *v19 = a1;
        v12 = v18;
        v10 = v5;
        goto lab_0x1d0253d4;
    } else {
        goto lab_0x1d0252fc;
    }
  lab_0x1d0252fc:;
    int32_t result = v11; // 0x1d025300
    int32_t v21 = v9; // 0x1d025300
    v12 = v11;
    v10 = v9;
    if (v13 == a1) {
        goto lab_0x1d0253d4;
    } else {
        goto lab_0x1d025308;
    }
  lab_0x1d0253d4:
    // 0x1d0253d4
    result = 0;
    v21 = v10;
    int32_t v22 = v10; // 0x1d0253d4
    if (v12 == 0) {
        goto lab_0x1d025308;
    } else {
        goto lab_0x1d02534c;
    }
  lab_0x1d025308:
    // 0x1d025308
    switch (v21) {
        case 43: {
            // 0x1d0253e4
            v22 = 43;
            if (result >= 0) {
                // 0x1d025318
                return result;
            }
            // break -> 0x1d02534c
            break;
        }
        case 45: {
            // 0x1d025338
            v22 = 45;
            if (result < 0x80000001) {
                // 0x1d025390
                return -result;
            }
            // break -> 0x1d02534c
            break;
        }
        default: {
            // 0x1d025318
            return result;
        }
    }
    goto lab_0x1d02534c;
  lab_0x1d02534c:
    // 0x1d02534c
    *(int32_t*)0xa0013a3c = 34;
    if (a4 != 0) {
        // 0x1d025358
        *(int32_t *)a4 = 1;
    }
    // 0x1d025318
    return v22 == 45 ? -0x80000000 : 0x7fffffff;
}

// Address range: 0x1d027174 - 0x1d0271bc
int32_t function_1d027174(int32_t result, uint16_t a2, int32_t a3) {
    // 0x1d027174
    if (a3 == 0) {
        // 0x1d0271a8
        return 0;
    }
    int32_t v1 = a2 % 256; // 0x1d027178
    if (result % 256 == v1) {
        // 0x1d0271a8
        return result;
    }
    int32_t v2 = result; // 0x1d02718c
    v2++;
    int32_t result2 = 0; // 0x1d0271a4
    while (v2 != a3 + result) {
        // 0x1d027190
        result2 = v2;
        if (v1 == (int32_t)*(char *)v2) {
            // break -> 0x1d0271a8
            break;
        }
        v2++;
        result2 = 0;
    }
    // 0x1d0271a8
    return result2;
}

// Address range: 0x1d027488 - 0x1d027490
int32_t exit2(void) {
    // 0x1d027488
    int32_t result; // 0x1d027488
    __asm_di(result);
    return result;
}

// --------------------- Meta-Information ---------------------

// Detected functions: 5
