//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int32_t exit(void);
int32_t exit2(void);
int32_t exit3(void);
int32_t function_1d008600(void);
int32_t function_1d008ef8(int32_t * a1);
int32_t function_1d0105f4(int32_t a1);
int32_t function_1d010b3c(int32_t a1);
int32_t function_1d011154(int32_t a1, uint32_t a2);
int32_t function_1d0114e4(int32_t a1, int32_t a2, uint32_t a3, int32_t a4, int32_t a5, uint32_t a6);
int32_t function_1d0134c4(int32_t * a1);
int32_t function_1d01504c(void);
int32_t function_1d015d44(int32_t a1);
int32_t function_1d015dd4(int32_t * a1);
int32_t function_1d016078(int32_t * a1);
int32_t function_1d016388(int32_t * a1);
int32_t function_1d017078(int32_t * a1);
int32_t function_1d0172b8(void);
int32_t function_1d01852c(void);
int32_t function_1d01bfcc(int32_t a1, int32_t a2);
int32_t function_1d01c21c(int32_t a1, int32_t a2);
int32_t function_1d01c248(int32_t a1, int32_t a2);
int32_t pthread_cond_destroy(int32_t * a1);
int32_t pthread_cond_destroy2(int32_t * a1);
int32_t pthread_cond_destroy3(void);
int32_t time(int32_t a1);

// ------------------------ Functions -------------------------

// Address range: 0x1d008600 - 0x1d00869c
int32_t function_1d008600(void) {
    // 0x1d008600
    if (*(int32_t*)0xa0013290 < 101) {
        // 0x1d008694
        return 8;
    }
    int32_t v1 = 938; // bp-24, 0x1d008624
    if (*(int32_t*)0xa0013310 < 3) {
        // 0x1d008660
        __asm_ins(2, 4, 4);
    } else {
        // 0x1d00863c
        __asm_ins(15, 4, 4);
    }
    // 0x1d008674
    __asm_ins(1, 15, 1);
    // 0x1d008694
    return pthread_cond_destroy2(&v1);
}

// Address range: 0x1d008ef8 - 0x1d0091a8
int32_t function_1d008ef8(int32_t * a1) {
    int32_t v1 = (int32_t)a1;
    *(char *)a1 = 0;
    *(char *)(v1 + 1) = 0;
    int32_t v2 = v1 + 2; // 0x1d008f0c
    *(char *)v2 = 0;
    *(char *)(v1 + 3) = 0;
    int32_t v3 = v1 + 4; // 0x1d008f14
    *(char *)v3 = 0;
    *(char *)(v1 + 5) = 0;
    char * v4 = (char *)(v1 + 6); // 0x1d008f1c
    *v4 = 0;
    char * v5 = (char *)(v1 + 7); // 0x1d008f20
    *v5 = 0;
    *(int16_t *)a1 = (int16_t)*(int32_t*)0xa00135d4;
    int32_t v6 = *(int32_t*)0xa00135d0; // 0x1d008f34
    *(int16_t *)v2 = (int16_t)((int32_t)(0x51eb851f * (int64_t)v6 / 0x2000000000) - (v6 >> 31));
    int32_t v7; // 0x1d008ef8
    int32_t v8; // 0x1d008ef8
    if (*(int32_t*)0xa00131b8 < 4) {
        // 0x1d009048
        v8 = 0;
        goto lab_0x1d009050;
    } else {
        int32_t v9 = *(int32_t*)0xa00131d8; // 0x1d008f70
        v7 = v9;
        if (v9 >= 4) {
            // 0x1d009118
            v7 = v9;
            if (*(int32_t*)0xa0013104 >= 4) {
                // 0x1d008f88
                v7 = v9;
                if (*(int32_t*)0xa00130b4 >= 4) {
                    unsigned char v10 = *(char*)0xa00130ae; // 0x1d009134
                    unsigned char v11 = *(char*)0xa00130af; // 0x1d00913c
                    *(int16_t *)v3 = 256 * (int16_t)v10 | (int16_t)v11;
                    *v4 = *(char*)0xa00131ac ^ -128;
                    v8 = 0;
                    if (*(int32_t*)0xa00131b8 >= 4) {
                        // 0x1d009130
                        v7 = *(int32_t*)0xa00131d8;
                        goto lab_0x1d008f9c;
                    } else {
                        goto lab_0x1d009050;
                    }
                } else {
                    goto lab_0x1d008f9c;
                }
            } else {
                goto lab_0x1d008f9c;
            }
        } else {
            goto lab_0x1d008f9c;
        }
    }
  lab_0x1d009050:
    // 0x1d009050
    __asm_ins(v8, 0, 1);
    *v5 = (char)__asm_ins((int32_t)*(char*)0xa001356e, 1, 1);
    *v5 = (char)__asm_ins(function_1d01852c(), 2, 1);
    *v5 = (char)__asm_ins((int32_t)(exit() != 0), 3, 1);
    int32_t v12 = 1; // 0x1d009098
    if (*(int32_t*)0xa0013104 >= 4) {
        // 0x1d00909c
        v12 = *(int32_t*)0xa00130b4 < 4;
    }
    // 0x1d0090ac
    *v5 = (char)__asm_ins(v12, 4, 1);
    int32_t v13 = 1; // 0x1d0090cc
    if (*(int32_t*)0xa00131b8 >= 4) {
        // 0x1d0090d0
        v13 = *(int32_t*)0xa00131d8 < 4;
    }
    // 0x1d0090e0
    *v5 = (char)__asm_ins(v13, 5, 1);
    *v5 = (char)__asm_ins((int32_t)*(char*)0xa001356f, 6, 1);
    int32_t result = __asm_ins((int32_t)(*(int32_t*)0xa0013228 == 0), 7, 1); // 0x1d00910c
    *v5 = (char)result;
    return result;
  lab_0x1d008f9c:
    // 0x1d008f9c
    v8 = 0;
    if (v7 >= 4) {
        // 0x1d00916c
        v8 = 0;
        if (*(int32_t*)0xa0013104 >= 4) {
            // 0x1d008fb4
            v8 = 0;
            if (*(int32_t*)0xa00130b4 >= 4) {
                // 0x1d009184
                v8 = 0;
                if (*(int32_t*)0xa0013228 == 0) {
                    goto lab_0x1d009050;
                } else {
                    // 0x1d008fcc
                    v8 = 0;
                    if (__asm_ext(*(int32_t*)0xa0013220, 16, 1) == 0) {
                        goto lab_0x1d009050;
                    } else {
                        // 0x1d008fdc
                        v8 = 0;
                        if (*(char*)0xa001356e == 0) {
                            // 0x1d008fec
                            v8 = 0;
                            if (*(char*)0xa001356f == 0) {
                                // 0x1d008ffc
                                if (exit() == 0) {
                                    goto lab_0x1d00901c;
                                } else {
                                    // 0x1d00900c
                                    v8 = 0;
                                    if (function_1d0172b8() == 0) {
                                        goto lab_0x1d009050;
                                    } else {
                                        goto lab_0x1d00901c;
                                    }
                                }
                            } else {
                                goto lab_0x1d009050;
                            }
                        } else {
                            goto lab_0x1d009050;
                        }
                    }
                }
            } else {
                goto lab_0x1d009050;
            }
        } else {
            goto lab_0x1d009050;
        }
    } else {
        goto lab_0x1d009050;
    }
  lab_0x1d00901c:
    // 0x1d00901c
    v8 = 0;
    if (function_1d01852c() == 0) {
        // 0x1d00902c
        v8 = 1;
        if ((*(int32_t*)0xa00131ac & 0xc00000) == 0x800000) {
            goto lab_0x1d009050;
        } else {
            // 0x1d009048
            v8 = 0;
            goto lab_0x1d009050;
        }
    } else {
        goto lab_0x1d009050;
    }
}

// Address range: 0x1d0091a8 - 0x1d0092dc
int32_t time(int32_t a1) {
    // 0x1d0091a8
    int32_t v1; // bp-16, 0x1d0091a8
    int32_t v2; // bp-24, 0x1d0091a8
    if (*(char*)0xa001356d == 0) {
        // 0x1d00923c
        if (a1 != 0) {
            // 0x1d0092d4
            return -0x5fff0000;
        }
    } else {
        int32_t v3 = 0; // 0x1d0091c8
        if (*(int32_t*)0xa0013100 != 0) {
            // 0x1d0091cc
            v3 = __asm_ins(0, 23, 1);
        }
        // 0x1d0091f0
        v1 = v3;
        v2 = 936;
        if (a1 != 0) {
            // 0x1d009204
            *(int32_t*)0xbf8860e8 = 32;
            // 0x1d0092d4
            return function_1d015dd4(&v2);
        }
        // 0x1d009220
        pthread_cond_destroy(&v2);
        *(int32_t*)0xbf8860e4 = 32;
    }
    // 0x1d009244
    if (*(int32_t*)0xa0013568 == 0) {
        // 0x1d009250
        v2 = 101;
        function_1d008ef8(&v1);
        function_1d017078(&v1);
        function_1d0134c4(&v2);
    }
    // 0x1d00927c
    if (*(int32_t*)0xa00131f8 != 0) {
        // 0x1d009288
        if (__asm_ext(*(int32_t*)0xa00131f4, 24, 1) != 0) {
            // 0x1d0092d4
            return function_1d008600();
        }
    }
    // 0x1d00929c
    if (*(int32_t*)0xa0013218 != 0) {
        // 0x1d0092a8
        if (__asm_ext(*(int32_t*)0xa0013214, 24, 1) != 0) {
            // 0x1d0092d4
            return function_1d008600();
        }
    }
    // 0x1d0092bc
    if (*(char*)0xa001356d == 0) {
        // 0x1d0092d4
        return 0;
    }
    // 0x1d0092d4
    return function_1d008600();
}

// Address range: 0x1d00e890 - 0x1d00eab8
int32_t exit2(void) {
    // 0x1d00e890
    *(int32_t*)0xbf881074 = 0x2000000;
    *(int32_t*)0xbf885220 = 255;
    *(int32_t*)0xbf885200 = 255;
    *(int32_t*)0xbf885300 = 0;
    *(int32_t*)0xbf885310 = 0;
    *(int32_t*)0xbf885320 = 0;
    *(int32_t*)0xbf885330 = 0;
    *(int32_t*)0xbf8852e0 = 0;
    *(int32_t*)0xbf885230 = 159;
    *(int32_t*)0xbf885210 = 159;
    *(int32_t*)0xbf885070 = *(int32_t*)0xbf885070 % 16;
    *(char*)0xbf885080 = (char)__asm_ins(1, 0, 1);
    uint32_t v1 = __asm_ext(-0x5ffffc00, 0, 29); // 0x1d00e91c
    *(int32_t*)0xbf8852d0 = v1 / 0x1000000;
    *(int32_t*)0xbf8852c0 = v1 / 0x10000;
    *(int32_t*)0xbf885270 = v1 / 256;
    int32_t v2 = 0; // 0x1d00e954
    int32_t v3 = 0; // 0x1d00e954
    *(int32_t *)(v2 - 0x5ffffc00) = 0;
    *(int32_t *)(v2 - 0x5ffffbfc) = 0;
    v3++;
    v2 = 8 * v3;
    while (v3 != 16) {
        // 0x1d00e958
        *(int32_t *)(v2 - 0x5ffffc00) = 0;
        *(int32_t *)(v2 - 0x5ffffbfc) = 0;
        v3++;
        v2 = 8 * v3;
    }
    // 0x1d00e978
    *(char*)0xbf885250 = (char)__asm_ins(1, 1, 1);
    *(int32_t*)0xbf885260 = 0;
    *(char*)0xbf885250 = (char)__asm_ins(0, 5, 1);
    *(char*)0xbf885250 = (char)__asm_ins(0, 1, 1);
    if ((*(int32_t*)0xbf885200 & 8) != 0) {
        *(int32_t*)0xbf885200 = 8;
        *(char*)0xa0000484 = 0;
        *(char*)0xa00004d4 = 0;
        *(int32_t*)0xa00004d4 = __asm_ins(0, 8, 16);
        while ((*(int32_t*)0xbf885200 & 8) != 0) {
            // 0x1d00e9d0
            *(int32_t*)0xbf885200 = 8;
            *(char*)0xa0000484 = 0;
            *(char*)0xa00004d4 = 0;
            *(int32_t*)0xa00004d4 = __asm_ins(0, 8, 16);
        }
    }
    // 0x1d00ea00
    int32_t v4; // 0x1d00e890
    *(int32_t *)(v4 - 0x7f2c) = 1;
    *(int32_t *)(v4 - 0x7f24) = 1;
    *(int32_t *)(v4 - 0x7ef4) = 0;
    *(int32_t *)(v4 - 0x7ef0) = 0;
    *(int32_t *)(v4 - 0x7f10) = 0;
    int32_t v5 = -0x5ffffe00; // 0x1d00ea34
    int32_t v6 = -0x5ffffdf0; // 0x1d00ea34
    int32_t v7 = 0; // 0x1d00ea34
    *(int32_t *)v6 = 0;
    *(int32_t *)v5 = 0;
    int32_t v8 = v7 + v4;
    *(char *)(v8 - 0x7edc) = 0;
    *(char *)(v8 - 0x7f0c) = 0;
    v7++;
    v5 += 4;
    v6 += 4;
    while (v7 != 4) {
        // 0x1d00ea38
        *(int32_t *)v6 = 0;
        *(int32_t *)v5 = 0;
        v8 = v7 + v4;
        *(char *)(v8 - 0x7edc) = 0;
        *(char *)(v8 - 0x7f0c) = 0;
        v7++;
        v5 += 4;
        v6 += 4;
    }
    // 0x1d00ea60
    *(int32_t*)0xa0000210 = -0x5ffffbf0;
    *(int32_t*)0xbf885300 = 13;
    *(int32_t*)0xa0000404 = __asm_ext(v4 - 0x7f18, 0, 29);
    *(int16_t *)-0x5ffffbfe = (int16_t)__asm_ins(64, 0, 10);
    *(int16_t *)-0x5ffffc00 = 132;
    *(char *)(v4 - 0x7f28) = 0;
    *(int32_t *)(v4 - 0x7eec) = 0;
    return 132;
}

// Address range: 0x1d0105f4 - 0x1d010604
int32_t function_1d0105f4(int32_t a1) {
    // 0x1d0105f4
    int32_t v1; // 0x1d0105f4
    return (int32_t)*(char *)(a1 - 0x7f44 + v1);
}

// Address range: 0x1d010b3c - 0x1d010d70
int32_t function_1d010b3c(int32_t a1) {
    switch (a1) {
        case 3: {
            // 0x1d010b74
            *(int32_t*)0xbf8860e4 = 512;
            *(int32_t*)0xbf8860c4 = 512;
            *(int32_t*)0xbf805820 = 160;
            while ((*(int32_t*)0xbf805810 & 0x1f000000) == 0) {
                // continue -> 0x1d010c08
            }
            // 0x1d010c9c
            *(int32_t*)0xbf805820 = 0;
            while ((*(int32_t*)0xbf805810 & 0x1f000000) == 0) {
                // continue -> 0x1d010ca8
            }
            // 0x1d010cb8
            *(int32_t*)0xbf8860e8 = 512;
            *(int32_t*)0xbf8860c4 = 512;
            return 0;
        }
        case 4: {
            // 0x1d010b90
            *(int32_t*)0xbf886064 = 256;
            *(int32_t*)0xbf886044 = 256;
            *(int32_t*)0xbf805c20 = 160;
            while ((*(int32_t*)0xbf805c10 & 0x1f000000) == 0) {
                // continue -> 0x1d010c38
            }
            // 0x1d010cc8
            *(int32_t*)0xbf805c20 = 0;
            while ((*(int32_t*)0xbf805c10 & 0x1f000000) == 0) {
                // continue -> 0x1d010cd4
            }
            // 0x1d010ce4
            *(int32_t*)0xbf886068 = 256;
            *(int32_t*)0xbf886044 = 256;
            return 0;
        }
        case 2: {
            // 0x1d010b58
            *(int32_t*)0xbf8861a4 = 512;
            *(int32_t*)0xbf886184 = 512;
            *(int32_t*)0xbf805a20 = 160;
            while ((*(int32_t*)0xbf805a10 & 0x1f000000) == 0) {
                // continue -> 0x1d010bd8
            }
            // 0x1d010c70
            *(int32_t*)0xbf805a20 = 0;
            while ((*(int32_t*)0xbf805a10 & 0x1f000000) == 0) {
                // continue -> 0x1d010c7c
            }
            // 0x1d010c8c
            *(int32_t*)0xbf8861a8 = 512;
            *(int32_t*)0xbf886184 = 512;
            return 0;
        }
    }
    // 0x1d010d68
    return 0;
}

// Address range: 0x1d011154 - 0x1d01130c
int32_t function_1d011154(int32_t a1, uint32_t a2) {
    switch (a1) {
        case 3: {
            // 0x1d0111a4
            *(int32_t*)0xbf8860e4 = 512;
            *(int32_t*)0xbf8860c4 = 512;
            *(int32_t*)0xbf805820 = (1 << a2 % 4) % 128 | 128;
            while ((*(int32_t*)0xbf805810 & 0x1f000000) == 0) {
                // continue -> 0x1d01125c
            }
            // 0x1d0112d8
            *(int32_t*)0xbf8860e8 = 512;
            *(int32_t*)0xbf8860c4 = 512;
            return 512;
        }
        case 4: {
            // 0x1d0111cc
            *(int32_t*)0xbf886064 = 256;
            *(int32_t*)0xbf886044 = 256;
            *(int32_t*)0xbf805c20 = (1 << a2 % 4) % 128 | 128;
            while ((*(int32_t*)0xbf805c10 & 0x1f000000) == 0) {
                // continue -> 0x1d011288
            }
            // 0x1d0112f4
            *(int32_t*)0xbf886068 = 256;
            *(int32_t*)0xbf886044 = 256;
            return 256;
        }
        case 2: {
            // 0x1d011178
            *(int32_t*)0xbf8861a4 = 512;
            *(int32_t*)0xbf886184 = 512;
            *(int32_t*)0xbf805a20 = (1 << a2 % 4) % 128 | 128;
            while ((*(int32_t*)0xbf805a10 & 0x1f000000) == 0) {
                // continue -> 0x1d011230
            }
            // 0x1d0112bc
            *(int32_t*)0xbf8861a8 = 512;
            *(int32_t*)0xbf886184 = 512;
            // 0x1d0112cc
            return 512;
        }
    }
    // 0x1d0112cc
    return 512;
}

// Address range: 0x1d0114e4 - 0x1d0117c0
int32_t function_1d0114e4(int32_t a1, int32_t a2, uint32_t a3, int32_t a4, int32_t a5, uint32_t a6) {
    switch (a1) {
        case 3: {
            // 0x1d01153c
            *(int32_t*)0xbf8860e4 = 512;
            *(int32_t*)0xbf8860c4 = 512;
            // break -> 0x1d011570
            break;
        }
        case 4: {
            // 0x1d011558
            *(int32_t*)0xbf886064 = 256;
            *(int32_t*)0xbf886044 = 256;
            // break -> 0x1d011570
            break;
        }
        case 2: {
            // 0x1d011520
            *(int32_t*)0xbf8861a4 = 512;
            *(int32_t*)0xbf886184 = 512;
            // break -> 0x1d011570
            break;
        }
    }
    char v1; // bp-7, 0x1d0114e4
    if (a4 == 0) {
        // 0x1d0115b0
        v1 = a3 / 8;
    } else {
        // 0x1d011580
        v1 = a3 / 0x200000;
        __asm_ins(0, 0, 5);
        __asm_ext(a3, 16, 2);
    }
    int32_t * v2 = (int32_t*)0xbf805a20; // 0x1d0114e4
    int32_t * v3 = (int32_t*)0xbf805a10; // 0x1d0114e4
    int32_t result = 2; // 0x1d0114e4
    switch (a1) {
        case 3: {
            // 0x1d011610
            v2 = (int32_t*)0xbf805820;
            v3 = (int32_t*)0xbf805810;
            goto lab_0x1d011620;
        }
        case 4: {
            // 0x1d0115fc
            v2 = (int32_t*)0xbf805c20;
            v3 = (int32_t*)0xbf805c10;
            goto lab_0x1d011620;
        }
        case 2: {
            goto lab_0x1d011620;
        }
        default: {
            return result;
        }
    }
  lab_0x1d011620:;
    uint32_t v4 = a6 % 256; // 0x1d0114e8
    int32_t v5 = v4 < 8 ? v4 : 8;
    int32_t v6 = &v1;
    *v2 = (int32_t)*(char *)(v6 - 1);
    int32_t v7 = v6 + 1; // 0x1d011634
    int32_t v8; // bp-2, 0x1d0114e4
    while (v6 != (int32_t)&v8) {
        // 0x1d01162c
        v6 = v7;
        *v2 = (int32_t)*(char *)(v6 - 1);
        v7 = v6 + 1;
    }
    // 0x1d011644
    while ((*v3 & 0x1e000000) < 0x6000000) {
        // continue -> 0x1d011644
    }
    int32_t * v9 = (int32_t*)0xbf805a20; // 0x1d0114e4
    int32_t * v10 = (int32_t*)0xbf805a10; // 0x1d0114e4
    result = 2;
    switch (a1) {
        case 3: {
            // 0x1d0116b8
            v9 = (int32_t*)0xbf805820;
            v10 = (int32_t*)0xbf805810;
            goto lab_0x1d0116c8;
        }
        case 4: {
            // 0x1d0116a4
            v9 = (int32_t*)0xbf805c20;
            v10 = (int32_t*)0xbf805c10;
            goto lab_0x1d0116c8;
        }
        case 2: {
            goto lab_0x1d0116c8;
        }
        default: {
            return result;
        }
    }
  lab_0x1d0116c8:
    // 0x1d0116c8
    if (a5 == 0) {
        if (v5 != 0) {
            // 0x1d011704
            *v9 = 0;
        }
    } else {
        // 0x1d0116e0
        if (v5 != 0) {
            int32_t v11 = a5 + 1;
            *v9 = (int32_t)*(char *)a5;
            int32_t v12 = v11; // 0x1d0116f8
            while (v11 != v5 + a5) {
                // 0x1d0116ec
                v11 = v12 + 1;
                *v9 = (int32_t)*(char *)v12;
                v12 = v11;
            }
        }
    }
    // 0x1d011718
    while ((*v10 & 0x1f000000) < 0x1000000 * v5) {
        // continue -> 0x1d01171c
    }
    // 0x1d011750
    result = 2;
    switch (a1) {
        case 3: {
            // 0x1d011784
            *(int32_t*)0xbf8860e8 = 512;
            *(int32_t*)0xbf8860c4 = 512;
            result = 512;
            // break -> 0x1d0117b8
            break;
        }
        case 4: {
            // 0x1d0117a0
            *(int32_t*)0xbf886068 = 256;
            *(int32_t*)0xbf886044 = 256;
            result = 256;
            // break -> 0x1d0117b8
            break;
        }
        case 2: {
            // 0x1d011768
            *(int32_t*)0xbf8861a8 = 512;
            *(int32_t*)0xbf886184 = 512;
            result = 512;
            // break -> 0x1d0117b8
            break;
        }
    }
    // 0x1d0117b8
    return result;
}

// Address range: 0x1d0134c4 - 0x1d013754
int32_t function_1d0134c4(int32_t * a1) {
    int32_t v1 = (int32_t)a1;
    int32_t v2; // 0x1d0134c4
    if ((*(int32_t *)(v2 - 0x7f3c) & 32) != 0) {
        int32_t v3 = *(int32_t*)0xa0000cf8; // 0x1d0134ec
        uint32_t v4 = *(int32_t*)0xa0000cf4; // 0x1d0134f4
        uint32_t v5 = v4 % 0x1000; // 0x1d0134f8
        if (v5 != (v3 + 1) % 0x1000) {
            int32_t * v6 = (int32_t *)(v1 + 4); // 0x1d01351c
            uint32_t v7 = *v6; // 0x1d01351c
            int32_t v8 = __asm_ext(v7, 28, 1); // 0x1d013520
            int32_t v9; // 0x1d0134c4
            if (v8 == 0) {
                // 0x1d013548
                v9 = v4 % 2048;
            } else {
                // 0x1d01352c
                v9 = __asm_ext(*v6, 10, 18) | 0x40000 * v5 & 0x1ffc0000;
            }
            int32_t v10 = 16 * v3 & 0xfff0; // 0x1d013508
            uint32_t v11 = v7 % 16; // 0x1d013528
            __asm_ins(v9, 0, 29);
            __asm_ins(v8, 29, 1);
            __asm_ins(v11, 30, 2);
            *(int32_t *)(v10 - 0x5ffff300) = __asm_ins(v11 / 4, 30, 2);
            __asm_ins(5, 27, 3);
            *(int32_t *)(v10 - 0x5ffff304) = __asm_ins(*(int32_t *)(v2 - 0x7f38), 0, 27);
            __asm_lwl(*(int32_t *)(v1 + 11));
            int32_t v12 = __asm_lwr(*(int32_t *)(v1 + 8)); // 0x1d01358c
            __asm_lwl(*(int32_t *)(v1 + 15));
            int32_t v13 = __asm_lwr(*(int32_t *)(v1 + 12)); // 0x1d013594
            *(int32_t *)(v10 - 0x5ffff2fc) = v12;
            *(int32_t *)(v10 - 0x5ffff2f8) = v13;
            uint32_t v14 = (*(int32_t*)0xa0000cf8 + 1) % 0x1000; // 0x1d0135b0
            if (*(int32_t*)0xa0000cf4 % 0x1000 != v14) {
                // 0x1d0135c4
                *(int32_t*)0xa0000cf8 = v14;
            }
        }
    }
    int32_t v15 = *(int32_t*)0xa00008e8 % 64; // 0x1d013668
    int32_t result2; // 0x1d0134c4
    if (v15 == *(int32_t*)0xa00008ec % 64) {
      lab_0x1d013730:;
        int32_t result = function_1d016078(a1); // 0x1d013734
        if (result != 0) {
            // 0x1d013740
            return result;
        }
        int32_t v16 = *(int32_t*)0xa00008ec; // 0x1d0136c4
        uint32_t v17 = (v16 + 1) % 64; // 0x1d0136d0
        if (*(int32_t*)0xa00008e8 % 64 == v17) {
            // 0x1d01371c
            *(int32_t*)0xa00008f0 = *(int32_t*)0xa00008f0 + 1;
            result2 = 0;
        } else {
            int32_t v18 = 16 * v16 & 1008; // 0x1d0136e4
            *(int32_t *)(v18 - 0x5ffff70c) = v17;
            *(int32_t *)(v18 - 0x5ffff708) = *(int32_t *)(v1 + 4);
            *(int32_t *)(v18 - 0x5ffff704) = *(int32_t *)(v1 + 8);
            *(int32_t *)(v18 - 0x5ffff700) = *(int32_t *)(v1 + 12);
            *(int32_t*)0xa00008ec = v17;
            result2 = 1;
        }
        // 0x1d013740
        return result2;
    }
    int32_t v19 = *(int32_t *)(16 * v15 - 0x5ffff70c); // bp-32, 0x1d013698
    while (function_1d016078(&v19) != 0) {
        int32_t v20 = *(int32_t*)0xa00008e8; // 0x1d0136b4
        int32_t v21 = *(int32_t*)0xa00008ec; // 0x1d0135d8
        int32_t v22 = v21; // 0x1d0135e4
        int32_t v23 = v20; // 0x1d0135e4
        if ((v21 ^ v20) % 64 != 0) {
            // 0x1d0135e8
            v23 = (v20 + 1) % 64;
            *(int32_t*)0xa00008e8 = v23;
            v22 = *(int32_t*)0xa00008ec;
        }
        int32_t v24 = v23 % 64; // 0x1d013668
        if (v24 == v22 % 64) {
            goto lab_0x1d013730;
        }
        v19 = *(int32_t *)(16 * v24 - 0x5ffff70c);
    }
    int32_t v25 = *(int32_t*)0xa00008ec; // 0x1d0135f8
    uint32_t v26 = (v25 + 1) % 64; // 0x1d013604
    if (*(int32_t*)0xa00008e8 % 64 == v26) {
        // 0x1d013650
        *(int32_t*)0xa00008f0 = *(int32_t*)0xa00008f0 + 1;
        result2 = 0;
    } else {
        int32_t v27 = 16 * v25 & 1008; // 0x1d013618
        *(int32_t *)(v27 - 0x5ffff70c) = v26;
        *(int32_t *)(v27 - 0x5ffff708) = *(int32_t *)(v1 + 4);
        *(int32_t *)(v27 - 0x5ffff704) = *(int32_t *)(v1 + 8);
        *(int32_t *)(v27 - 0x5ffff700) = *(int32_t *)(v1 + 12);
        *(int32_t*)0xa00008ec = v26;
        result2 = 1;
    }
    // 0x1d013740
    return result2;
}

// Address range: 0x1d013754 - 0x1d0139e4
int32_t pthread_cond_destroy2(int32_t * a1) {
    int32_t v1 = (int32_t)a1;
    int32_t v2; // 0x1d013754
    if ((*(int32_t *)(v2 - 0x7f3c) & 128) != 0) {
        int32_t v3 = *(int32_t*)0xa0000cf8; // 0x1d01377c
        uint32_t v4 = *(int32_t*)0xa0000cf4; // 0x1d013784
        uint32_t v5 = v4 % 0x1000; // 0x1d013788
        if (v5 != (v3 + 1) % 0x1000) {
            int32_t * v6 = (int32_t *)(v1 + 4); // 0x1d0137ac
            uint32_t v7 = *v6; // 0x1d0137ac
            int32_t v8 = __asm_ext(v7, 28, 1); // 0x1d0137b0
            int32_t v9; // 0x1d013754
            if (v8 == 0) {
                // 0x1d0137d8
                v9 = v4 % 2048;
            } else {
                // 0x1d0137bc
                v9 = __asm_ext(*v6, 10, 18) | 0x40000 * v5 & 0x1ffc0000;
            }
            int32_t v10 = 16 * v3 & 0xfff0; // 0x1d013798
            uint32_t v11 = v7 % 16; // 0x1d0137b8
            __asm_ins(v9, 0, 29);
            __asm_ins(v8, 29, 1);
            __asm_ins(v11, 30, 2);
            *(int32_t *)(v10 - 0x5ffff300) = __asm_ins(v11 / 4, 30, 2);
            __asm_ins(7, 27, 3);
            *(int32_t *)(v10 - 0x5ffff304) = __asm_ins(*(int32_t *)(v2 - 0x7f38), 0, 27);
            __asm_lwl(*(int32_t *)(v1 + 11));
            int32_t v12 = __asm_lwr(*(int32_t *)(v1 + 8)); // 0x1d01381c
            __asm_lwl(*(int32_t *)(v1 + 15));
            int32_t v13 = __asm_lwr(*(int32_t *)(v1 + 12)); // 0x1d013824
            *(int32_t *)(v10 - 0x5ffff2fc) = v12;
            *(int32_t *)(v10 - 0x5ffff2f8) = v13;
            uint32_t v14 = (*(int32_t*)0xa0000cf8 + 1) % 0x1000; // 0x1d013840
            if (*(int32_t*)0xa0000cf4 % 0x1000 != v14) {
                // 0x1d013854
                *(int32_t*)0xa0000cf8 = v14;
            }
        }
    }
    int32_t v15 = *(int32_t*)0xa00004dc % 64; // 0x1d0138f8
    int32_t result2; // 0x1d013754
    if (v15 == *(int32_t*)0xa00004e0 % 64) {
      lab_0x1d0139c0:;
        int32_t result = function_1d016388(a1); // 0x1d0139c4
        if (result != 0) {
            // 0x1d0139d0
            return result;
        }
        int32_t v16 = *(int32_t*)0xa00004e0; // 0x1d013954
        uint32_t v17 = (v16 + 1) % 64; // 0x1d013960
        if (*(int32_t*)0xa00004dc % 64 == v17) {
            // 0x1d0139ac
            *(int32_t*)0xa00004e4 = *(int32_t*)0xa00004e4 + 1;
            result2 = 0;
        } else {
            int32_t v18 = 16 * v16 & 1008; // 0x1d013974
            *(int32_t *)(v18 - 0x5ffffb18) = v17;
            *(int32_t *)(v18 - 0x5ffffb14) = *(int32_t *)(v1 + 4);
            *(int32_t *)(v18 - 0x5ffffb10) = *(int32_t *)(v1 + 8);
            *(int32_t *)(v18 - 0x5ffffb0c) = *(int32_t *)(v1 + 12);
            *(int32_t*)0xa00004e0 = v17;
            result2 = 1;
        }
        // 0x1d0139d0
        return result2;
    }
    int32_t v19 = *(int32_t *)(16 * v15 - 0x5ffffb18); // bp-32, 0x1d013928
    while (function_1d016388(&v19) != 0) {
        int32_t v20 = *(int32_t*)0xa00004dc; // 0x1d013944
        int32_t v21 = *(int32_t*)0xa00004e0; // 0x1d013868
        int32_t v22 = v21; // 0x1d013874
        int32_t v23 = v20; // 0x1d013874
        if ((v21 ^ v20) % 64 != 0) {
            // 0x1d013878
            v23 = (v20 + 1) % 64;
            *(int32_t*)0xa00004dc = v23;
            v22 = *(int32_t*)0xa00004e0;
        }
        int32_t v24 = v23 % 64; // 0x1d0138f8
        if (v24 == v22 % 64) {
            goto lab_0x1d0139c0;
        }
        v19 = *(int32_t *)(16 * v24 - 0x5ffffb18);
    }
    int32_t v25 = *(int32_t*)0xa00004e0; // 0x1d013888
    uint32_t v26 = (v25 + 1) % 64; // 0x1d013894
    if (*(int32_t*)0xa00004dc % 64 == v26) {
        // 0x1d0138e0
        *(int32_t*)0xa00004e4 = *(int32_t*)0xa00004e4 + 1;
        result2 = 0;
    } else {
        int32_t v27 = 16 * v25 & 1008; // 0x1d0138a8
        *(int32_t *)(v27 - 0x5ffffb18) = v26;
        *(int32_t *)(v27 - 0x5ffffb14) = *(int32_t *)(v1 + 4);
        *(int32_t *)(v27 - 0x5ffffb10) = *(int32_t *)(v1 + 8);
        *(int32_t *)(v27 - 0x5ffffb0c) = *(int32_t *)(v1 + 12);
        *(int32_t*)0xa00004e0 = v26;
        result2 = 1;
    }
    // 0x1d0139d0
    return result2;
}

// Address range: 0x1d013af0 - 0x1d013bfc
int32_t pthread_cond_destroy(int32_t * a1) {
    uint32_t v1 = (int32_t)a1;
    int32_t v2; // 0x1d013af0
    if ((*(int32_t *)(v2 - 0x7f3c) & 8) == 0) {
        // 0x1d013be8
        return function_1d015d44(v1);
    }
    int32_t v3 = *(int32_t*)0xa0000cf8; // 0x1d013b0c
    if ((*(int32_t*)0xa0000cf4 ^ v3 + 1) % 0x1000 == 0) {
        // 0x1d013be8
        return function_1d015d44(v1);
    }
    int32_t * v4 = (int32_t *)(v1 + 4); // 0x1d013b3c
    uint32_t v5 = *v4; // 0x1d013b3c
    int32_t v6 = __asm_ext(v5, 28, 1); // 0x1d013b40
    int32_t v7; // 0x1d013af0
    if (v6 == 0) {
        // 0x1d013b68
        v7 = v1 % 2048;
    } else {
        // 0x1d013b4c
        v7 = __asm_ext(*v4, 10, 18) | 0x40000 * v1 & 0x1ffc0000;
    }
    int32_t v8 = 16 * v3 & 0xfff0; // 0x1d013b28
    uint32_t v9 = v5 % 16; // 0x1d013b48
    __asm_ins(v7, 0, 29);
    __asm_ins(v6, 29, 1);
    __asm_ins(v9, 30, 2);
    *(int32_t *)(v8 - 0x5ffff300) = __asm_ins(v9 / 4, 30, 2);
    __asm_ins(3, 27, 3);
    *(int32_t *)(v8 - 0x5ffff304) = __asm_ins(*(int32_t *)(v2 - 0x7f38), 0, 27);
    __asm_lwl(*(int32_t *)(v1 + 11));
    int32_t v10 = __asm_lwr(*(int32_t *)(v1 + 8)); // 0x1d013bac
    __asm_lwl(*(int32_t *)(v1 + 15));
    int32_t v11 = __asm_lwr(*(int32_t *)(v1 + 12)); // 0x1d013bb4
    *(int32_t *)(v8 - 0x5ffff2fc) = v10;
    *(int32_t *)(v8 - 0x5ffff2f8) = v11;
    uint32_t v12 = (*(int32_t*)0xa0000cf8 + 1) % 0x1000; // 0x1d013bd0
    if (*(int32_t*)0xa0000cf4 % 0x1000 != v12) {
        // 0x1d013be4
        *(int32_t*)0xa0000cf8 = v12;
    }
    // 0x1d013be8
    return function_1d015d44(v1);
}

// Address range: 0x1d01504c - 0x1d015060
int32_t function_1d01504c(void) {
    // 0x1d01504c
    return (int32_t)*(char*)0xa00001bc;
}

// Address range: 0x1d015d44 - 0x1d015dd4
int32_t function_1d015d44(int32_t a1) {
    int32_t v1 = function_1d01bfcc(1, 1); // 0x1d015d5c
    int32_t result = 0; // 0x1d015d60
    if (v1 != 0) {
        // 0x1d015d68
        __asm_lwl(*(int32_t *)(a1 + 3));
        int32_t v2 = __asm_lwr(1); // 0x1d015d6c
        __asm_lwl(*(int32_t *)(a1 + 7));
        int32_t v3 = __asm_lwr(*(int32_t *)(a1 + 4)); // 0x1d015d74
        __asm_lwl(*(int32_t *)(a1 + 11));
        int32_t v4 = __asm_lwr(*(int32_t *)(a1 + 8)); // 0x1d015d7c
        __asm_lwl(*(int32_t *)(a1 + 15));
        int32_t v5 = __asm_lwr(*(int32_t *)(a1 + 12)); // 0x1d015d84
        __asm_swl(v2, *(int32_t *)(v1 + 3));
        __asm_swr(v2, *(int32_t *)v1);
        __asm_swl(v3, *(int32_t *)(v1 + 7));
        __asm_swr(v3, *(int32_t *)(v1 + 4));
        __asm_swl(v4, *(int32_t *)(v1 + 11));
        __asm_swr(v4, *(int32_t *)(v1 + 8));
        __asm_swl(v5, *(int32_t *)(v1 + 15));
        __asm_swr(v5, *(int32_t *)(v1 + 12));
        function_1d01c21c(1, 1);
        function_1d01c248(1, 1);
        result = 1;
    }
    // 0x1d015dc4
    return result;
}

// Address range: 0x1d015dd4 - 0x1d015e64
int32_t function_1d015dd4(int32_t * a1) {
    int32_t v1 = function_1d01bfcc(1, 2); // 0x1d015dec
    int32_t result = 0; // 0x1d015df0
    if (v1 != 0) {
        int32_t v2 = (int32_t)a1;
        __asm_lwl(*(int32_t *)(v2 + 3));
        int32_t v3 = __asm_lwr(1); // 0x1d015dfc
        __asm_lwl(*(int32_t *)(v2 + 7));
        int32_t v4 = __asm_lwr(*(int32_t *)(v2 + 4)); // 0x1d015e04
        __asm_lwl(*(int32_t *)(v2 + 11));
        int32_t v5 = __asm_lwr(*(int32_t *)(v2 + 8)); // 0x1d015e0c
        __asm_lwl(*(int32_t *)(v2 + 15));
        int32_t v6 = __asm_lwr(*(int32_t *)(v2 + 12)); // 0x1d015e14
        __asm_swl(v3, *(int32_t *)(v1 + 3));
        __asm_swr(v3, *(int32_t *)v1);
        __asm_swl(v4, *(int32_t *)(v1 + 7));
        __asm_swr(v4, *(int32_t *)(v1 + 4));
        __asm_swl(v5, *(int32_t *)(v1 + 11));
        __asm_swr(v5, *(int32_t *)(v1 + 8));
        __asm_swl(v6, *(int32_t *)(v1 + 15));
        __asm_swr(v6, *(int32_t *)(v1 + 12));
        function_1d01c21c(1, 2);
        function_1d01c248(1, 2);
        result = 1;
    }
    // 0x1d015e54
    return result;
}

// Address range: 0x1d016078 - 0x1d01612c
int32_t function_1d016078(int32_t * a1) {
    int32_t result = function_1d0105f4(3); // 0x1d016090
    if (result == 0 || (function_1d010b3c(3) & 4) != 0) {
        // 0x1d016118
        return 0;
    }
    int32_t v1 = (int32_t)a1;
    int32_t * v2 = (int32_t *)(v1 + 4); // 0x1d0160b4
    uint32_t v3 = *v2; // 0x1d0160b4
    int32_t v4 = __asm_ext(v3, 28, 1); // 0x1d0160b8
    int32_t v5 = 3; // 0x1d0160c0
    if (v4 != 0) {
        // 0x1d0160c4
        v5 = __asm_ext(*v2, 10, 18) | 0xc0000;
    }
    // 0x1d0160e8
    function_1d0114e4(3, 0, v5, v4, v1 + 8, v3 % 16);
    function_1d011154(3, 0);
    // 0x1d016118
    return result;
}

// Address range: 0x1d016388 - 0x1d01643c
int32_t function_1d016388(int32_t * a1) {
    int32_t result = function_1d0105f4(2); // 0x1d0163a0
    if (result == 0 || (function_1d010b3c(2) & 4) != 0) {
        // 0x1d016428
        return 0;
    }
    int32_t v1 = (int32_t)a1;
    int32_t * v2 = (int32_t *)(v1 + 4); // 0x1d0163c4
    uint32_t v3 = *v2; // 0x1d0163c4
    int32_t v4 = __asm_ext(v3, 28, 1); // 0x1d0163c8
    int32_t v5 = 2; // 0x1d0163d0
    if (v4 != 0) {
        // 0x1d0163d4
        v5 = __asm_ext(*v2, 10, 18) | 0x80000;
    }
    // 0x1d0163f8
    function_1d0114e4(2, 0, v5, v4, v1 + 8, v3 % 16);
    function_1d011154(2, 0);
    // 0x1d016428
    return result;
}

// Address range: 0x1d017078 - 0x1d017234
int32_t function_1d017078(int32_t * a1) {
    int32_t v1 = (int32_t)a1 + 4; // 0x1d017094
    int32_t * v2 = (int32_t *)v1; // 0x1d017094
    int32_t v3 = *v2; // 0x1d017094
    int32_t v4; // 0x1d017078
    char * v5 = (char *)(v4 - 0x7fb0);
    int32_t v6 = 0; // 0x1d0170a0
    if (__asm_ext(v3, 25, 1) != 0) {
        // 0x1d0170a4
        v6 = (int32_t)(*v5 % 2 ^ 1);
    }
    int32_t v7 = *v2; // 0x1d0170b0
    int32_t v8 = __asm_ext(v7, 25, 1); // 0x1d0170b4
    char v9 = v8; // 0x1d0170bc
    *v5 = v9;
    uint16_t v10 = *(int16_t *)v1; // 0x1d0170c0
    *(int32_t *)(v4 - 0x7fa8) = (int32_t)v10;
    *(int32_t *)(v4 - 0x7fa4) = 200;
    int32_t v11 = __asm_ext(v7, 24, 1); // 0x1d0170d0
    uint32_t v12 = __asm_ext(v7, 27, 1); // 0x1d0170d8
    if (*(int32_t*)0xa0013668 == 0) {
        goto lab_0x1d0171d4;
    } else {
        if (v12 % 256 == 0) {
            goto lab_0x1d017138;
        } else {
            // 0x1d017100
            if (*(char*)0xa001366f == 0) {
                // 0x1d017110
                *(char*)0xa001365d = 1;
                int32_t * v13 = (int32_t *)(v4 - 0x7fb4); // 0x1d01711c
                if (*v13 == 0) {
                    // 0x1d017128
                    *v13 = 1;
                    *(int32_t *)(v4 - 0x7fbc) = 3;
                }
                goto lab_0x1d0171d4;
            } else {
                goto lab_0x1d017138;
            }
        }
    }
  lab_0x1d0171d4:
    if (v6 != 0) {
        int32_t * v14 = (int32_t *)(v4 - 0x7fb4); // 0x1d0171dc
        if (*v14 == 1) {
            // 0x1d0171e8
            *v14 = 2;
        }
    }
    // 0x1d0171f4
    *(int32_t*)0xa0013668 = 100;
    *(char*)0xa001366c = (char)v11;
    *(char*)0xa001366d = v9;
    *(char*)0xa001366e = (char)v6;
    *(char*)0xa001366f = (char)v12;
    *(char*)0xa0013670 = (char)((v3 & 0x74000000) != 0);
    return -0x5ffec9d4;
  lab_0x1d017138:
    // 0x1d017138
    if (*(char*)0xa001365c != 0) {
        // 0x1d017144
        if ((v11 | v8) % 256 == 0 == (*(char*)0xa001366c != 0)) {
            // 0x1d017160
            if (*(char*)0xa001363d == 0) {
                // 0x1d01716c
                if (*(char*)0xa0013655 == 0) {
                    // 0x1d017178
                    if (*(char*)0xa001366d == 0) {
                        char v15 = *(char *)(v4 - 0x7faf); // 0x1d017188
                        if (v10 == 0 != (*(int32_t *)(v4 - 0x7fac) == 0 || v15 == 1)) {
                            // 0x1d0171a0
                            if (function_1d01504c() == 0) {
                                // 0x1d0171b0
                                *(char*)0xa001365d = 1;
                                *(char *)(v4 - 0x7fe8) = 0;
                                int32_t * v16 = (int32_t *)(v4 - 0x7fb4); // 0x1d0171bc
                                if (*v16 == 0) {
                                    // 0x1d0171c8
                                    *v16 = 1;
                                    *(int32_t *)(v4 - 0x7fbc) = 13;
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    goto lab_0x1d0171d4;
}

// Address range: 0x1d01728c - 0x1d017294
int32_t exit(void) {
    // 0x1d01728c
    int32_t v1; // 0x1d01728c
    return *(int32_t *)(v1 - 0x7fb4);
}

// Address range: 0x1d0172b8 - 0x1d0172dc
int32_t function_1d0172b8(void) {
    // 0x1d0172b8
    int32_t v1; // 0x1d0172b8
    int32_t v2 = *(int32_t *)(v1 - 0x7fb4); // 0x1d0172b8
    int32_t result = 1; // 0x1d0172c0
    if (v2 != 0) {
        // 0x1d0172c4
        result = v2 == 1 ? (int32_t)*(char *)(v1 - 0x7fe8) : 0;
    }
    // 0x1d0172d4
    return result;
}

// Address range: 0x1d01852c - 0x1d018540
int32_t function_1d01852c(void) {
    // 0x1d01852c
    return (int32_t)*(char*)0xa00001f2;
}

// Address range: 0x1d01a548 - 0x1d01a6e0
int32_t pthread_cond_destroy3(void) {
    // 0x1d01a548
    int32_t v1; // 0x1d01a548
    char * v2 = (char *)(v1 - 0x7f18); // 0x1d01a548
    if (*v2 % 32 != 1) {
        // 0x1d01a6d8
        return 1;
    }
    char result = *(char *)(v1 - 0x7f14); // 0x1d01a55c
    if (result != 0) {
        // 0x1d01a6d8
        return result;
    }
    char * v3 = (char *)(v1 - 0x7f17); // 0x1d01a56c
    if (*v3 == 6) {
        // 0x1d01a580
        switch (*(char *)(v1 - 0x7f15)) {
            case 33: {
                // 0x1d01a5a4
                if (*(char *)(v1 - 0x7f28) == 1) {
                    // 0x1d01a5b8
                    *(int32_t*)0xa0000480 = -0x62fe4d6a;
                    *(int16_t *)-0x5ffffb78 = 9;
                    *(char*)0xa0000484 = -64;
                }
                // break -> 0x1d01a600
                break;
            }
            case 34: {
                // 0x1d01a5e0
                *(int32_t*)0xa0000480 = -0x62fe4dc0;
                *(int16_t *)-0x5ffffb78 = 29;
                *(char*)0xa0000484 = -64;
                // break -> 0x1d01a600
                break;
            }
        }
    }
    // 0x1d01a600
    if ((*v2 & 96) != 32) {
        // 0x1d01a6d8
        return 32;
    }
    unsigned char result4 = *v3; // 0x1d01a614
    if (result4 == 3) {
        // 0x1d01a69c
        *(int32_t*)0xa0000480 = v1 - 0x7ed7;
        *(int16_t *)-0x5ffffb78 = 1;
        *(char*)0xa0000484 = -127;
        return -0x5ffffb80;
    }
    if (result4 < 4) {
        // 0x1d01a630
        if (result4 != 2) {
            // 0x1d01a63c
            return -0x60000000;
        }
        // 0x1d01a65c
        *(int32_t*)0xa0000480 = v1 - 0x7ed8;
        *(int16_t *)-0x5ffffb78 = 1;
        *(char*)0xa0000484 = -63;
        return -0x5ffffb80;
    }
    // 0x1d01a644
    switch (result4) {
        case 10: {
            // 0x1d01a680
            *(char*)0xa0000484 = -128;
            unsigned char result2 = *(char *)(v1 - 0x7f15); // 0x1d01a690
            *(char *)(v1 - 0x7ed8) = result2;
            return result2;
        }
        case 11: {
            // 0x1d01a6c4
            *(char*)0xa0000484 = -128;
            char result3 = *(char *)(v1 - 0x7f16); // 0x1d01a6d0
            *(char *)(v1 - 0x7ed7) = result3;
            // 0x1d01a6d8
            return result3;
        }
    }
    // 0x1d01a63c
    return result4;
}

// Address range: 0x1d01bfcc - 0x1d01c010
int32_t function_1d01bfcc(int32_t a1, int32_t a2) {
    int32_t v1 = *(int32_t *)(4 * a1 - 0x5ffecc6c) + 64 * a2; // 0x1d01bfe4
    if (__asm_ext(*(int32_t *)(v1 + 864), 10, 1) == 0) {
        // 0x1d01c008
        return 0;
    }
    // 0x1d01bff8
    return *(int32_t *)(v1 + 880) | -0x60000000;
}

// Address range: 0x1d01c21c - 0x1d01c248
int32_t function_1d01c21c(int32_t a1, int32_t a2) {
    int32_t result = *(int32_t *)(4 * a1 - 0x5ffecc6c) + 64 * a2; // 0x1d01c234
    *(int32_t *)(result + 856) = 0x2000;
    return result;
}

// Address range: 0x1d01c248 - 0x1d01c274
int32_t function_1d01c248(int32_t a1, int32_t a2) {
    int32_t result = *(int32_t *)(4 * a1 - 0x5ffecc6c) + 64 * a2; // 0x1d01c260
    *(int32_t *)(result + 856) = 8;
    return result;
}

// Address range: 0x1d01c4a0 - 0x1d01c4a8
int32_t exit3(void) {
    // 0x1d01c4a0
    int32_t result; // 0x1d01c4a0
    __asm_di(result);
    return result;
}

// --------------------- Meta-Information ---------------------

// Detected functions: 25
