//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int32_t exit(void);
int32_t exit2(void);
int32_t exit3(void);
int32_t function_1d008924(void);
int32_t function_1d00921c(int32_t * a1);
int32_t function_1d010294(int32_t a1);
int32_t function_1d0107dc(int32_t a1);
int32_t function_1d010df4(int32_t a1, uint32_t a2);
int32_t function_1d011184(int32_t a1, int32_t a2, uint32_t a3, int32_t a4, int32_t a5, uint32_t a6);
int32_t function_1d01326c(int32_t * a1);
int32_t function_1d0149f0(int32_t a1);
int32_t function_1d014a80(int32_t * a1);
int32_t function_1d014d08(int32_t * a1);
int32_t function_1d014fe0(int32_t * a1);
int32_t function_1d015dbc(int32_t * a1);
int32_t function_1d015fd8(void);
int32_t function_1d0172f0(void);
int32_t function_1d01aacc(char a1);
int32_t function_1d01ac1c(int32_t a1, int32_t a2);
int32_t function_1d01ae6c(int32_t a1, int32_t a2);
int32_t function_1d01ae98(int32_t a1, int32_t a2);
int32_t pthread_cond_destroy(int32_t * a1);
int32_t pthread_cond_destroy2(int32_t * a1);
int32_t pthread_cond_destroy3(void);
int32_t time(int32_t a1);

// ------------------------ Functions -------------------------

// Address range: 0x1d008924 - 0x1d0089c0
int32_t function_1d008924(void) {
    // 0x1d008924
    if (*(int32_t*)0xa0013244 < 101) {
        // 0x1d0089b8
        return 8;
    }
    int32_t v1 = 938; // bp-24, 0x1d008948
    if (*(int32_t*)0xa00132c4 < 3) {
        // 0x1d008984
        __asm_ins(2, 4, 4);
    } else {
        // 0x1d008960
        __asm_ins(15, 4, 4);
    }
    // 0x1d008998
    __asm_ins(1, 15, 1);
    // 0x1d0089b8
    return pthread_cond_destroy2(&v1);
}

// Address range: 0x1d00921c - 0x1d0094cc
int32_t function_1d00921c(int32_t * a1) {
    int32_t v1 = (int32_t)a1;
    *(char *)a1 = 0;
    *(char *)(v1 + 1) = 0;
    int32_t v2 = v1 + 2; // 0x1d009230
    *(char *)v2 = 0;
    *(char *)(v1 + 3) = 0;
    int32_t v3 = v1 + 4; // 0x1d009238
    *(char *)v3 = 0;
    *(char *)(v1 + 5) = 0;
    char * v4 = (char *)(v1 + 6); // 0x1d009240
    *v4 = 0;
    char * v5 = (char *)(v1 + 7); // 0x1d009244
    *v5 = 0;
    *(int16_t *)a1 = (int16_t)*(int32_t*)0xa00001b0;
    int32_t v6 = *(int32_t*)0xa00001ac; // 0x1d009258
    *(int16_t *)v2 = (int16_t)((int32_t)(0x51eb851f * (int64_t)v6 / 0x2000000000) - (v6 >> 31));
    int32_t v7; // 0x1d00921c
    int32_t v8; // 0x1d00921c
    if (*(int32_t*)0xa001316c < 4) {
        // 0x1d00936c
        v8 = 0;
        goto lab_0x1d009374;
    } else {
        int32_t v9 = *(int32_t*)0xa001318c; // 0x1d009294
        v7 = v9;
        if (v9 >= 4) {
            // 0x1d00943c
            v7 = v9;
            if (*(int32_t*)0xa00130b8 >= 4) {
                // 0x1d0092ac
                v7 = v9;
                if (*(int32_t*)0xa0013068 >= 4) {
                    unsigned char v10 = *(char*)0xa0013062; // 0x1d009458
                    unsigned char v11 = *(char*)0xa0013063; // 0x1d009460
                    *(int16_t *)v3 = 256 * (int16_t)v10 | (int16_t)v11;
                    *v4 = *(char*)0xa0013160 ^ -128;
                    v8 = 0;
                    if (*(int32_t*)0xa001316c >= 4) {
                        // 0x1d009454
                        v7 = *(int32_t*)0xa001318c;
                        goto lab_0x1d0092c0;
                    } else {
                        goto lab_0x1d009374;
                    }
                } else {
                    goto lab_0x1d0092c0;
                }
            } else {
                goto lab_0x1d0092c0;
            }
        } else {
            goto lab_0x1d0092c0;
        }
    }
  lab_0x1d009374:
    // 0x1d009374
    __asm_ins(v8, 0, 1);
    *v5 = (char)__asm_ins((int32_t)*(char*)0xa0000152, 1, 1);
    *v5 = (char)__asm_ins(function_1d0172f0(), 2, 1);
    *v5 = (char)__asm_ins((int32_t)(exit() != 0), 3, 1);
    int32_t v12 = 1; // 0x1d0093bc
    if (*(int32_t*)0xa00130b8 >= 4) {
        // 0x1d0093c0
        v12 = *(int32_t*)0xa0013068 < 4;
    }
    // 0x1d0093d0
    *v5 = (char)__asm_ins(v12, 4, 1);
    int32_t v13 = 1; // 0x1d0093f0
    if (*(int32_t*)0xa001316c >= 4) {
        // 0x1d0093f4
        v13 = *(int32_t*)0xa001318c < 4;
    }
    // 0x1d009404
    *v5 = (char)__asm_ins(v13, 5, 1);
    *v5 = (char)__asm_ins((int32_t)*(char*)0xa0000153, 6, 1);
    int32_t result = __asm_ins((int32_t)(*(int32_t*)0xa00131dc == 0), 7, 1); // 0x1d009430
    *v5 = (char)result;
    return result;
  lab_0x1d0092c0:
    // 0x1d0092c0
    v8 = 0;
    if (v7 >= 4) {
        // 0x1d009490
        v8 = 0;
        if (*(int32_t*)0xa00130b8 >= 4) {
            // 0x1d0092d8
            v8 = 0;
            if (*(int32_t*)0xa0013068 >= 4) {
                // 0x1d0094a8
                v8 = 0;
                if (*(int32_t*)0xa00131dc == 0) {
                    goto lab_0x1d009374;
                } else {
                    // 0x1d0092f0
                    v8 = 0;
                    if (__asm_ext(*(int32_t*)0xa00131d4, 16, 1) == 0) {
                        goto lab_0x1d009374;
                    } else {
                        // 0x1d009300
                        v8 = 0;
                        if (*(char*)0xa0000152 == 0) {
                            // 0x1d009310
                            v8 = 0;
                            if (*(char*)0xa0000153 == 0) {
                                // 0x1d009320
                                if (exit() == 0) {
                                    goto lab_0x1d009340;
                                } else {
                                    // 0x1d009330
                                    v8 = 0;
                                    if (function_1d015fd8() == 0) {
                                        goto lab_0x1d009374;
                                    } else {
                                        goto lab_0x1d009340;
                                    }
                                }
                            } else {
                                goto lab_0x1d009374;
                            }
                        } else {
                            goto lab_0x1d009374;
                        }
                    }
                }
            } else {
                goto lab_0x1d009374;
            }
        } else {
            goto lab_0x1d009374;
        }
    } else {
        goto lab_0x1d009374;
    }
  lab_0x1d009340:
    // 0x1d009340
    v8 = 0;
    if (function_1d0172f0() == 0) {
        // 0x1d009350
        v8 = 1;
        if ((*(int32_t*)0xa0013160 & 0xc00000) == 0x800000) {
            goto lab_0x1d009374;
        } else {
            // 0x1d00936c
            v8 = 0;
            goto lab_0x1d009374;
        }
    } else {
        goto lab_0x1d009374;
    }
}

// Address range: 0x1d0094cc - 0x1d009600
int32_t time(int32_t a1) {
    // 0x1d0094cc
    int32_t v1; // bp-16, 0x1d0094cc
    int32_t v2; // bp-24, 0x1d0094cc
    if (*(char*)0xa0000151 == 0) {
        // 0x1d009560
        if (a1 != 0) {
            // 0x1d0095f8
            return -0x60000000;
        }
    } else {
        int32_t v3 = 0; // 0x1d0094ec
        if (*(int32_t*)0xa00130b4 != 0) {
            // 0x1d0094f0
            v3 = __asm_ins(0, 23, 1);
        }
        // 0x1d009514
        v1 = v3;
        v2 = 936;
        if (a1 != 0) {
            // 0x1d009528
            *(int32_t*)0xbf8860e8 = 32;
            // 0x1d0095f8
            return function_1d014a80(&v2);
        }
        // 0x1d009544
        pthread_cond_destroy(&v2);
        *(int32_t*)0xbf8860e4 = 32;
    }
    // 0x1d009568
    if (*(int32_t*)0xa000014c == 0) {
        // 0x1d009574
        v2 = 101;
        function_1d00921c(&v1);
        function_1d015dbc(&v1);
        function_1d01326c(&v2);
    }
    // 0x1d0095a0
    if (*(int32_t*)0xa00131ac != 0) {
        // 0x1d0095ac
        if (__asm_ext(*(int32_t*)0xa00131a8, 24, 1) != 0) {
            // 0x1d0095f8
            return function_1d008924();
        }
    }
    // 0x1d0095c0
    if (*(int32_t*)0xa00131cc != 0) {
        // 0x1d0095cc
        if (__asm_ext(*(int32_t*)0xa00131c8, 24, 1) != 0) {
            // 0x1d0095f8
            return function_1d008924();
        }
    }
    // 0x1d0095e0
    if (*(char*)0xa0000151 == 0) {
        // 0x1d0095f8
        return 0;
    }
    // 0x1d0095f8
    return function_1d008924();
}

// Address range: 0x1d00e530 - 0x1d00e758
int32_t exit2(void) {
    // 0x1d00e530
    *(int32_t*)0xbf881074 = 0x2000000;
    *(int32_t*)0xbf885220 = 255;
    *(int32_t*)0xbf885200 = 255;
    *(int32_t*)0xbf885300 = 0;
    *(int32_t*)0xbf885310 = 0;
    *(int32_t*)0xbf885320 = 0;
    *(int32_t*)0xbf885330 = 0;
    *(int32_t*)0xbf8852e0 = 0;
    *(int32_t*)0xbf885230 = 159;
    *(int32_t*)0xbf885210 = 159;
    *(int32_t*)0xbf885070 = *(int32_t*)0xbf885070 % 16;
    *(char*)0xbf885080 = (char)__asm_ins(1, 0, 1);
    uint32_t v1 = __asm_ext(-0x5ffffc00, 0, 29); // 0x1d00e5bc
    *(int32_t*)0xbf8852d0 = v1 / 0x1000000;
    *(int32_t*)0xbf8852c0 = v1 / 0x10000;
    *(int32_t*)0xbf885270 = v1 / 256;
    int32_t v2 = 0; // 0x1d00e5f4
    int32_t v3 = 0; // 0x1d00e5f4
    *(int32_t *)(v2 - 0x5ffffc00) = 0;
    *(int32_t *)(v2 - 0x5ffffbfc) = 0;
    v3++;
    v2 = 8 * v3;
    while (v3 != 16) {
        // 0x1d00e5f8
        *(int32_t *)(v2 - 0x5ffffc00) = 0;
        *(int32_t *)(v2 - 0x5ffffbfc) = 0;
        v3++;
        v2 = 8 * v3;
    }
    // 0x1d00e618
    *(char*)0xbf885250 = (char)__asm_ins(1, 1, 1);
    *(int32_t*)0xbf885260 = 0;
    *(char*)0xbf885250 = (char)__asm_ins(0, 5, 1);
    *(char*)0xbf885250 = (char)__asm_ins(0, 1, 1);
    if ((*(int32_t*)0xbf885200 & 8) != 0) {
        *(int32_t*)0xbf885200 = 8;
        *(char*)0xa0000484 = 0;
        *(char*)0xa00004d4 = 0;
        *(int32_t*)0xa00004d4 = __asm_ins(0, 8, 16);
        while ((*(int32_t*)0xbf885200 & 8) != 0) {
            // 0x1d00e670
            *(int32_t*)0xbf885200 = 8;
            *(char*)0xa0000484 = 0;
            *(char*)0xa00004d4 = 0;
            *(int32_t*)0xa00004d4 = __asm_ins(0, 8, 16);
        }
    }
    // 0x1d00e6a0
    int32_t v4; // 0x1d00e530
    *(int32_t *)(v4 - 0x7f24) = 1;
    *(int32_t *)(v4 - 0x7f1c) = 1;
    *(int32_t *)(v4 - 0x7eec) = 0;
    *(int32_t *)(v4 - 0x7ee8) = 0;
    *(int32_t *)(v4 - 0x7f08) = 0;
    int32_t v5 = -0x5ffffe00; // 0x1d00e6d4
    int32_t v6 = -0x5ffffdf0; // 0x1d00e6d4
    int32_t v7 = 0; // 0x1d00e6d4
    *(int32_t *)v6 = 0;
    *(int32_t *)v5 = 0;
    int32_t v8 = v7 + v4;
    *(char *)(v8 - 0x7ed4) = 0;
    *(char *)(v8 - 0x7f04) = 0;
    v7++;
    v5 += 4;
    v6 += 4;
    while (v7 != 4) {
        // 0x1d00e6d8
        *(int32_t *)v6 = 0;
        *(int32_t *)v5 = 0;
        v8 = v7 + v4;
        *(char *)(v8 - 0x7ed4) = 0;
        *(char *)(v8 - 0x7f04) = 0;
        v7++;
        v5 += 4;
        v6 += 4;
    }
    // 0x1d00e700
    *(int32_t*)0xa0000210 = -0x5ffffbf0;
    *(int32_t*)0xbf885300 = 13;
    *(int32_t*)0xa0000404 = __asm_ext(v4 - 0x7f10, 0, 29);
    *(int16_t *)-0x5ffffbfe = (int16_t)__asm_ins(64, 0, 10);
    *(int16_t *)-0x5ffffc00 = 132;
    *(char *)(v4 - 0x7f20) = 0;
    *(int32_t *)(v4 - 0x7ee4) = 0;
    return 132;
}

// Address range: 0x1d010294 - 0x1d0102a4
int32_t function_1d010294(int32_t a1) {
    // 0x1d010294
    int32_t v1; // 0x1d010294
    return (int32_t)*(char *)(a1 - 0x7f3c + v1);
}

// Address range: 0x1d0107dc - 0x1d010a10
int32_t function_1d0107dc(int32_t a1) {
    switch (a1) {
        case 3: {
            // 0x1d010814
            *(int32_t*)0xbf8860e4 = 512;
            *(int32_t*)0xbf8860c4 = 512;
            *(int32_t*)0xbf805820 = 160;
            while ((*(int32_t*)0xbf805810 & 0x1f000000) == 0) {
                // continue -> 0x1d0108a8
            }
            // 0x1d01093c
            *(int32_t*)0xbf805820 = 0;
            while ((*(int32_t*)0xbf805810 & 0x1f000000) == 0) {
                // continue -> 0x1d010948
            }
            // 0x1d010958
            *(int32_t*)0xbf8860e8 = 512;
            *(int32_t*)0xbf8860c4 = 512;
            return 0;
        }
        case 4: {
            // 0x1d010830
            *(int32_t*)0xbf886064 = 256;
            *(int32_t*)0xbf886044 = 256;
            *(int32_t*)0xbf805c20 = 160;
            while ((*(int32_t*)0xbf805c10 & 0x1f000000) == 0) {
                // continue -> 0x1d0108d8
            }
            // 0x1d010968
            *(int32_t*)0xbf805c20 = 0;
            while ((*(int32_t*)0xbf805c10 & 0x1f000000) == 0) {
                // continue -> 0x1d010974
            }
            // 0x1d010984
            *(int32_t*)0xbf886068 = 256;
            *(int32_t*)0xbf886044 = 256;
            return 0;
        }
        case 2: {
            // 0x1d0107f8
            *(int32_t*)0xbf8861a4 = 512;
            *(int32_t*)0xbf886184 = 512;
            *(int32_t*)0xbf805a20 = 160;
            while ((*(int32_t*)0xbf805a10 & 0x1f000000) == 0) {
                // continue -> 0x1d010878
            }
            // 0x1d010910
            *(int32_t*)0xbf805a20 = 0;
            while ((*(int32_t*)0xbf805a10 & 0x1f000000) == 0) {
                // continue -> 0x1d01091c
            }
            // 0x1d01092c
            *(int32_t*)0xbf8861a8 = 512;
            *(int32_t*)0xbf886184 = 512;
            return 0;
        }
    }
    // 0x1d010a08
    return 0;
}

// Address range: 0x1d010df4 - 0x1d010fac
int32_t function_1d010df4(int32_t a1, uint32_t a2) {
    switch (a1) {
        case 3: {
            // 0x1d010e44
            *(int32_t*)0xbf8860e4 = 512;
            *(int32_t*)0xbf8860c4 = 512;
            *(int32_t*)0xbf805820 = (1 << a2 % 4) % 128 | 128;
            while ((*(int32_t*)0xbf805810 & 0x1f000000) == 0) {
                // continue -> 0x1d010efc
            }
            // 0x1d010f78
            *(int32_t*)0xbf8860e8 = 512;
            *(int32_t*)0xbf8860c4 = 512;
            return 512;
        }
        case 4: {
            // 0x1d010e6c
            *(int32_t*)0xbf886064 = 256;
            *(int32_t*)0xbf886044 = 256;
            *(int32_t*)0xbf805c20 = (1 << a2 % 4) % 128 | 128;
            while ((*(int32_t*)0xbf805c10 & 0x1f000000) == 0) {
                // continue -> 0x1d010f28
            }
            // 0x1d010f94
            *(int32_t*)0xbf886068 = 256;
            *(int32_t*)0xbf886044 = 256;
            return 256;
        }
        case 2: {
            // 0x1d010e18
            *(int32_t*)0xbf8861a4 = 512;
            *(int32_t*)0xbf886184 = 512;
            *(int32_t*)0xbf805a20 = (1 << a2 % 4) % 128 | 128;
            while ((*(int32_t*)0xbf805a10 & 0x1f000000) == 0) {
                // continue -> 0x1d010ed0
            }
            // 0x1d010f5c
            *(int32_t*)0xbf8861a8 = 512;
            *(int32_t*)0xbf886184 = 512;
            // 0x1d010f6c
            return 512;
        }
    }
    // 0x1d010f6c
    return 512;
}

// Address range: 0x1d011184 - 0x1d011460
int32_t function_1d011184(int32_t a1, int32_t a2, uint32_t a3, int32_t a4, int32_t a5, uint32_t a6) {
    switch (a1) {
        case 3: {
            // 0x1d0111dc
            *(int32_t*)0xbf8860e4 = 512;
            *(int32_t*)0xbf8860c4 = 512;
            // break -> 0x1d011210
            break;
        }
        case 4: {
            // 0x1d0111f8
            *(int32_t*)0xbf886064 = 256;
            *(int32_t*)0xbf886044 = 256;
            // break -> 0x1d011210
            break;
        }
        case 2: {
            // 0x1d0111c0
            *(int32_t*)0xbf8861a4 = 512;
            *(int32_t*)0xbf886184 = 512;
            // break -> 0x1d011210
            break;
        }
    }
    char v1; // bp-7, 0x1d011184
    if (a4 == 0) {
        // 0x1d011250
        v1 = a3 / 8;
    } else {
        // 0x1d011220
        v1 = a3 / 0x200000;
        __asm_ins(0, 0, 5);
        __asm_ext(a3, 16, 2);
    }
    int32_t * v2 = (int32_t*)0xbf805a20; // 0x1d011184
    int32_t * v3 = (int32_t*)0xbf805a10; // 0x1d011184
    int32_t result = 2; // 0x1d011184
    switch (a1) {
        case 3: {
            // 0x1d0112b0
            v2 = (int32_t*)0xbf805820;
            v3 = (int32_t*)0xbf805810;
            goto lab_0x1d0112c0;
        }
        case 4: {
            // 0x1d01129c
            v2 = (int32_t*)0xbf805c20;
            v3 = (int32_t*)0xbf805c10;
            goto lab_0x1d0112c0;
        }
        case 2: {
            goto lab_0x1d0112c0;
        }
        default: {
            return result;
        }
    }
  lab_0x1d0112c0:;
    uint32_t v4 = a6 % 256; // 0x1d011188
    int32_t v5 = v4 < 8 ? v4 : 8;
    int32_t v6 = &v1;
    *v2 = (int32_t)*(char *)(v6 - 1);
    int32_t v7 = v6 + 1; // 0x1d0112d4
    int32_t v8; // bp-2, 0x1d011184
    while (v6 != (int32_t)&v8) {
        // 0x1d0112cc
        v6 = v7;
        *v2 = (int32_t)*(char *)(v6 - 1);
        v7 = v6 + 1;
    }
    // 0x1d0112e4
    while ((*v3 & 0x1e000000) < 0x6000000) {
        // continue -> 0x1d0112e4
    }
    int32_t * v9 = (int32_t*)0xbf805a20; // 0x1d011184
    int32_t * v10 = (int32_t*)0xbf805a10; // 0x1d011184
    result = 2;
    switch (a1) {
        case 3: {
            // 0x1d011358
            v9 = (int32_t*)0xbf805820;
            v10 = (int32_t*)0xbf805810;
            goto lab_0x1d011368;
        }
        case 4: {
            // 0x1d011344
            v9 = (int32_t*)0xbf805c20;
            v10 = (int32_t*)0xbf805c10;
            goto lab_0x1d011368;
        }
        case 2: {
            goto lab_0x1d011368;
        }
        default: {
            return result;
        }
    }
  lab_0x1d011368:
    // 0x1d011368
    if (a5 == 0) {
        if (v5 != 0) {
            // 0x1d0113a4
            *v9 = 0;
        }
    } else {
        // 0x1d011380
        if (v5 != 0) {
            int32_t v11 = a5 + 1;
            *v9 = (int32_t)*(char *)a5;
            int32_t v12 = v11; // 0x1d011398
            while (v11 != v5 + a5) {
                // 0x1d01138c
                v11 = v12 + 1;
                *v9 = (int32_t)*(char *)v12;
                v12 = v11;
            }
        }
    }
    // 0x1d0113b8
    while ((*v10 & 0x1f000000) < 0x1000000 * v5) {
        // continue -> 0x1d0113bc
    }
    // 0x1d0113f0
    result = 2;
    switch (a1) {
        case 3: {
            // 0x1d011424
            *(int32_t*)0xbf8860e8 = 512;
            *(int32_t*)0xbf8860c4 = 512;
            result = 512;
            // break -> 0x1d011458
            break;
        }
        case 4: {
            // 0x1d011440
            *(int32_t*)0xbf886068 = 256;
            *(int32_t*)0xbf886044 = 256;
            result = 256;
            // break -> 0x1d011458
            break;
        }
        case 2: {
            // 0x1d011408
            *(int32_t*)0xbf8861a8 = 512;
            *(int32_t*)0xbf886184 = 512;
            result = 512;
            // break -> 0x1d011458
            break;
        }
    }
    // 0x1d011458
    return result;
}

// Address range: 0x1d01326c - 0x1d0134fc
int32_t function_1d01326c(int32_t * a1) {
    int32_t v1 = (int32_t)a1;
    int32_t v2; // 0x1d01326c
    if ((*(int32_t *)(v2 - 0x7f34) & 32) != 0) {
        int32_t v3 = *(int32_t*)0xa0000cf8; // 0x1d013294
        uint32_t v4 = *(int32_t*)0xa0000cf4; // 0x1d01329c
        uint32_t v5 = v4 % 0x1000; // 0x1d0132a0
        if (v5 != (v3 + 1) % 0x1000) {
            int32_t * v6 = (int32_t *)(v1 + 4); // 0x1d0132c4
            uint32_t v7 = *v6; // 0x1d0132c4
            int32_t v8 = __asm_ext(v7, 28, 1); // 0x1d0132c8
            int32_t v9; // 0x1d01326c
            if (v8 == 0) {
                // 0x1d0132f0
                v9 = v4 % 2048;
            } else {
                // 0x1d0132d4
                v9 = __asm_ext(*v6, 10, 18) | 0x40000 * v5 & 0x1ffc0000;
            }
            int32_t v10 = 16 * v3 & 0xfff0; // 0x1d0132b0
            uint32_t v11 = v7 % 16; // 0x1d0132d0
            __asm_ins(v9, 0, 29);
            __asm_ins(v8, 29, 1);
            __asm_ins(v11, 30, 2);
            *(int32_t *)(v10 - 0x5ffff300) = __asm_ins(v11 / 4, 30, 2);
            __asm_ins(5, 27, 3);
            *(int32_t *)(v10 - 0x5ffff304) = __asm_ins(*(int32_t *)(v2 - 0x7f30), 0, 27);
            __asm_lwl(*(int32_t *)(v1 + 11));
            int32_t v12 = __asm_lwr(*(int32_t *)(v1 + 8)); // 0x1d013334
            __asm_lwl(*(int32_t *)(v1 + 15));
            int32_t v13 = __asm_lwr(*(int32_t *)(v1 + 12)); // 0x1d01333c
            *(int32_t *)(v10 - 0x5ffff2fc) = v12;
            *(int32_t *)(v10 - 0x5ffff2f8) = v13;
            uint32_t v14 = (*(int32_t*)0xa0000cf8 + 1) % 0x1000; // 0x1d013358
            if (*(int32_t*)0xa0000cf4 % 0x1000 != v14) {
                // 0x1d01336c
                *(int32_t*)0xa0000cf8 = v14;
            }
        }
    }
    int32_t v15 = *(int32_t*)0xa00008e8 % 64; // 0x1d013410
    int32_t result2; // 0x1d01326c
    if (v15 == *(int32_t*)0xa00008ec % 64) {
      lab_0x1d0134d8:;
        int32_t result = function_1d014d08(a1); // 0x1d0134dc
        if (result != 0) {
            // 0x1d0134e8
            return result;
        }
        int32_t v16 = *(int32_t*)0xa00008ec; // 0x1d01346c
        uint32_t v17 = (v16 + 1) % 64; // 0x1d013478
        if (*(int32_t*)0xa00008e8 % 64 == v17) {
            // 0x1d0134c4
            *(int32_t*)0xa00008f0 = *(int32_t*)0xa00008f0 + 1;
            result2 = 0;
        } else {
            int32_t v18 = 16 * v16 & 1008; // 0x1d01348c
            *(int32_t *)(v18 - 0x5ffff70c) = v17;
            *(int32_t *)(v18 - 0x5ffff708) = *(int32_t *)(v1 + 4);
            *(int32_t *)(v18 - 0x5ffff704) = *(int32_t *)(v1 + 8);
            *(int32_t *)(v18 - 0x5ffff700) = *(int32_t *)(v1 + 12);
            *(int32_t*)0xa00008ec = v17;
            result2 = 1;
        }
        // 0x1d0134e8
        return result2;
    }
    int32_t v19 = *(int32_t *)(16 * v15 - 0x5ffff70c); // bp-32, 0x1d013440
    while (function_1d014d08(&v19) != 0) {
        int32_t v20 = *(int32_t*)0xa00008e8; // 0x1d01345c
        int32_t v21 = *(int32_t*)0xa00008ec; // 0x1d013380
        int32_t v22 = v21; // 0x1d01338c
        int32_t v23 = v20; // 0x1d01338c
        if ((v21 ^ v20) % 64 != 0) {
            // 0x1d013390
            v23 = (v20 + 1) % 64;
            *(int32_t*)0xa00008e8 = v23;
            v22 = *(int32_t*)0xa00008ec;
        }
        int32_t v24 = v23 % 64; // 0x1d013410
        if (v24 == v22 % 64) {
            goto lab_0x1d0134d8;
        }
        v19 = *(int32_t *)(16 * v24 - 0x5ffff70c);
    }
    int32_t v25 = *(int32_t*)0xa00008ec; // 0x1d0133a0
    uint32_t v26 = (v25 + 1) % 64; // 0x1d0133ac
    if (*(int32_t*)0xa00008e8 % 64 == v26) {
        // 0x1d0133f8
        *(int32_t*)0xa00008f0 = *(int32_t*)0xa00008f0 + 1;
        result2 = 0;
    } else {
        int32_t v27 = 16 * v25 & 1008; // 0x1d0133c0
        *(int32_t *)(v27 - 0x5ffff70c) = v26;
        *(int32_t *)(v27 - 0x5ffff708) = *(int32_t *)(v1 + 4);
        *(int32_t *)(v27 - 0x5ffff704) = *(int32_t *)(v1 + 8);
        *(int32_t *)(v27 - 0x5ffff700) = *(int32_t *)(v1 + 12);
        *(int32_t*)0xa00008ec = v26;
        result2 = 1;
    }
    // 0x1d0134e8
    return result2;
}

// Address range: 0x1d0134fc - 0x1d01378c
int32_t pthread_cond_destroy2(int32_t * a1) {
    int32_t v1 = (int32_t)a1;
    int32_t v2; // 0x1d0134fc
    if ((*(int32_t *)(v2 - 0x7f34) & 128) != 0) {
        int32_t v3 = *(int32_t*)0xa0000cf8; // 0x1d013524
        uint32_t v4 = *(int32_t*)0xa0000cf4; // 0x1d01352c
        uint32_t v5 = v4 % 0x1000; // 0x1d013530
        if (v5 != (v3 + 1) % 0x1000) {
            int32_t * v6 = (int32_t *)(v1 + 4); // 0x1d013554
            uint32_t v7 = *v6; // 0x1d013554
            int32_t v8 = __asm_ext(v7, 28, 1); // 0x1d013558
            int32_t v9; // 0x1d0134fc
            if (v8 == 0) {
                // 0x1d013580
                v9 = v4 % 2048;
            } else {
                // 0x1d013564
                v9 = __asm_ext(*v6, 10, 18) | 0x40000 * v5 & 0x1ffc0000;
            }
            int32_t v10 = 16 * v3 & 0xfff0; // 0x1d013540
            uint32_t v11 = v7 % 16; // 0x1d013560
            __asm_ins(v9, 0, 29);
            __asm_ins(v8, 29, 1);
            __asm_ins(v11, 30, 2);
            *(int32_t *)(v10 - 0x5ffff300) = __asm_ins(v11 / 4, 30, 2);
            __asm_ins(7, 27, 3);
            *(int32_t *)(v10 - 0x5ffff304) = __asm_ins(*(int32_t *)(v2 - 0x7f30), 0, 27);
            __asm_lwl(*(int32_t *)(v1 + 11));
            int32_t v12 = __asm_lwr(*(int32_t *)(v1 + 8)); // 0x1d0135c4
            __asm_lwl(*(int32_t *)(v1 + 15));
            int32_t v13 = __asm_lwr(*(int32_t *)(v1 + 12)); // 0x1d0135cc
            *(int32_t *)(v10 - 0x5ffff2fc) = v12;
            *(int32_t *)(v10 - 0x5ffff2f8) = v13;
            uint32_t v14 = (*(int32_t*)0xa0000cf8 + 1) % 0x1000; // 0x1d0135e8
            if (*(int32_t*)0xa0000cf4 % 0x1000 != v14) {
                // 0x1d0135fc
                *(int32_t*)0xa0000cf8 = v14;
            }
        }
    }
    int32_t v15 = *(int32_t*)0xa00004dc % 64; // 0x1d0136a0
    int32_t result2; // 0x1d0134fc
    if (v15 == *(int32_t*)0xa00004e0 % 64) {
      lab_0x1d013768:;
        int32_t result = function_1d014fe0(a1); // 0x1d01376c
        if (result != 0) {
            // 0x1d013778
            return result;
        }
        int32_t v16 = *(int32_t*)0xa00004e0; // 0x1d0136fc
        uint32_t v17 = (v16 + 1) % 64; // 0x1d013708
        if (*(int32_t*)0xa00004dc % 64 == v17) {
            // 0x1d013754
            *(int32_t*)0xa00004e4 = *(int32_t*)0xa00004e4 + 1;
            result2 = 0;
        } else {
            int32_t v18 = 16 * v16 & 1008; // 0x1d01371c
            *(int32_t *)(v18 - 0x5ffffb18) = v17;
            *(int32_t *)(v18 - 0x5ffffb14) = *(int32_t *)(v1 + 4);
            *(int32_t *)(v18 - 0x5ffffb10) = *(int32_t *)(v1 + 8);
            *(int32_t *)(v18 - 0x5ffffb0c) = *(int32_t *)(v1 + 12);
            *(int32_t*)0xa00004e0 = v17;
            result2 = 1;
        }
        // 0x1d013778
        return result2;
    }
    int32_t v19 = *(int32_t *)(16 * v15 - 0x5ffffb18); // bp-32, 0x1d0136d0
    while (function_1d014fe0(&v19) != 0) {
        int32_t v20 = *(int32_t*)0xa00004dc; // 0x1d0136ec
        int32_t v21 = *(int32_t*)0xa00004e0; // 0x1d013610
        int32_t v22 = v21; // 0x1d01361c
        int32_t v23 = v20; // 0x1d01361c
        if ((v21 ^ v20) % 64 != 0) {
            // 0x1d013620
            v23 = (v20 + 1) % 64;
            *(int32_t*)0xa00004dc = v23;
            v22 = *(int32_t*)0xa00004e0;
        }
        int32_t v24 = v23 % 64; // 0x1d0136a0
        if (v24 == v22 % 64) {
            goto lab_0x1d013768;
        }
        v19 = *(int32_t *)(16 * v24 - 0x5ffffb18);
    }
    int32_t v25 = *(int32_t*)0xa00004e0; // 0x1d013630
    uint32_t v26 = (v25 + 1) % 64; // 0x1d01363c
    if (*(int32_t*)0xa00004dc % 64 == v26) {
        // 0x1d013688
        *(int32_t*)0xa00004e4 = *(int32_t*)0xa00004e4 + 1;
        result2 = 0;
    } else {
        int32_t v27 = 16 * v25 & 1008; // 0x1d013650
        *(int32_t *)(v27 - 0x5ffffb18) = v26;
        *(int32_t *)(v27 - 0x5ffffb14) = *(int32_t *)(v1 + 4);
        *(int32_t *)(v27 - 0x5ffffb10) = *(int32_t *)(v1 + 8);
        *(int32_t *)(v27 - 0x5ffffb0c) = *(int32_t *)(v1 + 12);
        *(int32_t*)0xa00004e0 = v26;
        result2 = 1;
    }
    // 0x1d013778
    return result2;
}

// Address range: 0x1d013898 - 0x1d0139a4
int32_t pthread_cond_destroy(int32_t * a1) {
    uint32_t v1 = (int32_t)a1;
    int32_t v2; // 0x1d013898
    if ((*(int32_t *)(v2 - 0x7f34) & 8) == 0) {
        // 0x1d013990
        return function_1d0149f0(v1);
    }
    int32_t v3 = *(int32_t*)0xa0000cf8; // 0x1d0138b4
    if ((*(int32_t*)0xa0000cf4 ^ v3 + 1) % 0x1000 == 0) {
        // 0x1d013990
        return function_1d0149f0(v1);
    }
    int32_t * v4 = (int32_t *)(v1 + 4); // 0x1d0138e4
    uint32_t v5 = *v4; // 0x1d0138e4
    int32_t v6 = __asm_ext(v5, 28, 1); // 0x1d0138e8
    int32_t v7; // 0x1d013898
    if (v6 == 0) {
        // 0x1d013910
        v7 = v1 % 2048;
    } else {
        // 0x1d0138f4
        v7 = __asm_ext(*v4, 10, 18) | 0x40000 * v1 & 0x1ffc0000;
    }
    int32_t v8 = 16 * v3 & 0xfff0; // 0x1d0138d0
    uint32_t v9 = v5 % 16; // 0x1d0138f0
    __asm_ins(v7, 0, 29);
    __asm_ins(v6, 29, 1);
    __asm_ins(v9, 30, 2);
    *(int32_t *)(v8 - 0x5ffff300) = __asm_ins(v9 / 4, 30, 2);
    __asm_ins(3, 27, 3);
    *(int32_t *)(v8 - 0x5ffff304) = __asm_ins(*(int32_t *)(v2 - 0x7f30), 0, 27);
    __asm_lwl(*(int32_t *)(v1 + 11));
    int32_t v10 = __asm_lwr(*(int32_t *)(v1 + 8)); // 0x1d013954
    __asm_lwl(*(int32_t *)(v1 + 15));
    int32_t v11 = __asm_lwr(*(int32_t *)(v1 + 12)); // 0x1d01395c
    *(int32_t *)(v8 - 0x5ffff2fc) = v10;
    *(int32_t *)(v8 - 0x5ffff2f8) = v11;
    uint32_t v12 = (*(int32_t*)0xa0000cf8 + 1) % 0x1000; // 0x1d013978
    if (*(int32_t*)0xa0000cf4 % 0x1000 != v12) {
        // 0x1d01398c
        *(int32_t*)0xa0000cf8 = v12;
    }
    // 0x1d013990
    return function_1d0149f0(v1);
}

// Address range: 0x1d0149f0 - 0x1d014a80
int32_t function_1d0149f0(int32_t a1) {
    int32_t v1 = function_1d01ac1c(1, 1); // 0x1d014a08
    int32_t result = 0; // 0x1d014a0c
    if (v1 != 0) {
        // 0x1d014a14
        __asm_lwl(*(int32_t *)(a1 + 3));
        int32_t v2 = __asm_lwr(1); // 0x1d014a18
        __asm_lwl(*(int32_t *)(a1 + 7));
        int32_t v3 = __asm_lwr(*(int32_t *)(a1 + 4)); // 0x1d014a20
        __asm_lwl(*(int32_t *)(a1 + 11));
        int32_t v4 = __asm_lwr(*(int32_t *)(a1 + 8)); // 0x1d014a28
        __asm_lwl(*(int32_t *)(a1 + 15));
        int32_t v5 = __asm_lwr(*(int32_t *)(a1 + 12)); // 0x1d014a30
        __asm_swl(v2, *(int32_t *)(v1 + 3));
        __asm_swr(v2, *(int32_t *)v1);
        __asm_swl(v3, *(int32_t *)(v1 + 7));
        __asm_swr(v3, *(int32_t *)(v1 + 4));
        __asm_swl(v4, *(int32_t *)(v1 + 11));
        __asm_swr(v4, *(int32_t *)(v1 + 8));
        __asm_swl(v5, *(int32_t *)(v1 + 15));
        __asm_swr(v5, *(int32_t *)(v1 + 12));
        function_1d01ae6c(1, 1);
        function_1d01ae98(1, 1);
        result = 1;
    }
    // 0x1d014a70
    return result;
}

// Address range: 0x1d014a80 - 0x1d014b10
int32_t function_1d014a80(int32_t * a1) {
    int32_t v1 = function_1d01ac1c(1, 2); // 0x1d014a98
    int32_t result = 0; // 0x1d014a9c
    if (v1 != 0) {
        int32_t v2 = (int32_t)a1;
        __asm_lwl(*(int32_t *)(v2 + 3));
        int32_t v3 = __asm_lwr(1); // 0x1d014aa8
        __asm_lwl(*(int32_t *)(v2 + 7));
        int32_t v4 = __asm_lwr(*(int32_t *)(v2 + 4)); // 0x1d014ab0
        __asm_lwl(*(int32_t *)(v2 + 11));
        int32_t v5 = __asm_lwr(*(int32_t *)(v2 + 8)); // 0x1d014ab8
        __asm_lwl(*(int32_t *)(v2 + 15));
        int32_t v6 = __asm_lwr(*(int32_t *)(v2 + 12)); // 0x1d014ac0
        __asm_swl(v3, *(int32_t *)(v1 + 3));
        __asm_swr(v3, *(int32_t *)v1);
        __asm_swl(v4, *(int32_t *)(v1 + 7));
        __asm_swr(v4, *(int32_t *)(v1 + 4));
        __asm_swl(v5, *(int32_t *)(v1 + 11));
        __asm_swr(v5, *(int32_t *)(v1 + 8));
        __asm_swl(v6, *(int32_t *)(v1 + 15));
        __asm_swr(v6, *(int32_t *)(v1 + 12));
        function_1d01ae6c(1, 2);
        function_1d01ae98(1, 2);
        result = 1;
    }
    // 0x1d014b00
    return result;
}

// Address range: 0x1d014d08 - 0x1d014dbc
int32_t function_1d014d08(int32_t * a1) {
    int32_t result = function_1d010294(3); // 0x1d014d20
    if (result == 0 || (function_1d0107dc(3) & 4) != 0) {
        // 0x1d014da8
        return 0;
    }
    int32_t v1 = (int32_t)a1;
    int32_t * v2 = (int32_t *)(v1 + 4); // 0x1d014d44
    uint32_t v3 = *v2; // 0x1d014d44
    int32_t v4 = __asm_ext(v3, 28, 1); // 0x1d014d48
    int32_t v5 = 3; // 0x1d014d50
    if (v4 != 0) {
        // 0x1d014d54
        v5 = __asm_ext(*v2, 10, 18) | 0xc0000;
    }
    // 0x1d014d78
    function_1d011184(3, 0, v5, v4, v1 + 8, v3 % 16);
    function_1d010df4(3, 0);
    // 0x1d014da8
    return result;
}

// Address range: 0x1d014fe0 - 0x1d015094
int32_t function_1d014fe0(int32_t * a1) {
    int32_t result = function_1d010294(2); // 0x1d014ff8
    if (result == 0 || (function_1d0107dc(2) & 4) != 0) {
        // 0x1d015080
        return 0;
    }
    int32_t v1 = (int32_t)a1;
    int32_t * v2 = (int32_t *)(v1 + 4); // 0x1d01501c
    uint32_t v3 = *v2; // 0x1d01501c
    int32_t v4 = __asm_ext(v3, 28, 1); // 0x1d015020
    int32_t v5 = 2; // 0x1d015028
    if (v4 != 0) {
        // 0x1d01502c
        v5 = __asm_ext(*v2, 10, 18) | 0x80000;
    }
    // 0x1d015050
    function_1d011184(2, 0, v5, v4, v1 + 8, v3 % 16);
    function_1d010df4(2, 0);
    // 0x1d015080
    return result;
}

// Address range: 0x1d015dbc - 0x1d015f54
int32_t function_1d015dbc(int32_t * a1) {
    int32_t v1 = (int32_t)a1 + 4; // 0x1d015dd4
    uint16_t v2 = *(int16_t *)v1; // 0x1d015dd4
    int32_t v3; // 0x1d015dbc
    *(int32_t *)(v3 - 0x7fac) = (int32_t)v2;
    *(int32_t *)(v3 - 0x7fa8) = 100;
    int32_t v4 = *(int32_t *)v1; // 0x1d015de4
    int32_t v5 = __asm_ext(v4, 24, 1); // 0x1d015de8
    int32_t v6 = __asm_ext(v4, 25, 1); // 0x1d015df0
    uint32_t v7 = __asm_ext(v4, 27, 1); // 0x1d015df8
    if (*(int32_t*)0xa0013544 == 0) {
        goto lab_0x1d015f1c;
    } else {
        if (v7 % 256 == 0) {
            goto lab_0x1d015e5c;
        } else {
            // 0x1d015e20
            if (*(char*)0xa001354b == 0) {
                // 0x1d015e30
                *(char*)0xa0013539 = 1;
                int32_t * v8 = (int32_t *)(v3 - 0x7fb8); // 0x1d015e3c
                if (*v8 == 0) {
                    // 0x1d015e48
                    *v8 = 1;
                    *(int32_t *)(v3 - 0x7fbc) = 3;
                }
                goto lab_0x1d015f1c;
            } else {
                goto lab_0x1d015e5c;
            }
        }
    }
  lab_0x1d015f1c:
    // 0x1d015f1c
    *(int32_t*)0xa0013544 = 100;
    *(char*)0xa0013548 = (char)v5;
    *(char*)0xa0013549 = (char)v6;
    *(char*)0xa001354a = 0;
    *(char*)0xa001354b = (char)v7;
    *(char*)0xa001354c = (char)((v4 & 0x74000000) != 0);
    return -0x5ffecaf8;
  lab_0x1d015e5c:
    // 0x1d015e5c
    if (*(char*)0xa0013538 != 0) {
        // 0x1d015e68
        if (*(char*)0xa0013548 != 0) {
            if ((v6 | v5) % 256 == 0) {
                // 0x1d015e88
                if (*(char*)0xa0013519 == 0) {
                    // 0x1d015e98
                    if (*(char*)0xa0013531 == 0) {
                        // 0x1d015ea8
                        if (*(char*)0xa0013549 == 0) {
                            char v9 = *(char *)(v3 - 0x7fb4); // 0x1d015ec0
                            if (v2 == 0 != (*(int32_t *)(v3 - 0x7fb0) == 0 || v9 == 1)) {
                                // 0x1d015ed8
                                if (function_1d01aacc(v9) == 0) {
                                    // 0x1d015ee8
                                    *(char*)0xa0013539 = 1;
                                    *(char *)(v3 - 0x7fe8) = 0;
                                    int32_t * v10 = (int32_t *)(v3 - 0x7fb8); // 0x1d015ef8
                                    if (*v10 == 0) {
                                        // 0x1d015f04
                                        *v10 = 1;
                                        *(int32_t *)(v3 - 0x7fbc) = 13;
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    goto lab_0x1d015f1c;
}

// Address range: 0x1d015fac - 0x1d015fb4
int32_t exit(void) {
    // 0x1d015fac
    int32_t v1; // 0x1d015fac
    return *(int32_t *)(v1 - 0x7fb8);
}

// Address range: 0x1d015fd8 - 0x1d015ff0
int32_t function_1d015fd8(void) {
    // 0x1d015fd8
    int32_t v1; // 0x1d015fd8
    int32_t v2 = *(int32_t *)(v1 - 0x7fb8); // 0x1d015fdc
    return v2 == 1 ? (int32_t)*(char *)(v1 - 0x7fe8) : 0;
}

// Address range: 0x1d0172f0 - 0x1d017304
int32_t function_1d0172f0(void) {
    // 0x1d0172f0
    return (int32_t)*(char*)0xa00001be;
}

// Address range: 0x1d019370 - 0x1d019508
int32_t pthread_cond_destroy3(void) {
    // 0x1d019370
    int32_t v1; // 0x1d019370
    char * v2 = (char *)(v1 - 0x7f10); // 0x1d019370
    if (*v2 % 32 != 1) {
        // 0x1d019500
        return 1;
    }
    char result = *(char *)(v1 - 0x7f0c); // 0x1d019384
    if (result != 0) {
        // 0x1d019500
        return result;
    }
    char * v3 = (char *)(v1 - 0x7f0f); // 0x1d019394
    if (*v3 == 6) {
        // 0x1d0193a8
        switch (*(char *)(v1 - 0x7f0d)) {
            case 33: {
                // 0x1d0193cc
                if (*(char *)(v1 - 0x7f20) == 1) {
                    // 0x1d0193e0
                    *(int32_t*)0xa0000480 = -0x62fe60d2;
                    *(int16_t *)-0x5ffffb78 = 9;
                    *(char*)0xa0000484 = -64;
                }
                // break -> 0x1d019428
                break;
            }
            case 34: {
                // 0x1d019408
                *(int32_t*)0xa0000480 = -0x62fe6128;
                *(int16_t *)-0x5ffffb78 = 29;
                *(char*)0xa0000484 = -64;
                // break -> 0x1d019428
                break;
            }
        }
    }
    // 0x1d019428
    if ((*v2 & 96) != 32) {
        // 0x1d019500
        return 32;
    }
    unsigned char result4 = *v3; // 0x1d01943c
    if (result4 == 3) {
        // 0x1d0194c4
        *(int32_t*)0xa0000480 = v1 - 0x7ecf;
        *(int16_t *)-0x5ffffb78 = 1;
        *(char*)0xa0000484 = -127;
        return -0x5ffffb80;
    }
    if (result4 < 4) {
        // 0x1d019458
        if (result4 != 2) {
            // 0x1d019464
            return -0x60000000;
        }
        // 0x1d019484
        *(int32_t*)0xa0000480 = v1 - 0x7ed0;
        *(int16_t *)-0x5ffffb78 = 1;
        *(char*)0xa0000484 = -63;
        return -0x5ffffb80;
    }
    // 0x1d01946c
    switch (result4) {
        case 10: {
            // 0x1d0194a8
            *(char*)0xa0000484 = -128;
            unsigned char result2 = *(char *)(v1 - 0x7f0d); // 0x1d0194b8
            *(char *)(v1 - 0x7ed0) = result2;
            return result2;
        }
        case 11: {
            // 0x1d0194ec
            *(char*)0xa0000484 = -128;
            char result3 = *(char *)(v1 - 0x7f0e); // 0x1d0194f8
            *(char *)(v1 - 0x7ecf) = result3;
            // 0x1d019500
            return result3;
        }
    }
    // 0x1d019464
    return result4;
}

// Address range: 0x1d01aacc - 0x1d01aad8
int32_t function_1d01aacc(char a1) {
    // 0x1d01aacc
    return (int32_t)*(char*)0x9d017978;
}

// Address range: 0x1d01ac1c - 0x1d01ac60
int32_t function_1d01ac1c(int32_t a1, int32_t a2) {
    int32_t v1 = *(int32_t *)(4 * a1 - 0x5ffeccc8) + 64 * a2; // 0x1d01ac34
    if (__asm_ext(*(int32_t *)(v1 + 864), 10, 1) == 0) {
        // 0x1d01ac58
        return 0;
    }
    // 0x1d01ac48
    return *(int32_t *)(v1 + 880) | -0x60000000;
}

// Address range: 0x1d01ae6c - 0x1d01ae98
int32_t function_1d01ae6c(int32_t a1, int32_t a2) {
    int32_t result = *(int32_t *)(4 * a1 - 0x5ffeccc8) + 64 * a2; // 0x1d01ae84
    *(int32_t *)(result + 856) = 0x2000;
    return result;
}

// Address range: 0x1d01ae98 - 0x1d01aec4
int32_t function_1d01ae98(int32_t a1, int32_t a2) {
    int32_t result = *(int32_t *)(4 * a1 - 0x5ffeccc8) + 64 * a2; // 0x1d01aeb0
    *(int32_t *)(result + 856) = 8;
    return result;
}

// Address range: 0x1d01b0b4 - 0x1d01b0bc
int32_t exit3(void) {
    // 0x1d01b0b4
    int32_t result; // 0x1d01b0b4
    __asm_di(result);
    return result;
}

// --------------------- Meta-Information ---------------------

// Detected functions: 25
