//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int32_t exit(void);
int32_t exit2(void);
int32_t exit3(void);
int32_t function_1d008600(void);
int32_t function_1d008ef8(int32_t * a1);
int32_t function_1d010600(int32_t a1);
int32_t function_1d010b48(int32_t a1);
int32_t function_1d011160(int32_t a1, uint32_t a2);
int32_t function_1d0114f0(int32_t a1, int32_t a2, uint32_t a3, int32_t a4, int32_t a5, uint32_t a6);
int32_t function_1d0134d0(int32_t * a1);
int32_t function_1d015058(void);
int32_t function_1d015d50(int32_t a1);
int32_t function_1d015de0(int32_t * a1);
int32_t function_1d016084(int32_t * a1);
int32_t function_1d016378(int32_t * a1);
int32_t function_1d01704c(int32_t * a1);
int32_t function_1d01728c(void);
int32_t function_1d018500(void);
int32_t function_1d01bfa0(int32_t a1, int32_t a2);
int32_t function_1d01c1f0(int32_t a1, int32_t a2);
int32_t function_1d01c21c(int32_t a1, int32_t a2);
int32_t pthread_cond_destroy(int32_t * a1);
int32_t pthread_cond_destroy2(int32_t * a1);
int32_t pthread_cond_destroy3(void);
int32_t time(int32_t a1);

// ------------------------ Functions -------------------------

// Address range: 0x1d008600 - 0x1d00869c
int32_t function_1d008600(void) {
    // 0x1d008600
    if (*(int32_t*)0xa0013290 < 101) {
        // 0x1d008694
        return 8;
    }
    int32_t v1 = 938; // bp-24, 0x1d008624
    if (*(int32_t*)0xa0013310 < 3) {
        // 0x1d008660
        __asm_ins(2, 4, 4);
    } else {
        // 0x1d00863c
        __asm_ins(15, 4, 4);
    }
    // 0x1d008674
    __asm_ins(1, 15, 1);
    // 0x1d008694
    return pthread_cond_destroy2(&v1);
}

// Address range: 0x1d008ef8 - 0x1d0091a8
int32_t function_1d008ef8(int32_t * a1) {
    int32_t v1 = (int32_t)a1;
    *(char *)a1 = 0;
    *(char *)(v1 + 1) = 0;
    int32_t v2 = v1 + 2; // 0x1d008f0c
    *(char *)v2 = 0;
    *(char *)(v1 + 3) = 0;
    int32_t v3 = v1 + 4; // 0x1d008f14
    *(char *)v3 = 0;
    *(char *)(v1 + 5) = 0;
    char * v4 = (char *)(v1 + 6); // 0x1d008f1c
    *v4 = 0;
    char * v5 = (char *)(v1 + 7); // 0x1d008f20
    *v5 = 0;
    *(int16_t *)a1 = (int16_t)*(int32_t*)0xa00135d4;
    int32_t v6 = *(int32_t*)0xa00135d0; // 0x1d008f34
    *(int16_t *)v2 = (int16_t)((int32_t)(0x51eb851f * (int64_t)v6 / 0x2000000000) - (v6 >> 31));
    int32_t v7; // 0x1d008ef8
    int32_t v8; // 0x1d008ef8
    if (*(int32_t*)0xa00131b8 < 4) {
        // 0x1d009048
        v8 = 0;
        goto lab_0x1d009050;
    } else {
        int32_t v9 = *(int32_t*)0xa00131d8; // 0x1d008f70
        v7 = v9;
        if (v9 >= 4) {
            // 0x1d009118
            v7 = v9;
            if (*(int32_t*)0xa0013104 >= 4) {
                // 0x1d008f88
                v7 = v9;
                if (*(int32_t*)0xa00130b4 >= 4) {
                    unsigned char v10 = *(char*)0xa00130ae; // 0x1d009134
                    unsigned char v11 = *(char*)0xa00130af; // 0x1d00913c
                    *(int16_t *)v3 = 256 * (int16_t)v10 | (int16_t)v11;
                    *v4 = *(char*)0xa00131ac ^ -128;
                    v8 = 0;
                    if (*(int32_t*)0xa00131b8 >= 4) {
                        // 0x1d009130
                        v7 = *(int32_t*)0xa00131d8;
                        goto lab_0x1d008f9c;
                    } else {
                        goto lab_0x1d009050;
                    }
                } else {
                    goto lab_0x1d008f9c;
                }
            } else {
                goto lab_0x1d008f9c;
            }
        } else {
            goto lab_0x1d008f9c;
        }
    }
  lab_0x1d009050:
    // 0x1d009050
    __asm_ins(v8, 0, 1);
    *v5 = (char)__asm_ins((int32_t)*(char*)0xa001356e, 1, 1);
    *v5 = (char)__asm_ins(function_1d018500(), 2, 1);
    *v5 = (char)__asm_ins((int32_t)(exit() != 0), 3, 1);
    int32_t v12 = 1; // 0x1d009098
    if (*(int32_t*)0xa0013104 >= 4) {
        // 0x1d00909c
        v12 = *(int32_t*)0xa00130b4 < 4;
    }
    // 0x1d0090ac
    *v5 = (char)__asm_ins(v12, 4, 1);
    int32_t v13 = 1; // 0x1d0090cc
    if (*(int32_t*)0xa00131b8 >= 4) {
        // 0x1d0090d0
        v13 = *(int32_t*)0xa00131d8 < 4;
    }
    // 0x1d0090e0
    *v5 = (char)__asm_ins(v13, 5, 1);
    *v5 = (char)__asm_ins((int32_t)*(char*)0xa001356f, 6, 1);
    int32_t result = __asm_ins((int32_t)(*(int32_t*)0xa0013228 == 0), 7, 1); // 0x1d00910c
    *v5 = (char)result;
    return result;
  lab_0x1d008f9c:
    // 0x1d008f9c
    v8 = 0;
    if (v7 >= 4) {
        // 0x1d00916c
        v8 = 0;
        if (*(int32_t*)0xa0013104 >= 4) {
            // 0x1d008fb4
            v8 = 0;
            if (*(int32_t*)0xa00130b4 >= 4) {
                // 0x1d009184
                v8 = 0;
                if (*(int32_t*)0xa0013228 == 0) {
                    goto lab_0x1d009050;
                } else {
                    // 0x1d008fcc
                    v8 = 0;
                    if (__asm_ext(*(int32_t*)0xa0013220, 16, 1) == 0) {
                        goto lab_0x1d009050;
                    } else {
                        // 0x1d008fdc
                        v8 = 0;
                        if (*(char*)0xa001356e == 0) {
                            // 0x1d008fec
                            v8 = 0;
                            if (*(char*)0xa001356f == 0) {
                                // 0x1d008ffc
                                if (exit() == 0) {
                                    goto lab_0x1d00901c;
                                } else {
                                    // 0x1d00900c
                                    v8 = 0;
                                    if (function_1d01728c() == 0) {
                                        goto lab_0x1d009050;
                                    } else {
                                        goto lab_0x1d00901c;
                                    }
                                }
                            } else {
                                goto lab_0x1d009050;
                            }
                        } else {
                            goto lab_0x1d009050;
                        }
                    }
                }
            } else {
                goto lab_0x1d009050;
            }
        } else {
            goto lab_0x1d009050;
        }
    } else {
        goto lab_0x1d009050;
    }
  lab_0x1d00901c:
    // 0x1d00901c
    v8 = 0;
    if (function_1d018500() == 0) {
        // 0x1d00902c
        v8 = 1;
        if ((*(int32_t*)0xa00131ac & 0xc00000) == 0x800000) {
            goto lab_0x1d009050;
        } else {
            // 0x1d009048
            v8 = 0;
            goto lab_0x1d009050;
        }
    } else {
        goto lab_0x1d009050;
    }
}

// Address range: 0x1d0091a8 - 0x1d0092dc
int32_t time(int32_t a1) {
    // 0x1d0091a8
    int32_t v1; // bp-16, 0x1d0091a8
    int32_t v2; // bp-24, 0x1d0091a8
    if (*(char*)0xa001356d == 0) {
        // 0x1d00923c
        if (a1 != 0) {
            // 0x1d0092d4
            return -0x5fff0000;
        }
    } else {
        int32_t v3 = 0; // 0x1d0091c8
        if (*(int32_t*)0xa0013100 != 0) {
            // 0x1d0091cc
            v3 = __asm_ins(0, 23, 1);
        }
        // 0x1d0091f0
        v1 = v3;
        v2 = 936;
        if (a1 != 0) {
            // 0x1d009204
            *(int32_t*)0xbf8860e8 = 32;
            // 0x1d0092d4
            return function_1d015de0(&v2);
        }
        // 0x1d009220
        pthread_cond_destroy(&v2);
        *(int32_t*)0xbf8860e4 = 32;
    }
    // 0x1d009244
    if (*(int32_t*)0xa0013568 == 0) {
        // 0x1d009250
        v2 = 101;
        function_1d008ef8(&v1);
        function_1d01704c(&v1);
        function_1d0134d0(&v2);
    }
    // 0x1d00927c
    if (*(int32_t*)0xa00131f8 != 0) {
        // 0x1d009288
        if (__asm_ext(*(int32_t*)0xa00131f4, 24, 1) != 0) {
            // 0x1d0092d4
            return function_1d008600();
        }
    }
    // 0x1d00929c
    if (*(int32_t*)0xa0013218 != 0) {
        // 0x1d0092a8
        if (__asm_ext(*(int32_t*)0xa0013214, 24, 1) != 0) {
            // 0x1d0092d4
            return function_1d008600();
        }
    }
    // 0x1d0092bc
    if (*(char*)0xa001356d == 0) {
        // 0x1d0092d4
        return 0;
    }
    // 0x1d0092d4
    return function_1d008600();
}

// Address range: 0x1d00e89c - 0x1d00eac4
int32_t exit2(void) {
    // 0x1d00e89c
    *(int32_t*)0xbf881074 = 0x2000000;
    *(int32_t*)0xbf885220 = 255;
    *(int32_t*)0xbf885200 = 255;
    *(int32_t*)0xbf885300 = 0;
    *(int32_t*)0xbf885310 = 0;
    *(int32_t*)0xbf885320 = 0;
    *(int32_t*)0xbf885330 = 0;
    *(int32_t*)0xbf8852e0 = 0;
    *(int32_t*)0xbf885230 = 159;
    *(int32_t*)0xbf885210 = 159;
    *(int32_t*)0xbf885070 = *(int32_t*)0xbf885070 % 16;
    *(char*)0xbf885080 = (char)__asm_ins(1, 0, 1);
    uint32_t v1 = __asm_ext(-0x5ffffc00, 0, 29); // 0x1d00e928
    *(int32_t*)0xbf8852d0 = v1 / 0x1000000;
    *(int32_t*)0xbf8852c0 = v1 / 0x10000;
    *(int32_t*)0xbf885270 = v1 / 256;
    int32_t v2 = 0; // 0x1d00e960
    int32_t v3 = 0; // 0x1d00e960
    *(int32_t *)(v2 - 0x5ffffc00) = 0;
    *(int32_t *)(v2 - 0x5ffffbfc) = 0;
    v3++;
    v2 = 8 * v3;
    while (v3 != 16) {
        // 0x1d00e964
        *(int32_t *)(v2 - 0x5ffffc00) = 0;
        *(int32_t *)(v2 - 0x5ffffbfc) = 0;
        v3++;
        v2 = 8 * v3;
    }
    // 0x1d00e984
    *(char*)0xbf885250 = (char)__asm_ins(1, 1, 1);
    *(int32_t*)0xbf885260 = 0;
    *(char*)0xbf885250 = (char)__asm_ins(0, 5, 1);
    *(char*)0xbf885250 = (char)__asm_ins(0, 1, 1);
    if ((*(int32_t*)0xbf885200 & 8) != 0) {
        *(int32_t*)0xbf885200 = 8;
        *(char*)0xa0000484 = 0;
        *(char*)0xa00004d4 = 0;
        *(int32_t*)0xa00004d4 = __asm_ins(0, 8, 16);
        while ((*(int32_t*)0xbf885200 & 8) != 0) {
            // 0x1d00e9dc
            *(int32_t*)0xbf885200 = 8;
            *(char*)0xa0000484 = 0;
            *(char*)0xa00004d4 = 0;
            *(int32_t*)0xa00004d4 = __asm_ins(0, 8, 16);
        }
    }
    // 0x1d00ea0c
    int32_t v4; // 0x1d00e89c
    *(int32_t *)(v4 - 0x7f2c) = 1;
    *(int32_t *)(v4 - 0x7f24) = 1;
    *(int32_t *)(v4 - 0x7ef4) = 0;
    *(int32_t *)(v4 - 0x7ef0) = 0;
    *(int32_t *)(v4 - 0x7f10) = 0;
    int32_t v5 = -0x5ffffe00; // 0x1d00ea40
    int32_t v6 = -0x5ffffdf0; // 0x1d00ea40
    int32_t v7 = 0; // 0x1d00ea40
    *(int32_t *)v6 = 0;
    *(int32_t *)v5 = 0;
    int32_t v8 = v7 + v4;
    *(char *)(v8 - 0x7edc) = 0;
    *(char *)(v8 - 0x7f0c) = 0;
    v7++;
    v5 += 4;
    v6 += 4;
    while (v7 != 4) {
        // 0x1d00ea44
        *(int32_t *)v6 = 0;
        *(int32_t *)v5 = 0;
        v8 = v7 + v4;
        *(char *)(v8 - 0x7edc) = 0;
        *(char *)(v8 - 0x7f0c) = 0;
        v7++;
        v5 += 4;
        v6 += 4;
    }
    // 0x1d00ea6c
    *(int32_t*)0xa0000210 = -0x5ffffbf0;
    *(int32_t*)0xbf885300 = 13;
    *(int32_t*)0xa0000404 = __asm_ext(v4 - 0x7f18, 0, 29);
    *(int16_t *)-0x5ffffbfe = (int16_t)__asm_ins(64, 0, 10);
    *(int16_t *)-0x5ffffc00 = 132;
    *(char *)(v4 - 0x7f28) = 0;
    *(int32_t *)(v4 - 0x7eec) = 0;
    return 132;
}

// Address range: 0x1d010600 - 0x1d010610
int32_t function_1d010600(int32_t a1) {
    // 0x1d010600
    int32_t v1; // 0x1d010600
    return (int32_t)*(char *)(a1 - 0x7f44 + v1);
}

// Address range: 0x1d010b48 - 0x1d010d7c
int32_t function_1d010b48(int32_t a1) {
    switch (a1) {
        case 3: {
            // 0x1d010b80
            *(int32_t*)0xbf8860e4 = 512;
            *(int32_t*)0xbf8860c4 = 512;
            *(int32_t*)0xbf805820 = 160;
            while ((*(int32_t*)0xbf805810 & 0x1f000000) == 0) {
                // continue -> 0x1d010c14
            }
            // 0x1d010ca8
            *(int32_t*)0xbf805820 = 0;
            while ((*(int32_t*)0xbf805810 & 0x1f000000) == 0) {
                // continue -> 0x1d010cb4
            }
            // 0x1d010cc4
            *(int32_t*)0xbf8860e8 = 512;
            *(int32_t*)0xbf8860c4 = 512;
            return 0;
        }
        case 4: {
            // 0x1d010b9c
            *(int32_t*)0xbf886064 = 256;
            *(int32_t*)0xbf886044 = 256;
            *(int32_t*)0xbf805c20 = 160;
            while ((*(int32_t*)0xbf805c10 & 0x1f000000) == 0) {
                // continue -> 0x1d010c44
            }
            // 0x1d010cd4
            *(int32_t*)0xbf805c20 = 0;
            while ((*(int32_t*)0xbf805c10 & 0x1f000000) == 0) {
                // continue -> 0x1d010ce0
            }
            // 0x1d010cf0
            *(int32_t*)0xbf886068 = 256;
            *(int32_t*)0xbf886044 = 256;
            return 0;
        }
        case 2: {
            // 0x1d010b64
            *(int32_t*)0xbf8861a4 = 512;
            *(int32_t*)0xbf886184 = 512;
            *(int32_t*)0xbf805a20 = 160;
            while ((*(int32_t*)0xbf805a10 & 0x1f000000) == 0) {
                // continue -> 0x1d010be4
            }
            // 0x1d010c7c
            *(int32_t*)0xbf805a20 = 0;
            while ((*(int32_t*)0xbf805a10 & 0x1f000000) == 0) {
                // continue -> 0x1d010c88
            }
            // 0x1d010c98
            *(int32_t*)0xbf8861a8 = 512;
            *(int32_t*)0xbf886184 = 512;
            return 0;
        }
    }
    // 0x1d010d74
    return 0;
}

// Address range: 0x1d011160 - 0x1d011318
int32_t function_1d011160(int32_t a1, uint32_t a2) {
    switch (a1) {
        case 3: {
            // 0x1d0111b0
            *(int32_t*)0xbf8860e4 = 512;
            *(int32_t*)0xbf8860c4 = 512;
            *(int32_t*)0xbf805820 = (1 << a2 % 4) % 128 | 128;
            while ((*(int32_t*)0xbf805810 & 0x1f000000) == 0) {
                // continue -> 0x1d011268
            }
            // 0x1d0112e4
            *(int32_t*)0xbf8860e8 = 512;
            *(int32_t*)0xbf8860c4 = 512;
            return 512;
        }
        case 4: {
            // 0x1d0111d8
            *(int32_t*)0xbf886064 = 256;
            *(int32_t*)0xbf886044 = 256;
            *(int32_t*)0xbf805c20 = (1 << a2 % 4) % 128 | 128;
            while ((*(int32_t*)0xbf805c10 & 0x1f000000) == 0) {
                // continue -> 0x1d011294
            }
            // 0x1d011300
            *(int32_t*)0xbf886068 = 256;
            *(int32_t*)0xbf886044 = 256;
            return 256;
        }
        case 2: {
            // 0x1d011184
            *(int32_t*)0xbf8861a4 = 512;
            *(int32_t*)0xbf886184 = 512;
            *(int32_t*)0xbf805a20 = (1 << a2 % 4) % 128 | 128;
            while ((*(int32_t*)0xbf805a10 & 0x1f000000) == 0) {
                // continue -> 0x1d01123c
            }
            // 0x1d0112c8
            *(int32_t*)0xbf8861a8 = 512;
            *(int32_t*)0xbf886184 = 512;
            // 0x1d0112d8
            return 512;
        }
    }
    // 0x1d0112d8
    return 512;
}

// Address range: 0x1d0114f0 - 0x1d0117cc
int32_t function_1d0114f0(int32_t a1, int32_t a2, uint32_t a3, int32_t a4, int32_t a5, uint32_t a6) {
    switch (a1) {
        case 3: {
            // 0x1d011548
            *(int32_t*)0xbf8860e4 = 512;
            *(int32_t*)0xbf8860c4 = 512;
            // break -> 0x1d01157c
            break;
        }
        case 4: {
            // 0x1d011564
            *(int32_t*)0xbf886064 = 256;
            *(int32_t*)0xbf886044 = 256;
            // break -> 0x1d01157c
            break;
        }
        case 2: {
            // 0x1d01152c
            *(int32_t*)0xbf8861a4 = 512;
            *(int32_t*)0xbf886184 = 512;
            // break -> 0x1d01157c
            break;
        }
    }
    char v1; // bp-7, 0x1d0114f0
    if (a4 == 0) {
        // 0x1d0115bc
        v1 = a3 / 8;
    } else {
        // 0x1d01158c
        v1 = a3 / 0x200000;
        __asm_ins(0, 0, 5);
        __asm_ext(a3, 16, 2);
    }
    int32_t * v2 = (int32_t*)0xbf805a20; // 0x1d0114f0
    int32_t * v3 = (int32_t*)0xbf805a10; // 0x1d0114f0
    int32_t result = 2; // 0x1d0114f0
    switch (a1) {
        case 3: {
            // 0x1d01161c
            v2 = (int32_t*)0xbf805820;
            v3 = (int32_t*)0xbf805810;
            goto lab_0x1d01162c;
        }
        case 4: {
            // 0x1d011608
            v2 = (int32_t*)0xbf805c20;
            v3 = (int32_t*)0xbf805c10;
            goto lab_0x1d01162c;
        }
        case 2: {
            goto lab_0x1d01162c;
        }
        default: {
            return result;
        }
    }
  lab_0x1d01162c:;
    uint32_t v4 = a6 % 256; // 0x1d0114f4
    int32_t v5 = v4 < 8 ? v4 : 8;
    int32_t v6 = &v1;
    *v2 = (int32_t)*(char *)(v6 - 1);
    int32_t v7 = v6 + 1; // 0x1d011640
    int32_t v8; // bp-2, 0x1d0114f0
    while (v6 != (int32_t)&v8) {
        // 0x1d011638
        v6 = v7;
        *v2 = (int32_t)*(char *)(v6 - 1);
        v7 = v6 + 1;
    }
    // 0x1d011650
    while ((*v3 & 0x1e000000) < 0x6000000) {
        // continue -> 0x1d011650
    }
    int32_t * v9 = (int32_t*)0xbf805a20; // 0x1d0114f0
    int32_t * v10 = (int32_t*)0xbf805a10; // 0x1d0114f0
    result = 2;
    switch (a1) {
        case 3: {
            // 0x1d0116c4
            v9 = (int32_t*)0xbf805820;
            v10 = (int32_t*)0xbf805810;
            goto lab_0x1d0116d4;
        }
        case 4: {
            // 0x1d0116b0
            v9 = (int32_t*)0xbf805c20;
            v10 = (int32_t*)0xbf805c10;
            goto lab_0x1d0116d4;
        }
        case 2: {
            goto lab_0x1d0116d4;
        }
        default: {
            return result;
        }
    }
  lab_0x1d0116d4:
    // 0x1d0116d4
    if (a5 == 0) {
        if (v5 != 0) {
            // 0x1d011710
            *v9 = 0;
        }
    } else {
        // 0x1d0116ec
        if (v5 != 0) {
            int32_t v11 = a5 + 1;
            *v9 = (int32_t)*(char *)a5;
            int32_t v12 = v11; // 0x1d011704
            while (v11 != v5 + a5) {
                // 0x1d0116f8
                v11 = v12 + 1;
                *v9 = (int32_t)*(char *)v12;
                v12 = v11;
            }
        }
    }
    // 0x1d011724
    while ((*v10 & 0x1f000000) < 0x1000000 * v5) {
        // continue -> 0x1d011728
    }
    // 0x1d01175c
    result = 2;
    switch (a1) {
        case 3: {
            // 0x1d011790
            *(int32_t*)0xbf8860e8 = 512;
            *(int32_t*)0xbf8860c4 = 512;
            result = 512;
            // break -> 0x1d0117c4
            break;
        }
        case 4: {
            // 0x1d0117ac
            *(int32_t*)0xbf886068 = 256;
            *(int32_t*)0xbf886044 = 256;
            result = 256;
            // break -> 0x1d0117c4
            break;
        }
        case 2: {
            // 0x1d011774
            *(int32_t*)0xbf8861a8 = 512;
            *(int32_t*)0xbf886184 = 512;
            result = 512;
            // break -> 0x1d0117c4
            break;
        }
    }
    // 0x1d0117c4
    return result;
}

// Address range: 0x1d0134d0 - 0x1d013760
int32_t function_1d0134d0(int32_t * a1) {
    int32_t v1 = (int32_t)a1;
    int32_t v2; // 0x1d0134d0
    if ((*(int32_t *)(v2 - 0x7f3c) & 32) != 0) {
        int32_t v3 = *(int32_t*)0xa0000cf8; // 0x1d0134f8
        uint32_t v4 = *(int32_t*)0xa0000cf4; // 0x1d013500
        uint32_t v5 = v4 % 0x1000; // 0x1d013504
        if (v5 != (v3 + 1) % 0x1000) {
            int32_t * v6 = (int32_t *)(v1 + 4); // 0x1d013528
            uint32_t v7 = *v6; // 0x1d013528
            int32_t v8 = __asm_ext(v7, 28, 1); // 0x1d01352c
            int32_t v9; // 0x1d0134d0
            if (v8 == 0) {
                // 0x1d013554
                v9 = v4 % 2048;
            } else {
                // 0x1d013538
                v9 = __asm_ext(*v6, 10, 18) | 0x40000 * v5 & 0x1ffc0000;
            }
            int32_t v10 = 16 * v3 & 0xfff0; // 0x1d013514
            uint32_t v11 = v7 % 16; // 0x1d013534
            __asm_ins(v9, 0, 29);
            __asm_ins(v8, 29, 1);
            __asm_ins(v11, 30, 2);
            *(int32_t *)(v10 - 0x5ffff300) = __asm_ins(v11 / 4, 30, 2);
            __asm_ins(5, 27, 3);
            *(int32_t *)(v10 - 0x5ffff304) = __asm_ins(*(int32_t *)(v2 - 0x7f38), 0, 27);
            __asm_lwl(*(int32_t *)(v1 + 11));
            int32_t v12 = __asm_lwr(*(int32_t *)(v1 + 8)); // 0x1d013598
            __asm_lwl(*(int32_t *)(v1 + 15));
            int32_t v13 = __asm_lwr(*(int32_t *)(v1 + 12)); // 0x1d0135a0
            *(int32_t *)(v10 - 0x5ffff2fc) = v12;
            *(int32_t *)(v10 - 0x5ffff2f8) = v13;
            uint32_t v14 = (*(int32_t*)0xa0000cf8 + 1) % 0x1000; // 0x1d0135bc
            if (*(int32_t*)0xa0000cf4 % 0x1000 != v14) {
                // 0x1d0135d0
                *(int32_t*)0xa0000cf8 = v14;
            }
        }
    }
    int32_t v15 = *(int32_t*)0xa00008e8 % 64; // 0x1d013674
    int32_t result2; // 0x1d0134d0
    if (v15 == *(int32_t*)0xa00008ec % 64) {
      lab_0x1d01373c:;
        int32_t result = function_1d016084(a1); // 0x1d013740
        if (result != 0) {
            // 0x1d01374c
            return result;
        }
        int32_t v16 = *(int32_t*)0xa00008ec; // 0x1d0136d0
        uint32_t v17 = (v16 + 1) % 64; // 0x1d0136dc
        if (*(int32_t*)0xa00008e8 % 64 == v17) {
            // 0x1d013728
            *(int32_t*)0xa00008f0 = *(int32_t*)0xa00008f0 + 1;
            result2 = 0;
        } else {
            int32_t v18 = 16 * v16 & 1008; // 0x1d0136f0
            *(int32_t *)(v18 - 0x5ffff70c) = v17;
            *(int32_t *)(v18 - 0x5ffff708) = *(int32_t *)(v1 + 4);
            *(int32_t *)(v18 - 0x5ffff704) = *(int32_t *)(v1 + 8);
            *(int32_t *)(v18 - 0x5ffff700) = *(int32_t *)(v1 + 12);
            *(int32_t*)0xa00008ec = v17;
            result2 = 1;
        }
        // 0x1d01374c
        return result2;
    }
    int32_t v19 = *(int32_t *)(16 * v15 - 0x5ffff70c); // bp-32, 0x1d0136a4
    while (function_1d016084(&v19) != 0) {
        int32_t v20 = *(int32_t*)0xa00008e8; // 0x1d0136c0
        int32_t v21 = *(int32_t*)0xa00008ec; // 0x1d0135e4
        int32_t v22 = v21; // 0x1d0135f0
        int32_t v23 = v20; // 0x1d0135f0
        if ((v21 ^ v20) % 64 != 0) {
            // 0x1d0135f4
            v23 = (v20 + 1) % 64;
            *(int32_t*)0xa00008e8 = v23;
            v22 = *(int32_t*)0xa00008ec;
        }
        int32_t v24 = v23 % 64; // 0x1d013674
        if (v24 == v22 % 64) {
            goto lab_0x1d01373c;
        }
        v19 = *(int32_t *)(16 * v24 - 0x5ffff70c);
    }
    int32_t v25 = *(int32_t*)0xa00008ec; // 0x1d013604
    uint32_t v26 = (v25 + 1) % 64; // 0x1d013610
    if (*(int32_t*)0xa00008e8 % 64 == v26) {
        // 0x1d01365c
        *(int32_t*)0xa00008f0 = *(int32_t*)0xa00008f0 + 1;
        result2 = 0;
    } else {
        int32_t v27 = 16 * v25 & 1008; // 0x1d013624
        *(int32_t *)(v27 - 0x5ffff70c) = v26;
        *(int32_t *)(v27 - 0x5ffff708) = *(int32_t *)(v1 + 4);
        *(int32_t *)(v27 - 0x5ffff704) = *(int32_t *)(v1 + 8);
        *(int32_t *)(v27 - 0x5ffff700) = *(int32_t *)(v1 + 12);
        *(int32_t*)0xa00008ec = v26;
        result2 = 1;
    }
    // 0x1d01374c
    return result2;
}

// Address range: 0x1d013760 - 0x1d0139f0
int32_t pthread_cond_destroy2(int32_t * a1) {
    int32_t v1 = (int32_t)a1;
    int32_t v2; // 0x1d013760
    if ((*(int32_t *)(v2 - 0x7f3c) & 128) != 0) {
        int32_t v3 = *(int32_t*)0xa0000cf8; // 0x1d013788
        uint32_t v4 = *(int32_t*)0xa0000cf4; // 0x1d013790
        uint32_t v5 = v4 % 0x1000; // 0x1d013794
        if (v5 != (v3 + 1) % 0x1000) {
            int32_t * v6 = (int32_t *)(v1 + 4); // 0x1d0137b8
            uint32_t v7 = *v6; // 0x1d0137b8
            int32_t v8 = __asm_ext(v7, 28, 1); // 0x1d0137bc
            int32_t v9; // 0x1d013760
            if (v8 == 0) {
                // 0x1d0137e4
                v9 = v4 % 2048;
            } else {
                // 0x1d0137c8
                v9 = __asm_ext(*v6, 10, 18) | 0x40000 * v5 & 0x1ffc0000;
            }
            int32_t v10 = 16 * v3 & 0xfff0; // 0x1d0137a4
            uint32_t v11 = v7 % 16; // 0x1d0137c4
            __asm_ins(v9, 0, 29);
            __asm_ins(v8, 29, 1);
            __asm_ins(v11, 30, 2);
            *(int32_t *)(v10 - 0x5ffff300) = __asm_ins(v11 / 4, 30, 2);
            __asm_ins(7, 27, 3);
            *(int32_t *)(v10 - 0x5ffff304) = __asm_ins(*(int32_t *)(v2 - 0x7f38), 0, 27);
            __asm_lwl(*(int32_t *)(v1 + 11));
            int32_t v12 = __asm_lwr(*(int32_t *)(v1 + 8)); // 0x1d013828
            __asm_lwl(*(int32_t *)(v1 + 15));
            int32_t v13 = __asm_lwr(*(int32_t *)(v1 + 12)); // 0x1d013830
            *(int32_t *)(v10 - 0x5ffff2fc) = v12;
            *(int32_t *)(v10 - 0x5ffff2f8) = v13;
            uint32_t v14 = (*(int32_t*)0xa0000cf8 + 1) % 0x1000; // 0x1d01384c
            if (*(int32_t*)0xa0000cf4 % 0x1000 != v14) {
                // 0x1d013860
                *(int32_t*)0xa0000cf8 = v14;
            }
        }
    }
    int32_t v15 = *(int32_t*)0xa00004dc % 64; // 0x1d013904
    int32_t result2; // 0x1d013760
    if (v15 == *(int32_t*)0xa00004e0 % 64) {
      lab_0x1d0139cc:;
        int32_t result = function_1d016378(a1); // 0x1d0139d0
        if (result != 0) {
            // 0x1d0139dc
            return result;
        }
        int32_t v16 = *(int32_t*)0xa00004e0; // 0x1d013960
        uint32_t v17 = (v16 + 1) % 64; // 0x1d01396c
        if (*(int32_t*)0xa00004dc % 64 == v17) {
            // 0x1d0139b8
            *(int32_t*)0xa00004e4 = *(int32_t*)0xa00004e4 + 1;
            result2 = 0;
        } else {
            int32_t v18 = 16 * v16 & 1008; // 0x1d013980
            *(int32_t *)(v18 - 0x5ffffb18) = v17;
            *(int32_t *)(v18 - 0x5ffffb14) = *(int32_t *)(v1 + 4);
            *(int32_t *)(v18 - 0x5ffffb10) = *(int32_t *)(v1 + 8);
            *(int32_t *)(v18 - 0x5ffffb0c) = *(int32_t *)(v1 + 12);
            *(int32_t*)0xa00004e0 = v17;
            result2 = 1;
        }
        // 0x1d0139dc
        return result2;
    }
    int32_t v19 = *(int32_t *)(16 * v15 - 0x5ffffb18); // bp-32, 0x1d013934
    while (function_1d016378(&v19) != 0) {
        int32_t v20 = *(int32_t*)0xa00004dc; // 0x1d013950
        int32_t v21 = *(int32_t*)0xa00004e0; // 0x1d013874
        int32_t v22 = v21; // 0x1d013880
        int32_t v23 = v20; // 0x1d013880
        if ((v21 ^ v20) % 64 != 0) {
            // 0x1d013884
            v23 = (v20 + 1) % 64;
            *(int32_t*)0xa00004dc = v23;
            v22 = *(int32_t*)0xa00004e0;
        }
        int32_t v24 = v23 % 64; // 0x1d013904
        if (v24 == v22 % 64) {
            goto lab_0x1d0139cc;
        }
        v19 = *(int32_t *)(16 * v24 - 0x5ffffb18);
    }
    int32_t v25 = *(int32_t*)0xa00004e0; // 0x1d013894
    uint32_t v26 = (v25 + 1) % 64; // 0x1d0138a0
    if (*(int32_t*)0xa00004dc % 64 == v26) {
        // 0x1d0138ec
        *(int32_t*)0xa00004e4 = *(int32_t*)0xa00004e4 + 1;
        result2 = 0;
    } else {
        int32_t v27 = 16 * v25 & 1008; // 0x1d0138b4
        *(int32_t *)(v27 - 0x5ffffb18) = v26;
        *(int32_t *)(v27 - 0x5ffffb14) = *(int32_t *)(v1 + 4);
        *(int32_t *)(v27 - 0x5ffffb10) = *(int32_t *)(v1 + 8);
        *(int32_t *)(v27 - 0x5ffffb0c) = *(int32_t *)(v1 + 12);
        *(int32_t*)0xa00004e0 = v26;
        result2 = 1;
    }
    // 0x1d0139dc
    return result2;
}

// Address range: 0x1d013afc - 0x1d013c08
int32_t pthread_cond_destroy(int32_t * a1) {
    uint32_t v1 = (int32_t)a1;
    int32_t v2; // 0x1d013afc
    if ((*(int32_t *)(v2 - 0x7f3c) & 8) == 0) {
        // 0x1d013bf4
        return function_1d015d50(v1);
    }
    int32_t v3 = *(int32_t*)0xa0000cf8; // 0x1d013b18
    if ((*(int32_t*)0xa0000cf4 ^ v3 + 1) % 0x1000 == 0) {
        // 0x1d013bf4
        return function_1d015d50(v1);
    }
    int32_t * v4 = (int32_t *)(v1 + 4); // 0x1d013b48
    uint32_t v5 = *v4; // 0x1d013b48
    int32_t v6 = __asm_ext(v5, 28, 1); // 0x1d013b4c
    int32_t v7; // 0x1d013afc
    if (v6 == 0) {
        // 0x1d013b74
        v7 = v1 % 2048;
    } else {
        // 0x1d013b58
        v7 = __asm_ext(*v4, 10, 18) | 0x40000 * v1 & 0x1ffc0000;
    }
    int32_t v8 = 16 * v3 & 0xfff0; // 0x1d013b34
    uint32_t v9 = v5 % 16; // 0x1d013b54
    __asm_ins(v7, 0, 29);
    __asm_ins(v6, 29, 1);
    __asm_ins(v9, 30, 2);
    *(int32_t *)(v8 - 0x5ffff300) = __asm_ins(v9 / 4, 30, 2);
    __asm_ins(3, 27, 3);
    *(int32_t *)(v8 - 0x5ffff304) = __asm_ins(*(int32_t *)(v2 - 0x7f38), 0, 27);
    __asm_lwl(*(int32_t *)(v1 + 11));
    int32_t v10 = __asm_lwr(*(int32_t *)(v1 + 8)); // 0x1d013bb8
    __asm_lwl(*(int32_t *)(v1 + 15));
    int32_t v11 = __asm_lwr(*(int32_t *)(v1 + 12)); // 0x1d013bc0
    *(int32_t *)(v8 - 0x5ffff2fc) = v10;
    *(int32_t *)(v8 - 0x5ffff2f8) = v11;
    uint32_t v12 = (*(int32_t*)0xa0000cf8 + 1) % 0x1000; // 0x1d013bdc
    if (*(int32_t*)0xa0000cf4 % 0x1000 != v12) {
        // 0x1d013bf0
        *(int32_t*)0xa0000cf8 = v12;
    }
    // 0x1d013bf4
    return function_1d015d50(v1);
}

// Address range: 0x1d015058 - 0x1d01506c
int32_t function_1d015058(void) {
    // 0x1d015058
    return (int32_t)*(char*)0xa00001bc;
}

// Address range: 0x1d015d50 - 0x1d015de0
int32_t function_1d015d50(int32_t a1) {
    int32_t v1 = function_1d01bfa0(1, 1); // 0x1d015d68
    int32_t result = 0; // 0x1d015d6c
    if (v1 != 0) {
        // 0x1d015d74
        __asm_lwl(*(int32_t *)(a1 + 3));
        int32_t v2 = __asm_lwr(1); // 0x1d015d78
        __asm_lwl(*(int32_t *)(a1 + 7));
        int32_t v3 = __asm_lwr(*(int32_t *)(a1 + 4)); // 0x1d015d80
        __asm_lwl(*(int32_t *)(a1 + 11));
        int32_t v4 = __asm_lwr(*(int32_t *)(a1 + 8)); // 0x1d015d88
        __asm_lwl(*(int32_t *)(a1 + 15));
        int32_t v5 = __asm_lwr(*(int32_t *)(a1 + 12)); // 0x1d015d90
        __asm_swl(v2, *(int32_t *)(v1 + 3));
        __asm_swr(v2, *(int32_t *)v1);
        __asm_swl(v3, *(int32_t *)(v1 + 7));
        __asm_swr(v3, *(int32_t *)(v1 + 4));
        __asm_swl(v4, *(int32_t *)(v1 + 11));
        __asm_swr(v4, *(int32_t *)(v1 + 8));
        __asm_swl(v5, *(int32_t *)(v1 + 15));
        __asm_swr(v5, *(int32_t *)(v1 + 12));
        function_1d01c1f0(1, 1);
        function_1d01c21c(1, 1);
        result = 1;
    }
    // 0x1d015dd0
    return result;
}

// Address range: 0x1d015de0 - 0x1d015e70
int32_t function_1d015de0(int32_t * a1) {
    int32_t v1 = function_1d01bfa0(1, 2); // 0x1d015df8
    int32_t result = 0; // 0x1d015dfc
    if (v1 != 0) {
        int32_t v2 = (int32_t)a1;
        __asm_lwl(*(int32_t *)(v2 + 3));
        int32_t v3 = __asm_lwr(1); // 0x1d015e08
        __asm_lwl(*(int32_t *)(v2 + 7));
        int32_t v4 = __asm_lwr(*(int32_t *)(v2 + 4)); // 0x1d015e10
        __asm_lwl(*(int32_t *)(v2 + 11));
        int32_t v5 = __asm_lwr(*(int32_t *)(v2 + 8)); // 0x1d015e18
        __asm_lwl(*(int32_t *)(v2 + 15));
        int32_t v6 = __asm_lwr(*(int32_t *)(v2 + 12)); // 0x1d015e20
        __asm_swl(v3, *(int32_t *)(v1 + 3));
        __asm_swr(v3, *(int32_t *)v1);
        __asm_swl(v4, *(int32_t *)(v1 + 7));
        __asm_swr(v4, *(int32_t *)(v1 + 4));
        __asm_swl(v5, *(int32_t *)(v1 + 11));
        __asm_swr(v5, *(int32_t *)(v1 + 8));
        __asm_swl(v6, *(int32_t *)(v1 + 15));
        __asm_swr(v6, *(int32_t *)(v1 + 12));
        function_1d01c1f0(1, 2);
        function_1d01c21c(1, 2);
        result = 1;
    }
    // 0x1d015e60
    return result;
}

// Address range: 0x1d016084 - 0x1d016138
int32_t function_1d016084(int32_t * a1) {
    int32_t result = function_1d010600(3); // 0x1d01609c
    if (result == 0 || (function_1d010b48(3) & 4) != 0) {
        // 0x1d016124
        return 0;
    }
    int32_t v1 = (int32_t)a1;
    int32_t * v2 = (int32_t *)(v1 + 4); // 0x1d0160c0
    uint32_t v3 = *v2; // 0x1d0160c0
    int32_t v4 = __asm_ext(v3, 28, 1); // 0x1d0160c4
    int32_t v5 = 3; // 0x1d0160cc
    if (v4 != 0) {
        // 0x1d0160d0
        v5 = __asm_ext(*v2, 10, 18) | 0xc0000;
    }
    // 0x1d0160f4
    function_1d0114f0(3, 0, v5, v4, v1 + 8, v3 % 16);
    function_1d011160(3, 0);
    // 0x1d016124
    return result;
}

// Address range: 0x1d016378 - 0x1d01642c
int32_t function_1d016378(int32_t * a1) {
    int32_t result = function_1d010600(2); // 0x1d016390
    if (result == 0 || (function_1d010b48(2) & 4) != 0) {
        // 0x1d016418
        return 0;
    }
    int32_t v1 = (int32_t)a1;
    int32_t * v2 = (int32_t *)(v1 + 4); // 0x1d0163b4
    uint32_t v3 = *v2; // 0x1d0163b4
    int32_t v4 = __asm_ext(v3, 28, 1); // 0x1d0163b8
    int32_t v5 = 2; // 0x1d0163c0
    if (v4 != 0) {
        // 0x1d0163c4
        v5 = __asm_ext(*v2, 10, 18) | 0x80000;
    }
    // 0x1d0163e8
    function_1d0114f0(2, 0, v5, v4, v1 + 8, v3 % 16);
    function_1d011160(2, 0);
    // 0x1d016418
    return result;
}

// Address range: 0x1d01704c - 0x1d017208
int32_t function_1d01704c(int32_t * a1) {
    int32_t v1 = (int32_t)a1 + 4; // 0x1d017068
    int32_t * v2 = (int32_t *)v1; // 0x1d017068
    int32_t v3 = *v2; // 0x1d017068
    int32_t v4; // 0x1d01704c
    char * v5 = (char *)(v4 - 0x7fb0);
    int32_t v6 = 0; // 0x1d017074
    if (__asm_ext(v3, 25, 1) != 0) {
        // 0x1d017078
        v6 = (int32_t)(*v5 % 2 ^ 1);
    }
    int32_t v7 = *v2; // 0x1d017084
    int32_t v8 = __asm_ext(v7, 25, 1); // 0x1d017088
    char v9 = v8; // 0x1d017090
    *v5 = v9;
    uint16_t v10 = *(int16_t *)v1; // 0x1d017094
    *(int32_t *)(v4 - 0x7fa8) = (int32_t)v10;
    *(int32_t *)(v4 - 0x7fa4) = 200;
    int32_t v11 = __asm_ext(v7, 24, 1); // 0x1d0170a4
    uint32_t v12 = __asm_ext(v7, 27, 1); // 0x1d0170ac
    if (*(int32_t*)0xa0013668 == 0) {
        goto lab_0x1d0171a8;
    } else {
        if (v12 % 256 == 0) {
            goto lab_0x1d01710c;
        } else {
            // 0x1d0170d4
            if (*(char*)0xa001366f == 0) {
                // 0x1d0170e4
                *(char*)0xa001365d = 1;
                int32_t * v13 = (int32_t *)(v4 - 0x7fb4); // 0x1d0170f0
                if (*v13 == 0) {
                    // 0x1d0170fc
                    *v13 = 1;
                    *(int32_t *)(v4 - 0x7fbc) = 3;
                }
                goto lab_0x1d0171a8;
            } else {
                goto lab_0x1d01710c;
            }
        }
    }
  lab_0x1d0171a8:
    if (v6 != 0) {
        int32_t * v14 = (int32_t *)(v4 - 0x7fb4); // 0x1d0171b0
        if (*v14 == 1) {
            // 0x1d0171bc
            *v14 = 2;
        }
    }
    // 0x1d0171c8
    *(int32_t*)0xa0013668 = 100;
    *(char*)0xa001366c = (char)v11;
    *(char*)0xa001366d = v9;
    *(char*)0xa001366e = (char)v6;
    *(char*)0xa001366f = (char)v12;
    *(char*)0xa0013670 = (char)((v3 & 0x74000000) != 0);
    return -0x5ffec9d4;
  lab_0x1d01710c:
    // 0x1d01710c
    if (*(char*)0xa001365c != 0) {
        // 0x1d017118
        if ((v11 | v8) % 256 == 0 == (*(char*)0xa001366c != 0)) {
            // 0x1d017134
            if (*(char*)0xa001363d == 0) {
                // 0x1d017140
                if (*(char*)0xa0013655 == 0) {
                    // 0x1d01714c
                    if (*(char*)0xa001366d == 0) {
                        char v15 = *(char *)(v4 - 0x7faf); // 0x1d01715c
                        if (v10 == 0 != (*(int32_t *)(v4 - 0x7fac) == 0 || v15 == 1)) {
                            // 0x1d017174
                            if (function_1d015058() == 0) {
                                // 0x1d017184
                                *(char*)0xa001365d = 1;
                                *(char *)(v4 - 0x7fe8) = 0;
                                int32_t * v16 = (int32_t *)(v4 - 0x7fb4); // 0x1d017190
                                if (*v16 == 0) {
                                    // 0x1d01719c
                                    *v16 = 1;
                                    *(int32_t *)(v4 - 0x7fbc) = 13;
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    goto lab_0x1d0171a8;
}

// Address range: 0x1d017260 - 0x1d017268
int32_t exit(void) {
    // 0x1d017260
    int32_t v1; // 0x1d017260
    return *(int32_t *)(v1 - 0x7fb4);
}

// Address range: 0x1d01728c - 0x1d0172b0
int32_t function_1d01728c(void) {
    // 0x1d01728c
    int32_t v1; // 0x1d01728c
    int32_t v2 = *(int32_t *)(v1 - 0x7fb4); // 0x1d01728c
    int32_t result = 1; // 0x1d017294
    if (v2 != 0) {
        // 0x1d017298
        result = v2 == 1 ? (int32_t)*(char *)(v1 - 0x7fe8) : 0;
    }
    // 0x1d0172a8
    return result;
}

// Address range: 0x1d018500 - 0x1d018514
int32_t function_1d018500(void) {
    // 0x1d018500
    return (int32_t)*(char*)0xa00001f2;
}

// Address range: 0x1d01a51c - 0x1d01a6b4
int32_t pthread_cond_destroy3(void) {
    // 0x1d01a51c
    int32_t v1; // 0x1d01a51c
    char * v2 = (char *)(v1 - 0x7f18); // 0x1d01a51c
    if (*v2 % 32 != 1) {
        // 0x1d01a6ac
        return 1;
    }
    char result = *(char *)(v1 - 0x7f14); // 0x1d01a530
    if (result != 0) {
        // 0x1d01a6ac
        return result;
    }
    char * v3 = (char *)(v1 - 0x7f17); // 0x1d01a540
    if (*v3 == 6) {
        // 0x1d01a554
        switch (*(char *)(v1 - 0x7f15)) {
            case 33: {
                // 0x1d01a578
                if (*(char *)(v1 - 0x7f28) == 1) {
                    // 0x1d01a58c
                    *(int32_t*)0xa0000480 = -0x62fe4d96;
                    *(int16_t *)-0x5ffffb78 = 9;
                    *(char*)0xa0000484 = -64;
                }
                // break -> 0x1d01a5d4
                break;
            }
            case 34: {
                // 0x1d01a5b4
                *(int32_t*)0xa0000480 = -0x62fe4dec;
                *(int16_t *)-0x5ffffb78 = 29;
                *(char*)0xa0000484 = -64;
                // break -> 0x1d01a5d4
                break;
            }
        }
    }
    // 0x1d01a5d4
    if ((*v2 & 96) != 32) {
        // 0x1d01a6ac
        return 32;
    }
    unsigned char result4 = *v3; // 0x1d01a5e8
    if (result4 == 3) {
        // 0x1d01a670
        *(int32_t*)0xa0000480 = v1 - 0x7ed7;
        *(int16_t *)-0x5ffffb78 = 1;
        *(char*)0xa0000484 = -127;
        return -0x5ffffb80;
    }
    if (result4 < 4) {
        // 0x1d01a604
        if (result4 != 2) {
            // 0x1d01a610
            return -0x60000000;
        }
        // 0x1d01a630
        *(int32_t*)0xa0000480 = v1 - 0x7ed8;
        *(int16_t *)-0x5ffffb78 = 1;
        *(char*)0xa0000484 = -63;
        return -0x5ffffb80;
    }
    // 0x1d01a618
    switch (result4) {
        case 10: {
            // 0x1d01a654
            *(char*)0xa0000484 = -128;
            unsigned char result2 = *(char *)(v1 - 0x7f15); // 0x1d01a664
            *(char *)(v1 - 0x7ed8) = result2;
            return result2;
        }
        case 11: {
            // 0x1d01a698
            *(char*)0xa0000484 = -128;
            char result3 = *(char *)(v1 - 0x7f16); // 0x1d01a6a4
            *(char *)(v1 - 0x7ed7) = result3;
            // 0x1d01a6ac
            return result3;
        }
    }
    // 0x1d01a610
    return result4;
}

// Address range: 0x1d01bfa0 - 0x1d01bfe4
int32_t function_1d01bfa0(int32_t a1, int32_t a2) {
    int32_t v1 = *(int32_t *)(4 * a1 - 0x5ffecc6c) + 64 * a2; // 0x1d01bfb8
    if (__asm_ext(*(int32_t *)(v1 + 864), 10, 1) == 0) {
        // 0x1d01bfdc
        return 0;
    }
    // 0x1d01bfcc
    return *(int32_t *)(v1 + 880) | -0x60000000;
}

// Address range: 0x1d01c1f0 - 0x1d01c21c
int32_t function_1d01c1f0(int32_t a1, int32_t a2) {
    int32_t result = *(int32_t *)(4 * a1 - 0x5ffecc6c) + 64 * a2; // 0x1d01c208
    *(int32_t *)(result + 856) = 0x2000;
    return result;
}

// Address range: 0x1d01c21c - 0x1d01c248
int32_t function_1d01c21c(int32_t a1, int32_t a2) {
    int32_t result = *(int32_t *)(4 * a1 - 0x5ffecc6c) + 64 * a2; // 0x1d01c234
    *(int32_t *)(result + 856) = 8;
    return result;
}

// Address range: 0x1d01c474 - 0x1d01c47c
int32_t exit3(void) {
    // 0x1d01c474
    int32_t result; // 0x1d01c474
    __asm_di(result);
    return result;
}

// --------------------- Meta-Information ---------------------

// Detected functions: 25
