//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

// - Added parameter for lateral acceleration limit (m/s^2) to limit maximum steering wheel angle




#include <stdint.h>

// ------------------- Function Prototypes --------------------

int32_t exit(void);
int32_t exit2(void);
int32_t function_1d008690(void);
int32_t function_1d008eec(int32_t * a1);
int32_t function_1d0126ec(int32_t a1);
int32_t function_1d012c34(int32_t a1);
int32_t function_1d01324c(int32_t a1, uint32_t a2);
int32_t function_1d0135dc(int32_t a1, int32_t a2, uint32_t a3, int32_t a4, int32_t a5, uint32_t a6);
int32_t function_1d0160e0(void);
int32_t function_1d018134(int32_t a1);
int32_t function_1d0181c4(int32_t * a1);
int32_t function_1d018468(int32_t * a1);
int32_t function_1d018778(int32_t * a1);
int32_t function_1d01a2f4(int32_t * a1);
int32_t function_1d01a508(void);
int32_t function_1d01a534(void);
int32_t function_1d01be48(void);
int32_t function_1d021918(int32_t a1, int32_t a2);
int32_t function_1d021bec(int32_t a1, int32_t a2);
int32_t function_1d021c18(int32_t a1, int32_t a2);
int32_t pthread_cond_destroy(int32_t * a1);
int32_t pthread_cond_destroy2(int32_t * a1);
int32_t pthread_cond_destroy3(int32_t * a1);
int32_t pthread_cond_destroy4(void);
int32_t time(int32_t a1);

// ------------------------ Functions -------------------------

// Address range: 0x1d008690 - 0x1d00872c
int32_t function_1d008690(void) {
    
    if (*(int32_t*)0xa00134ac < 101) {
        
        return 8;
    }
    int32_t v1 = 938; // bp-24, 0x1d0086b4
    if (*(int32_t*)0xa001352c < 3) {
        
        __asm_ins(2, 4, 4);
    } else {
        
        __asm_ins(15, 4, 4);
    }
    
    __asm_ins(1, 15, 1);
    
    return pthread_cond_destroy3(&v1);
}

// Address range: 0x1d008eec - 0x1d00919c
int32_t function_1d008eec(int32_t * a1) {
    int32_t v1 = (int32_t)a1;
    *(char *)a1 = 0;
    *(char *)(v1 + 1) = 0;
    int32_t v2 = v1 + 2; 
    *(char *)v2 = 0;
    *(char *)(v1 + 3) = 0;
    int32_t v3 = v1 + 4; 
    *(char *)v3 = 0;
    *(char *)(v1 + 5) = 0;
    char * v4 = (char *)(v1 + 6); 
    *v4 = 0;
    char * v5 = (char *)(v1 + 7); 
    *v5 = 0;
    *(int16_t *)a1 = (int16_t)*(int32_t*)0xa00001d8;
    int32_t v6 = *(int32_t*)0xa00001d4; 
    *(int16_t *)v2 = (int16_t)((int32_t)(0x51eb851f * (int64_t)v6 / 0x2000000000) - (v6 >> 31));
    int32_t v7; 
    int32_t v8; 
    if (*(int32_t*)0xa00133d4 < 4) {
        
        v8 = 0;
        goto lab_0x1d009044;
    } else {
        int32_t v9 = *(int32_t*)0xa00133f4; 
        v7 = v9;
        if (v9 >= 4) {
            
            v7 = v9;
            if (*(int32_t*)0xa0013320 >= 4) {
                
                v7 = v9;
                if (*(int32_t*)0xa00132d0 >= 4) {
                    unsigned char v10 = *(char*)0xa00132ca; 
                    unsigned char v11 = *(char*)0xa00132cb; 
                    *(int16_t *)v3 = 256 * (int16_t)v10 | (int16_t)v11;
                    *v4 = *(char*)0xa00133c8 ^ -128;
                    v8 = 0;
                    if (*(int32_t*)0xa00133d4 >= 4) {
                        
                        v7 = *(int32_t*)0xa00133f4;
                        goto lab_0x1d008f90;
                    } else {
                        goto lab_0x1d009044;
                    }
                } else {
                    goto lab_0x1d008f90;
                }
            } else {
                goto lab_0x1d008f90;
            }
        } else {
            goto lab_0x1d008f90;
        }
    }
  lab_0x1d009044:
    
    __asm_ins(v8, 0, 1);
    *v5 = (char)__asm_ins((int32_t)*(char*)0xa0000172, 1, 1);
    *v5 = (char)__asm_ins(function_1d01be48(), 2, 1);
    *v5 = (char)__asm_ins((int32_t)(function_1d01a508() != 0), 3, 1);
    int32_t v12 = 1; 
    if (*(int32_t*)0xa0013320 >= 4) {
        
        v12 = *(int32_t*)0xa00132d0 < 4;
    }
    
    *v5 = (char)__asm_ins(v12, 4, 1);
    int32_t v13 = 1; 
    if (*(int32_t*)0xa00133d4 >= 4) {
        
        v13 = *(int32_t*)0xa00133f4 < 4;
    }
    
    *v5 = (char)__asm_ins(v13, 5, 1);
    *v5 = (char)__asm_ins((int32_t)*(char*)0xa0000173, 6, 1);
    int32_t result = __asm_ins((int32_t)(*(int32_t*)0xa0013444 == 0), 7, 1); 
    *v5 = (char)result;
    return result;
  lab_0x1d008f90:
    
    v8 = 0;
    if (v7 >= 4) {
        
        v8 = 0;
        if (*(int32_t*)0xa0013320 >= 4) {
            
            v8 = 0;
            if (*(int32_t*)0xa00132d0 >= 4) {
                
                v8 = 0;
                if (*(int32_t*)0xa0013444 == 0) {
                    goto lab_0x1d009044;
                } else {
                    
                    v8 = 0;
                    if (__asm_ext(*(int32_t*)0xa001343c, 16, 1) == 0) {
                        goto lab_0x1d009044;
                    } else {
                        
                        v8 = 0;
                        if (*(char*)0xa0000172 == 0) {
                            
                            v8 = 0;
                            if (*(char*)0xa0000173 == 0) {
                                
                                if (function_1d01a508() == 0) {
                                    goto lab_0x1d009010;
                                } else {
                                    
                                    v8 = 0;
                                    if (function_1d01a534() == 0) {
                                        goto lab_0x1d009044;
                                    } else {
                                        goto lab_0x1d009010;
                                    }
                                }
                            } else {
                                goto lab_0x1d009044;
                            }
                        } else {
                            goto lab_0x1d009044;
                        }
                    }
                }
            } else {
                goto lab_0x1d009044;
            }
        } else {
            goto lab_0x1d009044;
        }
    } else {
        goto lab_0x1d009044;
    }
  lab_0x1d009010:
    
    v8 = 0;
    if (function_1d01be48() == 0) {
        
        v8 = 1;
        if ((*(int32_t*)0xa00133c8 & 0xc00000) == 0x800000) {
            goto lab_0x1d009044;
        } else {
            
            v8 = 0;
            goto lab_0x1d009044;
        }
    } else {
        goto lab_0x1d009044;
    }
}

// Address range: 0x1d00919c - 0x1d0092d0
int32_t time(int32_t a1) {
    
    int32_t v1; // bp-16, 0x1d00919c
    int32_t v2; // bp-24, 0x1d00919c
    if (*(char*)0xa0000171 == 0) {
        
        if (a1 != 0) {
            
            return -0x60000000;
        }
    } else {
        int32_t v3 = 0; 
        if (*(int32_t*)0xa001331c != 0) {
            
            v3 = __asm_ins(0, 23, 1);
        }
        
        v1 = v3;
        v2 = 936;
        if (a1 != 0) {
            
            *(int32_t*)0xbf8860e8 = 32;
            
            return function_1d0181c4(&v2);
        }
        
        pthread_cond_destroy(&v2);
        *(int32_t*)0xbf8860e4 = 32;
    }
    
    if (*(int32_t*)0xa000016c == 0) {
        
        v2 = 101;
        function_1d008eec(&v1);
        function_1d01a2f4(&v1);
        pthread_cond_destroy2(&v2);
    }
    
    if (*(int32_t*)0xa0013414 != 0) {
        
        if (__asm_ext(*(int32_t*)0xa0013410, 24, 1) != 0) {
            
            return function_1d008690();
        }
    }
    
    if (*(int32_t*)0xa0013434 != 0) {
        
        if (__asm_ext(*(int32_t*)0xa0013430, 24, 1) != 0) {
            
            return function_1d008690();
        }
    }
    
    if (*(char*)0xa0000171 == 0) {
        
        return 0;
    }
    
    return function_1d008690();
}

// Address range: 0x1d00ebbc - 0x1d00ede4
int32_t exit(void) {
    
    *(int32_t*)0xbf881074 = 0x2000000;
    *(int32_t*)0xbf885220 = 255;
    *(int32_t*)0xbf885200 = 255;
    *(int32_t*)0xbf885300 = 0;
    *(int32_t*)0xbf885310 = 0;
    *(int32_t*)0xbf885320 = 0;
    *(int32_t*)0xbf885330 = 0;
    *(int32_t*)0xbf8852e0 = 0;
    *(int32_t*)0xbf885230 = 159;
    *(int32_t*)0xbf885210 = 159;
    *(int32_t*)0xbf885070 = *(int32_t*)0xbf885070 % 16;
    *(char*)0xbf885080 = (char)__asm_ins(1, 0, 1);
    uint32_t v1 = __asm_ext(-0x5ffffc00, 0, 29); 
    *(int32_t*)0xbf8852d0 = v1 / 0x1000000;
    *(int32_t*)0xbf8852c0 = v1 / 0x10000;
    *(int32_t*)0xbf885270 = v1 / 256;
    int32_t v2 = 0; 
    int32_t v3 = 0; 
    *(int32_t *)(v2 - 0x5ffffc00) = 0;
    *(int32_t *)(v2 - 0x5ffffbfc) = 0;
    v3++;
    v2 = 8 * v3;
    while (v3 != 16) {
        
        *(int32_t *)(v2 - 0x5ffffc00) = 0;
        *(int32_t *)(v2 - 0x5ffffbfc) = 0;
        v3++;
        v2 = 8 * v3;
    }
    
    *(char*)0xbf885250 = (char)__asm_ins(1, 1, 1);
    *(int32_t*)0xbf885260 = 0;
    *(char*)0xbf885250 = (char)__asm_ins(0, 5, 1);
    *(char*)0xbf885250 = (char)__asm_ins(0, 1, 1);
    if ((*(int32_t*)0xbf885200 & 8) != 0) {
        *(int32_t*)0xbf885200 = 8;
        *(char*)0xa0000484 = 0;
        *(char*)0xa00004d4 = 0;
        *(int32_t*)0xa00004d4 = __asm_ins(0, 8, 16);
        while ((*(int32_t*)0xbf885200 & 8) != 0) {
            
            *(int32_t*)0xbf885200 = 8;
            *(char*)0xa0000484 = 0;
            *(char*)0xa00004d4 = 0;
            *(int32_t*)0xa00004d4 = __asm_ins(0, 8, 16);
        }
    }
    
    int32_t v4; 
    *(int32_t *)(v4 - 0x7f18) = 1;
    *(int32_t *)(v4 - 0x7f10) = 1;
    *(int32_t *)(v4 - 0x7ee0) = 0;
    *(int32_t *)(v4 - 0x7edc) = 0;
    *(int32_t *)(v4 - 0x7efc) = 0;
    int32_t v5 = -0x5ffffe00; 
    int32_t v6 = -0x5ffffdf0; 
    int32_t v7 = 0; 
    *(int32_t *)v6 = 0;
    *(int32_t *)v5 = 0;
    int32_t v8 = v7 + v4;
    *(char *)(v8 - 0x7ec8) = 0;
    *(char *)(v8 - 0x7ef8) = 0;
    v7++;
    v5 += 4;
    v6 += 4;
    while (v7 != 4) {
        
        *(int32_t *)v6 = 0;
        *(int32_t *)v5 = 0;
        v8 = v7 + v4;
        *(char *)(v8 - 0x7ec8) = 0;
        *(char *)(v8 - 0x7ef8) = 0;
        v7++;
        v5 += 4;
        v6 += 4;
    }
    
    *(int32_t*)0xa0000210 = -0x5ffffbf0;
    *(int32_t*)0xbf885300 = 13;
    *(int32_t*)0xa0000404 = __asm_ext(v4 - 0x7f04, 0, 29);
    *(int16_t *)-0x5ffffbfe = (int16_t)__asm_ins(64, 0, 10);
    *(int16_t *)-0x5ffffc00 = 132;
    *(char *)(v4 - 0x7f14) = 0;
    *(int32_t *)(v4 - 0x7ed8) = 0;
    return 132;
}

// Address range: 0x1d0126ec - 0x1d0126fc
int32_t function_1d0126ec(int32_t a1) {
    
    int32_t v1; 
    return (int32_t)*(char *)(a1 - 0x7f30 + v1);
}

// Address range: 0x1d012c34 - 0x1d012e68
int32_t function_1d012c34(int32_t a1) {
    switch (a1) {
        case 3: {
            
            *(int32_t*)0xbf8860e4 = 512;
            *(int32_t*)0xbf8860c4 = 512;
            *(int32_t*)0xbf805820 = 160;
            while ((*(int32_t*)0xbf805810 & 0x1f000000) == 0) {
                // continue -> 0x1d012d00
            }
            
            *(int32_t*)0xbf805820 = 0;
            while ((*(int32_t*)0xbf805810 & 0x1f000000) == 0) {
                // continue -> 0x1d012da0
            }
            
            *(int32_t*)0xbf8860e8 = 512;
            *(int32_t*)0xbf8860c4 = 512;
            return 0;
        }
        case 4: {
            
            *(int32_t*)0xbf886064 = 256;
            *(int32_t*)0xbf886044 = 256;
            *(int32_t*)0xbf805c20 = 160;
            while ((*(int32_t*)0xbf805c10 & 0x1f000000) == 0) {
                // continue -> 0x1d012d30
            }
            
            *(int32_t*)0xbf805c20 = 0;
            while ((*(int32_t*)0xbf805c10 & 0x1f000000) == 0) {
                // continue -> 0x1d012dcc
            }
            
            *(int32_t*)0xbf886068 = 256;
            *(int32_t*)0xbf886044 = 256;
            return 0;
        }
        case 2: {
            
            *(int32_t*)0xbf8861a4 = 512;
            *(int32_t*)0xbf886184 = 512;
            *(int32_t*)0xbf805a20 = 160;
            while ((*(int32_t*)0xbf805a10 & 0x1f000000) == 0) {
                // continue -> 0x1d012cd0
            }
            
            *(int32_t*)0xbf805a20 = 0;
            while ((*(int32_t*)0xbf805a10 & 0x1f000000) == 0) {
                // continue -> 0x1d012d74
            }
            
            *(int32_t*)0xbf8861a8 = 512;
            *(int32_t*)0xbf886184 = 512;
            return 0;
        }
    }
    
    return 0;
}

// Address range: 0x1d01324c - 0x1d013404
int32_t function_1d01324c(int32_t a1, uint32_t a2) {
    switch (a1) {
        case 3: {
            
            *(int32_t*)0xbf8860e4 = 512;
            *(int32_t*)0xbf8860c4 = 512;
            *(int32_t*)0xbf805820 = (1 << a2 % 4) % 128 | 128;
            while ((*(int32_t*)0xbf805810 & 0x1f000000) == 0) {
                // continue -> 0x1d013354
            }
            
            *(int32_t*)0xbf8860e8 = 512;
            *(int32_t*)0xbf8860c4 = 512;
            return 512;
        }
        case 4: {
            
            *(int32_t*)0xbf886064 = 256;
            *(int32_t*)0xbf886044 = 256;
            *(int32_t*)0xbf805c20 = (1 << a2 % 4) % 128 | 128;
            while ((*(int32_t*)0xbf805c10 & 0x1f000000) == 0) {
                // continue -> 0x1d013380
            }
            
            *(int32_t*)0xbf886068 = 256;
            *(int32_t*)0xbf886044 = 256;
            return 256;
        }
        case 2: {
            
            *(int32_t*)0xbf8861a4 = 512;
            *(int32_t*)0xbf886184 = 512;
            *(int32_t*)0xbf805a20 = (1 << a2 % 4) % 128 | 128;
            while ((*(int32_t*)0xbf805a10 & 0x1f000000) == 0) {
                // continue -> 0x1d013328
            }
            
            *(int32_t*)0xbf8861a8 = 512;
            *(int32_t*)0xbf886184 = 512;
            
            return 512;
        }
    }
    
    return 512;
}

// Address range: 0x1d0135dc - 0x1d0138b8
int32_t function_1d0135dc(int32_t a1, int32_t a2, uint32_t a3, int32_t a4, int32_t a5, uint32_t a6) {
    switch (a1) {
        case 3: {
            
            *(int32_t*)0xbf8860e4 = 512;
            *(int32_t*)0xbf8860c4 = 512;
            // break -> 0x1d013668
            break;
        }
        case 4: {
            
            *(int32_t*)0xbf886064 = 256;
            *(int32_t*)0xbf886044 = 256;
            // break -> 0x1d013668
            break;
        }
        case 2: {
            
            *(int32_t*)0xbf8861a4 = 512;
            *(int32_t*)0xbf886184 = 512;
            // break -> 0x1d013668
            break;
        }
    }
    char v1; // bp-7, 0x1d0135dc
    if (a4 == 0) {
        
        v1 = a3 / 8;
    } else {
        
        v1 = a3 / 0x200000;
        __asm_ins(0, 0, 5);
        __asm_ext(a3, 16, 2);
    }
    int32_t * v2 = (int32_t*)0xbf805a20; 
    int32_t * v3 = (int32_t*)0xbf805a10; 
    int32_t result = 2; 
    switch (a1) {
        case 3: {
            
            v2 = (int32_t*)0xbf805820;
            v3 = (int32_t*)0xbf805810;
            goto lab_0x1d013718;
        }
        case 4: {
            
            v2 = (int32_t*)0xbf805c20;
            v3 = (int32_t*)0xbf805c10;
            goto lab_0x1d013718;
        }
        case 2: {
            goto lab_0x1d013718;
        }
        default: {
            return result;
        }
    }
  lab_0x1d013718:;
    uint32_t v4 = a6 % 256; 
    int32_t v5 = v4 < 8 ? v4 : 8;
    int32_t v6 = &v1;
    *v2 = (int32_t)*(char *)(v6 - 1);
    int32_t v7 = v6 + 1; 
    int32_t v8; // bp-2, 0x1d0135dc
    while (v6 != (int32_t)&v8) {
        
        v6 = v7;
        *v2 = (int32_t)*(char *)(v6 - 1);
        v7 = v6 + 1;
    }
    
    while ((*v3 & 0x1e000000) < 0x6000000) {
        // continue -> 0x1d01373c
    }
    int32_t * v9 = (int32_t*)0xbf805a20; 
    int32_t * v10 = (int32_t*)0xbf805a10; 
    result = 2;
    switch (a1) {
        case 3: {
            
            v9 = (int32_t*)0xbf805820;
            v10 = (int32_t*)0xbf805810;
            goto lab_0x1d0137c0;
        }
        case 4: {
            
            v9 = (int32_t*)0xbf805c20;
            v10 = (int32_t*)0xbf805c10;
            goto lab_0x1d0137c0;
        }
        case 2: {
            goto lab_0x1d0137c0;
        }
        default: {
            return result;
        }
    }
  lab_0x1d0137c0:
    
    if (a5 == 0) {
        if (v5 != 0) {
            
            *v9 = 0;
        }
    } else {
        
        if (v5 != 0) {
            int32_t v11 = a5 + 1;
            *v9 = (int32_t)*(char *)a5;
            int32_t v12 = v11; 
            while (v11 != v5 + a5) {
                
                v11 = v12 + 1;
                *v9 = (int32_t)*(char *)v12;
                v12 = v11;
            }
        }
    }
    
    while ((*v10 & 0x1f000000) < 0x1000000 * v5) {
        // continue -> 0x1d013814
    }
    
    result = 2;
    switch (a1) {
        case 3: {
            
            *(int32_t*)0xbf8860e8 = 512;
            *(int32_t*)0xbf8860c4 = 512;
            result = 512;
            // break -> 0x1d0138b0
            break;
        }
        case 4: {
            
            *(int32_t*)0xbf886068 = 256;
            *(int32_t*)0xbf886044 = 256;
            result = 256;
            // break -> 0x1d0138b0
            break;
        }
        case 2: {
            
            *(int32_t*)0xbf8861a8 = 512;
            *(int32_t*)0xbf886184 = 512;
            result = 512;
            // break -> 0x1d0138b0
            break;
        }
    }
    
    return result;
}

// Address range: 0x1d016940 - 0x1d016bd0
int32_t pthread_cond_destroy2(int32_t * a1) {
    int32_t v1 = (int32_t)a1;
    int32_t v2; 
    if ((*(int32_t *)(v2 - 0x7f28) & 32) != 0) {
        int32_t v3 = *(int32_t*)0xa0000f14; 
        uint32_t v4 = *(int32_t*)0xa0000f10; 
        uint32_t v5 = v4 % 0x1000; 
        if (v5 != (v3 + 1) % 0x1000) {
            int32_t * v6 = (int32_t *)(v1 + 4); 
            uint32_t v7 = *v6; 
            int32_t v8 = __asm_ext(v7, 28, 1); 
            int32_t v9; 
            if (v8 == 0) {
                
                v9 = v4 % 2048;
            } else {
                
                v9 = __asm_ext(*v6, 10, 18) | 0x40000 * v5 & 0x1ffc0000;
            }
            int32_t v10 = 16 * v3 & 0xfff0; 
            uint32_t v11 = v7 % 16; 
            __asm_ins(v9, 0, 29);
            __asm_ins(v8, 29, 1);
            __asm_ins(v11, 30, 2);
            *(int32_t *)(v10 - 0x5ffff0e4) = __asm_ins(v11 / 4, 30, 2);
            __asm_ins(5, 27, 3);
            *(int32_t *)(v10 - 0x5ffff0e8) = __asm_ins(*(int32_t *)(v2 - 0x7f24), 0, 27);
            __asm_lwl(*(int32_t *)(v1 + 11));
            int32_t v12 = __asm_lwr(*(int32_t *)(v1 + 8)); 
            __asm_lwl(*(int32_t *)(v1 + 15));
            int32_t v13 = __asm_lwr(*(int32_t *)(v1 + 12)); 
            *(int32_t *)(v10 - 0x5ffff0e0) = v12;
            *(int32_t *)(v10 - 0x5ffff0dc) = v13;
            uint32_t v14 = (*(int32_t*)0xa0000f14 + 1) % 0x1000; 
            if (*(int32_t*)0xa0000f10 % 0x1000 != v14) {
                
                *(int32_t*)0xa0000f14 = v14;
            }
        }
    }
    int32_t v15 = *(int32_t*)0xa0000b04 % 64; 
    int32_t result2; 
    if (v15 == *(int32_t*)0xa0000b08 % 64) {
      lab_0x1d016bac:;
        int32_t result = function_1d018468(a1); 
        if (result != 0) {
            
            return result;
        }
        int32_t v16 = *(int32_t*)0xa0000b08; 
        uint32_t v17 = (v16 + 1) % 64; 
        if (*(int32_t*)0xa0000b04 % 64 == v17) {
            
            *(int32_t*)0xa0000b0c = *(int32_t*)0xa0000b0c + 1;
            result2 = 0;
        } else {
            int32_t v18 = 16 * v16 & 1008; 
            *(int32_t *)(v18 - 0x5ffff4f0) = v17;
            *(int32_t *)(v18 - 0x5ffff4ec) = *(int32_t *)(v1 + 4);
            *(int32_t *)(v18 - 0x5ffff4e8) = *(int32_t *)(v1 + 8);
            *(int32_t *)(v18 - 0x5ffff4e4) = *(int32_t *)(v1 + 12);
            *(int32_t*)0xa0000b08 = v17;
            result2 = 1;
        }
        
        return result2;
    }
    int32_t v19 = *(int32_t *)(16 * v15 - 0x5ffff4f0); // bp-32, 0x1d016b14
    while (function_1d018468(&v19) != 0) {
        int32_t v20 = *(int32_t*)0xa0000b04; 
        int32_t v21 = *(int32_t*)0xa0000b08; 
        int32_t v22 = v21; 
        int32_t v23 = v20; 
        if ((v21 ^ v20) % 64 != 0) {
            
            v23 = (v20 + 1) % 64;
            *(int32_t*)0xa0000b04 = v23;
            v22 = *(int32_t*)0xa0000b08;
        }
        int32_t v24 = v23 % 64; 
        if (v24 == v22 % 64) {
            goto lab_0x1d016bac;
        }
        v19 = *(int32_t *)(16 * v24 - 0x5ffff4f0);
    }
    int32_t v25 = *(int32_t*)0xa0000b08; 
    uint32_t v26 = (v25 + 1) % 64; 
    if (*(int32_t*)0xa0000b04 % 64 == v26) {
        
        *(int32_t*)0xa0000b0c = *(int32_t*)0xa0000b0c + 1;
        result2 = 0;
    } else {
        int32_t v27 = 16 * v25 & 1008; 
        *(int32_t *)(v27 - 0x5ffff4f0) = v26;
        *(int32_t *)(v27 - 0x5ffff4ec) = *(int32_t *)(v1 + 4);
        *(int32_t *)(v27 - 0x5ffff4e8) = *(int32_t *)(v1 + 8);
        *(int32_t *)(v27 - 0x5ffff4e4) = *(int32_t *)(v1 + 12);
        *(int32_t*)0xa0000b08 = v26;
        result2 = 1;
    }
    
    return result2;
}

// Address range: 0x1d016bd0 - 0x1d016e60
int32_t pthread_cond_destroy3(int32_t * a1) {
    int32_t v1 = (int32_t)a1;
    int32_t v2; 
    if ((*(int32_t *)(v2 - 0x7f28) & 128) != 0) {
        int32_t v3 = *(int32_t*)0xa0000f14; 
        uint32_t v4 = *(int32_t*)0xa0000f10; 
        uint32_t v5 = v4 % 0x1000; 
        if (v5 != (v3 + 1) % 0x1000) {
            int32_t * v6 = (int32_t *)(v1 + 4); 
            uint32_t v7 = *v6; 
            int32_t v8 = __asm_ext(v7, 28, 1); 
            int32_t v9; 
            if (v8 == 0) {
                
                v9 = v4 % 2048;
            } else {
                
                v9 = __asm_ext(*v6, 10, 18) | 0x40000 * v5 & 0x1ffc0000;
            }
            int32_t v10 = 16 * v3 & 0xfff0; 
            uint32_t v11 = v7 % 16; 
            __asm_ins(v9, 0, 29);
            __asm_ins(v8, 29, 1);
            __asm_ins(v11, 30, 2);
            *(int32_t *)(v10 - 0x5ffff0e4) = __asm_ins(v11 / 4, 30, 2);
            __asm_ins(7, 27, 3);
            *(int32_t *)(v10 - 0x5ffff0e8) = __asm_ins(*(int32_t *)(v2 - 0x7f24), 0, 27);
            __asm_lwl(*(int32_t *)(v1 + 11));
            int32_t v12 = __asm_lwr(*(int32_t *)(v1 + 8)); 
            __asm_lwl(*(int32_t *)(v1 + 15));
            int32_t v13 = __asm_lwr(*(int32_t *)(v1 + 12)); 
            *(int32_t *)(v10 - 0x5ffff0e0) = v12;
            *(int32_t *)(v10 - 0x5ffff0dc) = v13;
            uint32_t v14 = (*(int32_t*)0xa0000f14 + 1) % 0x1000; 
            if (*(int32_t*)0xa0000f10 % 0x1000 != v14) {
                
                *(int32_t*)0xa0000f14 = v14;
            }
        }
    }
    int32_t v15 = *(int32_t*)0xa00006f8 % 64; 
    int32_t result2; 
    if (v15 == *(int32_t*)0xa00006fc % 64) {
      lab_0x1d016e3c:;
        int32_t result = function_1d018778(a1); 
        if (result != 0) {
            
            return result;
        }
        int32_t v16 = *(int32_t*)0xa00006fc; 
        uint32_t v17 = (v16 + 1) % 64; 
        if (*(int32_t*)0xa00006f8 % 64 == v17) {
            
            *(int32_t*)0xa0000700 = *(int32_t*)0xa0000700 + 1;
            result2 = 0;
        } else {
            int32_t v18 = 16 * v16 & 1008; 
            *(int32_t *)(v18 - 0x5ffff8fc) = v17;
            *(int32_t *)(v18 - 0x5ffff8f8) = *(int32_t *)(v1 + 4);
            *(int32_t *)(v18 - 0x5ffff8f4) = *(int32_t *)(v1 + 8);
            *(int32_t *)(v18 - 0x5ffff8f0) = *(int32_t *)(v1 + 12);
            *(int32_t*)0xa00006fc = v17;
            result2 = 1;
        }
        
        return result2;
    }
    int32_t v19 = *(int32_t *)(16 * v15 - 0x5ffff8fc); // bp-32, 0x1d016da4
    while (function_1d018778(&v19) != 0) {
        int32_t v20 = *(int32_t*)0xa00006f8; 
        int32_t v21 = *(int32_t*)0xa00006fc; 
        int32_t v22 = v21; 
        int32_t v23 = v20; 
        if ((v21 ^ v20) % 64 != 0) {
            
            v23 = (v20 + 1) % 64;
            *(int32_t*)0xa00006f8 = v23;
            v22 = *(int32_t*)0xa00006fc;
        }
        int32_t v24 = v23 % 64; 
        if (v24 == v22 % 64) {
            goto lab_0x1d016e3c;
        }
        v19 = *(int32_t *)(16 * v24 - 0x5ffff8fc);
    }
    int32_t v25 = *(int32_t*)0xa00006fc; 
    uint32_t v26 = (v25 + 1) % 64; 
    if (*(int32_t*)0xa00006f8 % 64 == v26) {
        
        *(int32_t*)0xa0000700 = *(int32_t*)0xa0000700 + 1;
        result2 = 0;
    } else {
        int32_t v27 = 16 * v25 & 1008; 
        *(int32_t *)(v27 - 0x5ffff8fc) = v26;
        *(int32_t *)(v27 - 0x5ffff8f8) = *(int32_t *)(v1 + 4);
        *(int32_t *)(v27 - 0x5ffff8f4) = *(int32_t *)(v1 + 8);
        *(int32_t *)(v27 - 0x5ffff8f0) = *(int32_t *)(v1 + 12);
        *(int32_t*)0xa00006fc = v26;
        result2 = 1;
    }
    
    return result2;
}

// Address range: 0x1d016f6c - 0x1d017078
int32_t pthread_cond_destroy(int32_t * a1) {
    uint32_t v1 = (int32_t)a1;
    int32_t v2; 
    if ((*(int32_t *)(v2 - 0x7f28) & 8) == 0) {
        
        return function_1d018134(v1);
    }
    int32_t v3 = *(int32_t*)0xa0000f14; 
    if ((*(int32_t*)0xa0000f10 ^ v3 + 1) % 0x1000 == 0) {
        
        return function_1d018134(v1);
    }
    int32_t * v4 = (int32_t *)(v1 + 4); 
    uint32_t v5 = *v4; 
    int32_t v6 = __asm_ext(v5, 28, 1); 
    int32_t v7; 
    if (v6 == 0) {
        
        v7 = v1 % 2048;
    } else {
        
        v7 = __asm_ext(*v4, 10, 18) | 0x40000 * v1 & 0x1ffc0000;
    }
    int32_t v8 = 16 * v3 & 0xfff0; 
    uint32_t v9 = v5 % 16; 
    __asm_ins(v7, 0, 29);
    __asm_ins(v6, 29, 1);
    __asm_ins(v9, 30, 2);
    *(int32_t *)(v8 - 0x5ffff0e4) = __asm_ins(v9 / 4, 30, 2);
    __asm_ins(3, 27, 3);
    *(int32_t *)(v8 - 0x5ffff0e8) = __asm_ins(*(int32_t *)(v2 - 0x7f24), 0, 27);
    __asm_lwl(*(int32_t *)(v1 + 11));
    int32_t v10 = __asm_lwr(*(int32_t *)(v1 + 8)); 
    __asm_lwl(*(int32_t *)(v1 + 15));
    int32_t v11 = __asm_lwr(*(int32_t *)(v1 + 12)); 
    *(int32_t *)(v8 - 0x5ffff0e0) = v10;
    *(int32_t *)(v8 - 0x5ffff0dc) = v11;
    uint32_t v12 = (*(int32_t*)0xa0000f14 + 1) % 0x1000; 
    if (*(int32_t*)0xa0000f10 % 0x1000 != v12) {
        
        *(int32_t*)0xa0000f14 = v12;
    }
    
    return function_1d018134(v1);
}

// Address range: 0x1d018134 - 0x1d0181c4
int32_t function_1d018134(int32_t a1) {
    int32_t v1 = function_1d021918(1, 1); 
    int32_t result = 0; 
    if (v1 != 0) {
        
        __asm_lwl(*(int32_t *)(a1 + 3));
        int32_t v2 = __asm_lwr(1); 
        __asm_lwl(*(int32_t *)(a1 + 7));
        int32_t v3 = __asm_lwr(*(int32_t *)(a1 + 4)); 
        __asm_lwl(*(int32_t *)(a1 + 11));
        int32_t v4 = __asm_lwr(*(int32_t *)(a1 + 8)); 
        __asm_lwl(*(int32_t *)(a1 + 15));
        int32_t v5 = __asm_lwr(*(int32_t *)(a1 + 12)); 
        __asm_swl(v2, *(int32_t *)(v1 + 3));
        __asm_swr(v2, *(int32_t *)v1);
        __asm_swl(v3, *(int32_t *)(v1 + 7));
        __asm_swr(v3, *(int32_t *)(v1 + 4));
        __asm_swl(v4, *(int32_t *)(v1 + 11));
        __asm_swr(v4, *(int32_t *)(v1 + 8));
        __asm_swl(v5, *(int32_t *)(v1 + 15));
        __asm_swr(v5, *(int32_t *)(v1 + 12));
        function_1d021bec(1, 1);
        function_1d021c18(1, 1);
        result = 1;
    }
    
    return result;
}

// Address range: 0x1d0181c4 - 0x1d018254
int32_t function_1d0181c4(int32_t * a1) {
    int32_t v1 = function_1d021918(1, 2); 
    int32_t result = 0; 
    if (v1 != 0) {
        int32_t v2 = (int32_t)a1;
        __asm_lwl(*(int32_t *)(v2 + 3));
        int32_t v3 = __asm_lwr(1); 
        __asm_lwl(*(int32_t *)(v2 + 7));
        int32_t v4 = __asm_lwr(*(int32_t *)(v2 + 4)); 
        __asm_lwl(*(int32_t *)(v2 + 11));
        int32_t v5 = __asm_lwr(*(int32_t *)(v2 + 8)); 
        __asm_lwl(*(int32_t *)(v2 + 15));
        int32_t v6 = __asm_lwr(*(int32_t *)(v2 + 12)); 
        __asm_swl(v3, *(int32_t *)(v1 + 3));
        __asm_swr(v3, *(int32_t *)v1);
        __asm_swl(v4, *(int32_t *)(v1 + 7));
        __asm_swr(v4, *(int32_t *)(v1 + 4));
        __asm_swl(v5, *(int32_t *)(v1 + 11));
        __asm_swr(v5, *(int32_t *)(v1 + 8));
        __asm_swl(v6, *(int32_t *)(v1 + 15));
        __asm_swr(v6, *(int32_t *)(v1 + 12));
        function_1d021bec(1, 2);
        function_1d021c18(1, 2);
        result = 1;
    }
    
    return result;
}

// Address range: 0x1d018468 - 0x1d01851c
int32_t function_1d018468(int32_t * a1) {
    int32_t result = function_1d0126ec(3); 
    if (result == 0 || (function_1d012c34(3) & 4) != 0) {
        
        return 0;
    }
    int32_t v1 = (int32_t)a1;
    int32_t * v2 = (int32_t *)(v1 + 4); 
    uint32_t v3 = *v2; 
    int32_t v4 = __asm_ext(v3, 28, 1); 
    int32_t v5 = 3; 
    if (v4 != 0) {
        
        v5 = __asm_ext(*v2, 10, 18) | 0xc0000;
    }
    
    function_1d0135dc(3, 0, v5, v4, v1 + 8, v3 % 16);
    function_1d01324c(3, 0);
    
    return result;
}

// Address range: 0x1d018778 - 0x1d01882c
int32_t function_1d018778(int32_t * a1) {
    int32_t result = function_1d0126ec(2); 
    if (result == 0 || (function_1d012c34(2) & 4) != 0) {
        
        return 0;
    }
    int32_t v1 = (int32_t)a1;
    int32_t * v2 = (int32_t *)(v1 + 4); 
    uint32_t v3 = *v2; 
    int32_t v4 = __asm_ext(v3, 28, 1); 
    int32_t v5 = 2; 
    if (v4 != 0) {
        
        v5 = __asm_ext(*v2, 10, 18) | 0x80000;
    }
    
    function_1d0135dc(2, 0, v5, v4, v1 + 8, v3 % 16);
    function_1d01324c(2, 0);
    
    return result;
}

// Address range: 0x1d01a2f4 - 0x1d01a4b0
int32_t function_1d01a2f4(int32_t * a1) {
    int32_t v1 = (int32_t)a1 + 4; 
    int32_t * v2 = (int32_t *)v1; 
    int32_t v3 = *v2; 
    int32_t v4; 
    char * v5 = (char *)(v4 - 0x7f9c);
    int32_t v6 = 0; 
    if (__asm_ext(v3, 25, 1) != 0) {
        
        v6 = (int32_t)(*v5 % 2 ^ 1);
    }
    int32_t v7 = *v2; 
    int32_t v8 = __asm_ext(v7, 25, 1); 
    char v9 = v8; 
    *v5 = v9;
    uint16_t v10 = *(int16_t *)v1; 
    *(int32_t *)(v4 - 0x7f94) = (int32_t)v10;
    *(int32_t *)(v4 - 0x7f90) = 200;
    int32_t v11 = __asm_ext(v7, 24, 1); 
    uint32_t v12 = __asm_ext(v7, 27, 1); 
    if (*(int32_t*)0xa0013a9c == 0) {
        goto lab_0x1d01a450;
    } else {
        if (v12 % 256 == 0) {
            goto lab_0x1d01a3b4;
        } else {
            
            if (*(char*)0xa0013aa3 == 0) {
                
                *(char*)0xa0013a91 = 1;
                int32_t * v13 = (int32_t *)(v4 - 0x7fa0); 
                if (*v13 == 0) {
                    
                    *v13 = 1;
                    *(int32_t *)(v4 - 0x7fa8) = 3;
                }
                goto lab_0x1d01a450;
            } else {
                goto lab_0x1d01a3b4;
            }
        }
    }
  lab_0x1d01a450:
    if (v6 != 0) {
        int32_t * v14 = (int32_t *)(v4 - 0x7fa0); 
        if (*v14 == 1) {
            
            *v14 = 2;
        }
    }
    
    *(int32_t*)0xa0013a9c = 100;
    *(char*)0xa0013aa0 = (char)v11;
    *(char*)0xa0013aa1 = v9;
    *(char*)0xa0013aa2 = (char)v6;
    *(char*)0xa0013aa3 = (char)v12;
    *(char*)0xa0013aa4 = (char)((v3 & 0x74000000) != 0);
    return -0x5ffec5a0;
  lab_0x1d01a3b4:
    
    if (*(char*)0xa0013a90 != 0) {
        
        if ((v11 | v8) % 256 == 0 == (*(char*)0xa0013aa0 != 0)) {
            
            if (*(char*)0xa0013a71 == 0) {
                
                if (*(char*)0xa0013a89 == 0) {
                    
                    if (*(char*)0xa0013aa1 == 0) {
                        char v15 = *(char *)(v4 - 0x7f9b); 
                        if (v10 == 0 != (*(int32_t *)(v4 - 0x7f98) == 0 || v15 == 1)) {
                            
                            if (function_1d0160e0() == 0) {
                                
                                *(char*)0xa0013a91 = 1;
                                *(char *)(v4 - 0x7fe8) = 0;
                                int32_t * v16 = (int32_t *)(v4 - 0x7fa0); 
                                if (*v16 == 0) {
                                    
                                    *v16 = 1;
                                    *(int32_t *)(v4 - 0x7fa8) = 13;
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    goto lab_0x1d01a450;
}

// Address range: 0x1d01f860 - 0x1d01f9f8
int32_t pthread_cond_destroy4(void) {
    
    int32_t v1; 
    char * v2 = (char *)(v1 - 0x7f04); 
    if (*v2 % 32 != 1) {
        
        return 1;
    }
    char result = *(char *)(v1 - 0x7f00); 
    if (result != 0) {
        
        return result;
    }
    char * v3 = (char *)(v1 - 0x7f03); 
    if (*v3 == 6) {
        
        switch (*(char *)(v1 - 0x7f01)) {
            case 33: {
                
                if (*(char *)(v1 - 0x7f14) == 1) {
                    
                    *(int32_t*)0xa0000480 = -0x62fdf82a;
                    *(int16_t *)-0x5ffffb78 = 9;
                    *(char*)0xa0000484 = -64;
                }
                // break -> 0x1d01f918
                break;
            }
            case 34: {
                
                *(int32_t*)0xa0000480 = -0x62fdf880;
                *(int16_t *)-0x5ffffb78 = 29;
                *(char*)0xa0000484 = -64;
                // break -> 0x1d01f918
                break;
            }
        }
    }
    
    if ((*v2 & 96) != 32) {
        
        return 32;
    }
    unsigned char result4 = *v3; 
    if (result4 == 3) {
        
        *(int32_t*)0xa0000480 = v1 - 0x7ec3;
        *(int16_t *)-0x5ffffb78 = 1;
        *(char*)0xa0000484 = -127;
        return -0x5ffffb80;
    }
    if (result4 < 4) {
        
        if (result4 != 2) {
            
            return -0x60000000;
        }
        
        *(int32_t*)0xa0000480 = v1 - 0x7ec4;
        *(int16_t *)-0x5ffffb78 = 1;
        *(char*)0xa0000484 = -63;
        return -0x5ffffb80;
    }
    
    switch (result4) {
        case 10: {
            
            *(char*)0xa0000484 = -128;
            unsigned char result2 = *(char *)(v1 - 0x7f01); 
            *(char *)(v1 - 0x7ec4) = result2;
            return result2;
        }
        case 11: {
            
            *(char*)0xa0000484 = -128;
            char result3 = *(char *)(v1 - 0x7f02); 
            *(char *)(v1 - 0x7ec3) = result3;
            
            return result3;
        }
    }
    
    return result4;
}

// Address range: 0x1d01a508 - 0x1d01a510
int32_t function_1d01a508(void) {
    
    int32_t v1; 
    return *(int32_t *)(v1 - 0x7fa0);
}

// Address range: 0x1d0160e0 - 0x1d0160f4
int32_t function_1d0160e0(void) {
    
    return (int32_t)*(char*)0xa001366c;
}

// Address range: 0x1d01a534 - 0x1d01a558
int32_t function_1d01a534(void) {
    
    int32_t v1; 
    int32_t v2 = *(int32_t *)(v1 - 0x7fa0); 
    int32_t result = 1; 
    if (v2 != 0) {
        
        result = v2 == 1 ? (int32_t)*(char *)(v1 - 0x7fe8) : 0;
    }
    
    return result;
}

// Address range: 0x1d01be48 - 0x1d01be5c
int32_t function_1d01be48(void) {
    
    return (int32_t)*(char*)0xa00001ea;
}

// Address range: 0x1d021918 - 0x1d02195c
int32_t function_1d021918(int32_t a1, int32_t a2) {
    int32_t v1 = *(int32_t *)(4 * a1 - 0x5ffffe08) + 64 * a2; 
    if (__asm_ext(*(int32_t *)(v1 + 864), 10, 1) == 0) {
        
        return 0;
    }
    
    return *(int32_t *)(v1 + 880) | -0x60000000;
}

// Address range: 0x1d021bec - 0x1d021c18
int32_t function_1d021bec(int32_t a1, int32_t a2) {
    int32_t result = *(int32_t *)(4 * a1 - 0x5ffffe08) + 64 * a2; 
    *(int32_t *)(result + 856) = 0x2000;
    return result;
}

// Address range: 0x1d021c18 - 0x1d021c44
int32_t function_1d021c18(int32_t a1, int32_t a2) {
    int32_t result = *(int32_t *)(4 * a1 - 0x5ffffe08) + 64 * a2; 
    *(int32_t *)(result + 856) = 8;
    return result;
}

// Address range: 0x1d021e70 - 0x1d021e78
int32_t exit2(void) {
    
    int32_t result; 
    __asm_di(result);
    return result;
}

// --------------------- Meta-Information ---------------------

// Detected functions: 25
