//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int32_t exit(void);
int32_t exit2(void);
int32_t exit3(void);
int32_t function_1d0091fc(int32_t * a1);
int32_t function_1d00f900(int32_t a1);
int32_t function_1d00fe48(int32_t a1);
int32_t function_1d010460(int32_t a1, uint32_t a2);
int32_t function_1d0107f0(int32_t a1, int32_t a2, uint32_t a3, int32_t a4, int32_t a5, uint32_t a6);
int32_t function_1d012878(int32_t * a1);
int32_t function_1d012ea4(int32_t * a1);
int32_t function_1d013f58(int32_t a1);
int32_t function_1d013fe8(int32_t * a1);
int32_t function_1d014270(int32_t * a1);
int32_t function_1d01528c(int32_t * a1);
int32_t function_1d015468(void);
int32_t function_1d0161cc(void);
int32_t function_1d01912c(int32_t a1, int32_t a2);
int32_t function_1d01937c(int32_t a1, int32_t a2);
int32_t function_1d0193a8(int32_t a1, int32_t a2);
int32_t pthread_cond_destroy(void);
int32_t time(int32_t a1);

// ------------------------ Functions -------------------------

// Address range: 0x1d0091fc - 0x1d00956c
int32_t function_1d0091fc(int32_t * a1) {
    int32_t v1 = (int32_t)a1;
    *(char *)a1 = 0;
    *(char *)(v1 + 1) = 0;
    int32_t v2 = v1 + 2; // 0x1d009210
    *(char *)v2 = 0;
    *(char *)(v1 + 3) = 0;
    int32_t v3 = v1 + 4; // 0x1d009218
    *(char *)v3 = 0;
    *(char *)(v1 + 5) = 0;
    char * v4 = (char *)(v1 + 6); // 0x1d009220
    *v4 = 0;
    char * v5 = (char *)(v1 + 7); // 0x1d009224
    *v5 = 0;
    *(int16_t *)a1 = (int16_t)*(int32_t*)0xa00001a8;
    int32_t v6 = *(int32_t*)0xa00001a4; // 0x1d009238
    *(int16_t *)v2 = (int16_t)((int32_t)(0x51eb851f * (int64_t)v6 / 0x2000000000) - (v6 >> 31));
    int32_t v7; // 0x1d0091fc
    if (*(int32_t*)0xa0012f2c == 0) {
        // 0x1d0093d8
        v7 = 0;
        goto lab_0x1d0093e0;
    } else {
        // 0x1d00926c
        v7 = 0;
        if (*(int32_t*)0xa0012f30 < 4) {
            goto lab_0x1d0093e0;
        } else {
            // 0x1d009280
            v7 = 0;
            if (*(int32_t*)0xa0012f3c == 0) {
                goto lab_0x1d0093e0;
            } else {
                // 0x1d009290
                if (*(int32_t*)0xa0012f40 >= 4) {
                    // 0x1d0094e8
                    if (*(int32_t*)0xa0012e48 == 0) {
                        goto lab_0x1d009304;
                    } else {
                        // 0x1d0092ac
                        if (*(int32_t*)0xa0012e4c < 4) {
                            goto lab_0x1d009304;
                        } else {
                            // 0x1d0092bc
                            if (*(int32_t*)0xa0012e38 == 0) {
                                goto lab_0x1d009304;
                            } else {
                                // 0x1d0092cc
                                if (*(int32_t*)0xa0012e3c >= 4) {
                                    unsigned char v8 = *(char*)0xa0012e36; // 0x1d009500
                                    unsigned char v9 = *(char*)0xa0012e37; // 0x1d009508
                                    *(int16_t *)v3 = 256 * (int16_t)v8 | (int16_t)v9;
                                    *v4 = *(char*)0xa0012f24 ^ -128;
                                    v7 = 0;
                                    if (*(int32_t*)0xa0012f2c == 0) {
                                        goto lab_0x1d0093e0;
                                    } else {
                                        // 0x1d0092e4
                                        v7 = 0;
                                        if (*(int32_t*)0xa0012f30 < 4) {
                                            goto lab_0x1d0093e0;
                                        } else {
                                            // 0x1d0092f4
                                            v7 = 0;
                                            if (*(int32_t*)0xa0012f3c == 0) {
                                                goto lab_0x1d0093e0;
                                            } else {
                                                goto lab_0x1d009304;
                                            }
                                        }
                                    }
                                } else {
                                    goto lab_0x1d009304;
                                }
                            }
                        }
                    }
                } else {
                    goto lab_0x1d009304;
                }
            }
        }
    }
  lab_0x1d0093e0:
    // 0x1d0093e0
    __asm_ins(v7, 0, 1);
    *v5 = (char)__asm_ins((int32_t)*(char*)0xa000014a, 1, 1);
    *v5 = (char)__asm_ins(function_1d0161cc(), 2, 1);
    *v5 = (char)__asm_ins((int32_t)(exit() != 0), 3, 1);
    int32_t v10 = 1; // 0x1d009424
    if (*(int32_t*)0xa0012e48 != 0) {
        // 0x1d009428
        v10 = 1;
        if (*(int32_t*)0xa0012e4c >= 4) {
            // 0x1d00943c
            v10 = 1;
            if (*(int32_t*)0xa0012e38 != 0) {
                // 0x1d00944c
                v10 = *(int32_t*)0xa0012e3c < 4;
            }
        }
    }
    // 0x1d00945c
    *v5 = (char)__asm_ins(v10, 4, 1);
    int32_t v11 = 1; // 0x1d009478
    if (*(int32_t*)0xa0012f2c != 0) {
        // 0x1d00947c
        v11 = 1;
        if (*(int32_t*)0xa0012f30 >= 4) {
            // 0x1d009490
            v11 = 1;
            if (*(int32_t*)0xa0012f3c != 0) {
                // 0x1d0094a0
                v11 = *(int32_t*)0xa0012f40 < 4;
            }
        }
    }
    // 0x1d0094b0
    *v5 = (char)__asm_ins(v11, 5, 1);
    *v5 = (char)__asm_ins((int32_t)*(char*)0xa000014b, 6, 1);
    int32_t result = __asm_ins((int32_t)(*(int32_t*)0xa0012fa0 == 0), 7, 1); // 0x1d0094dc
    *v5 = (char)result;
    return result;
  lab_0x1d009304:
    // 0x1d009304
    v7 = 0;
    if (*(int32_t*)0xa0012f40 >= 4) {
        // 0x1d009534
        v7 = 0;
        if (*(int32_t*)0xa0012e48 == 0) {
            goto lab_0x1d0093e0;
        } else {
            // 0x1d009320
            v7 = 0;
            if (*(int32_t*)0xa0012e4c < 4) {
                goto lab_0x1d0093e0;
            } else {
                // 0x1d009330
                v7 = 0;
                if (*(int32_t*)0xa0012e38 == 0) {
                    goto lab_0x1d0093e0;
                } else {
                    // 0x1d009340
                    v7 = 0;
                    if (*(int32_t*)0xa0012e3c >= 4) {
                        // 0x1d009548
                        v7 = 0;
                        if (*(int32_t*)0xa0012fa0 == 0) {
                            goto lab_0x1d0093e0;
                        } else {
                            // 0x1d00935c
                            v7 = 0;
                            if (__asm_ext(*(int32_t*)0xa0012f98, 16, 1) == 0) {
                                goto lab_0x1d0093e0;
                            } else {
                                // 0x1d00936c
                                v7 = 0;
                                if (*(char*)0xa000014a == 0) {
                                    // 0x1d00937c
                                    v7 = 0;
                                    if (*(char*)0xa000014b == 0) {
                                        // 0x1d00938c
                                        if (exit() == 0) {
                                            goto lab_0x1d0093ac;
                                        } else {
                                            // 0x1d00939c
                                            v7 = 0;
                                            if (function_1d015468() == 0) {
                                                goto lab_0x1d0093e0;
                                            } else {
                                                goto lab_0x1d0093ac;
                                            }
                                        }
                                    } else {
                                        goto lab_0x1d0093e0;
                                    }
                                } else {
                                    goto lab_0x1d0093e0;
                                }
                            }
                        }
                    } else {
                        goto lab_0x1d0093e0;
                    }
                }
            }
        }
    } else {
        goto lab_0x1d0093e0;
    }
  lab_0x1d0093ac:
    // 0x1d0093ac
    v7 = 0;
    if (function_1d0161cc() == 0) {
        // 0x1d0093bc
        v7 = 1;
        if ((*(int32_t*)0xa0012f24 & 0xc00000) == 0x800000) {
            goto lab_0x1d0093e0;
        } else {
            // 0x1d0093d8
            v7 = 0;
            goto lab_0x1d0093e0;
        }
    } else {
        goto lab_0x1d0093e0;
    }
}

// Address range: 0x1d00956c - 0x1d009658
int32_t time(int32_t a1) {
    // 0x1d00956c
    int32_t v1; // bp-16, 0x1d00956c
    int32_t v2; // bp-24, 0x1d00956c
    if (*(char*)0xa0000149 == 0) {
        int32_t result = *(int32_t*)0xa0000144; // 0x1d009614
        if (result != 0) {
            // 0x1d009650
            return result;
        }
        // 0x1d009620
        if (a1 != 0) {
            // 0x1d009650
            return 8;
        }
    } else {
        int32_t v3 = 0; // 0x1d009590
        if (*(int32_t*)0xa0012e48 != 0) {
            // 0x1d009594
            v3 = __asm_ins(0, 23, 1);
        }
        // 0x1d0095b8
        v1 = v3;
        v2 = 936;
        if (a1 != 0) {
            // 0x1d0095cc
            *(int32_t*)0xbf8860e8 = 32;
            // 0x1d009650
            return function_1d013fe8(&v2);
        }
        // 0x1d0095e8
        function_1d012ea4(&v2);
        *(int32_t*)0xbf8860e4 = 32;
        if (*(int32_t*)0xa0000144 != 0) {
            // 0x1d009650
            return 8;
        }
    }
    // 0x1d009628
    v2 = 101;
    function_1d0091fc(&v1);
    function_1d01528c(&v1);
    // 0x1d009650
    return function_1d012878(&v2);
}

// Address range: 0x1d00db9c - 0x1d00ddc4
int32_t exit2(void) {
    // 0x1d00db9c
    *(int32_t*)0xbf881074 = 0x2000000;
    *(int32_t*)0xbf885220 = 255;
    *(int32_t*)0xbf885200 = 255;
    *(int32_t*)0xbf885300 = 0;
    *(int32_t*)0xbf885310 = 0;
    *(int32_t*)0xbf885320 = 0;
    *(int32_t*)0xbf885330 = 0;
    *(int32_t*)0xbf8852e0 = 0;
    *(int32_t*)0xbf885230 = 159;
    *(int32_t*)0xbf885210 = 159;
    *(int32_t*)0xbf885070 = *(int32_t*)0xbf885070 % 16;
    *(char*)0xbf885080 = (char)__asm_ins(1, 0, 1);
    uint32_t v1 = __asm_ext(-0x5ffffc00, 0, 29); // 0x1d00dc28
    *(int32_t*)0xbf8852d0 = v1 / 0x1000000;
    *(int32_t*)0xbf8852c0 = v1 / 0x10000;
    *(int32_t*)0xbf885270 = v1 / 256;
    int32_t v2 = 0; // 0x1d00dc60
    int32_t v3 = 0; // 0x1d00dc60
    *(int32_t *)(v2 - 0x5ffffc00) = 0;
    *(int32_t *)(v2 - 0x5ffffbfc) = 0;
    v3++;
    v2 = 8 * v3;
    while (v3 != 16) {
        // 0x1d00dc64
        *(int32_t *)(v2 - 0x5ffffc00) = 0;
        *(int32_t *)(v2 - 0x5ffffbfc) = 0;
        v3++;
        v2 = 8 * v3;
    }
    // 0x1d00dc84
    *(char*)0xbf885250 = (char)__asm_ins(1, 1, 1);
    *(int32_t*)0xbf885260 = 0;
    *(char*)0xbf885250 = (char)__asm_ins(0, 5, 1);
    *(char*)0xbf885250 = (char)__asm_ins(0, 1, 1);
    if ((*(int32_t*)0xbf885200 & 8) != 0) {
        *(int32_t*)0xbf885200 = 8;
        *(char*)0xa0000484 = 0;
        *(char*)0xa00004d4 = 0;
        *(int32_t*)0xa00004d4 = __asm_ins(0, 8, 16);
        while ((*(int32_t*)0xbf885200 & 8) != 0) {
            // 0x1d00dcdc
            *(int32_t*)0xbf885200 = 8;
            *(char*)0xa0000484 = 0;
            *(char*)0xa00004d4 = 0;
            *(int32_t*)0xa00004d4 = __asm_ins(0, 8, 16);
        }
    }
    // 0x1d00dd0c
    int32_t v4; // 0x1d00db9c
    *(int32_t *)(v4 - 0x7f2c) = 1;
    *(int32_t *)(v4 - 0x7f24) = 1;
    *(int32_t *)(v4 - 0x7ef4) = 0;
    *(int32_t *)(v4 - 0x7ef0) = 0;
    *(int32_t *)(v4 - 0x7f10) = 0;
    int32_t v5 = -0x5ffffe00; // 0x1d00dd40
    int32_t v6 = -0x5ffffdf0; // 0x1d00dd40
    int32_t v7 = 0; // 0x1d00dd40
    *(int32_t *)v6 = 0;
    *(int32_t *)v5 = 0;
    int32_t v8 = v7 + v4;
    *(char *)(v8 - 0x7edc) = 0;
    *(char *)(v8 - 0x7f0c) = 0;
    v7++;
    v5 += 4;
    v6 += 4;
    while (v7 != 4) {
        // 0x1d00dd44
        *(int32_t *)v6 = 0;
        *(int32_t *)v5 = 0;
        v8 = v7 + v4;
        *(char *)(v8 - 0x7edc) = 0;
        *(char *)(v8 - 0x7f0c) = 0;
        v7++;
        v5 += 4;
        v6 += 4;
    }
    // 0x1d00dd6c
    *(int32_t*)0xa0000210 = -0x5ffffbf0;
    *(int32_t*)0xbf885300 = 13;
    *(int32_t*)0xa0000404 = __asm_ext(v4 - 0x7f18, 0, 29);
    *(int16_t *)-0x5ffffbfe = (int16_t)__asm_ins(64, 0, 10);
    *(int16_t *)-0x5ffffc00 = 132;
    *(char *)(v4 - 0x7f28) = 0;
    *(int32_t *)(v4 - 0x7eec) = 0;
    return 132;
}

// Address range: 0x1d00f900 - 0x1d00f910
int32_t function_1d00f900(int32_t a1) {
    // 0x1d00f900
    int32_t v1; // 0x1d00f900
    return (int32_t)*(char *)(a1 - 0x7f48 + v1);
}

// Address range: 0x1d00fe48 - 0x1d01007c
int32_t function_1d00fe48(int32_t a1) {
    switch (a1) {
        case 3: {
            // 0x1d00fe80
            *(int32_t*)0xbf8860e4 = 512;
            *(int32_t*)0xbf8860c4 = 512;
            *(int32_t*)0xbf805820 = 160;
            while ((*(int32_t*)0xbf805810 & 0x1f000000) == 0) {
                // continue -> 0x1d00ff14
            }
            // 0x1d00ffa8
            *(int32_t*)0xbf805820 = 0;
            while ((*(int32_t*)0xbf805810 & 0x1f000000) == 0) {
                // continue -> 0x1d00ffb4
            }
            // 0x1d00ffc4
            *(int32_t*)0xbf8860e8 = 512;
            *(int32_t*)0xbf8860c4 = 512;
            return 0;
        }
        case 4: {
            // 0x1d00fe9c
            *(int32_t*)0xbf886064 = 256;
            *(int32_t*)0xbf886044 = 256;
            *(int32_t*)0xbf805c20 = 160;
            while ((*(int32_t*)0xbf805c10 & 0x1f000000) == 0) {
                // continue -> 0x1d00ff44
            }
            // 0x1d00ffd4
            *(int32_t*)0xbf805c20 = 0;
            while ((*(int32_t*)0xbf805c10 & 0x1f000000) == 0) {
                // continue -> 0x1d00ffe0
            }
            // 0x1d00fff0
            *(int32_t*)0xbf886068 = 256;
            *(int32_t*)0xbf886044 = 256;
            return 0;
        }
        case 2: {
            // 0x1d00fe64
            *(int32_t*)0xbf8861a4 = 512;
            *(int32_t*)0xbf886184 = 512;
            *(int32_t*)0xbf805a20 = 160;
            while ((*(int32_t*)0xbf805a10 & 0x1f000000) == 0) {
                // continue -> 0x1d00fee4
            }
            // 0x1d00ff7c
            *(int32_t*)0xbf805a20 = 0;
            while ((*(int32_t*)0xbf805a10 & 0x1f000000) == 0) {
                // continue -> 0x1d00ff88
            }
            // 0x1d00ff98
            *(int32_t*)0xbf8861a8 = 512;
            *(int32_t*)0xbf886184 = 512;
            return 0;
        }
    }
    // 0x1d010074
    return 0;
}

// Address range: 0x1d010460 - 0x1d010618
int32_t function_1d010460(int32_t a1, uint32_t a2) {
    switch (a1) {
        case 3: {
            // 0x1d0104b0
            *(int32_t*)0xbf8860e4 = 512;
            *(int32_t*)0xbf8860c4 = 512;
            *(int32_t*)0xbf805820 = (1 << a2 % 4) % 128 | 128;
            while ((*(int32_t*)0xbf805810 & 0x1f000000) == 0) {
                // continue -> 0x1d010568
            }
            // 0x1d0105e4
            *(int32_t*)0xbf8860e8 = 512;
            *(int32_t*)0xbf8860c4 = 512;
            return 512;
        }
        case 4: {
            // 0x1d0104d8
            *(int32_t*)0xbf886064 = 256;
            *(int32_t*)0xbf886044 = 256;
            *(int32_t*)0xbf805c20 = (1 << a2 % 4) % 128 | 128;
            while ((*(int32_t*)0xbf805c10 & 0x1f000000) == 0) {
                // continue -> 0x1d010594
            }
            // 0x1d010600
            *(int32_t*)0xbf886068 = 256;
            *(int32_t*)0xbf886044 = 256;
            return 256;
        }
        case 2: {
            // 0x1d010484
            *(int32_t*)0xbf8861a4 = 512;
            *(int32_t*)0xbf886184 = 512;
            *(int32_t*)0xbf805a20 = (1 << a2 % 4) % 128 | 128;
            while ((*(int32_t*)0xbf805a10 & 0x1f000000) == 0) {
                // continue -> 0x1d01053c
            }
            // 0x1d0105c8
            *(int32_t*)0xbf8861a8 = 512;
            *(int32_t*)0xbf886184 = 512;
            // 0x1d0105d8
            return 512;
        }
    }
    // 0x1d0105d8
    return 512;
}

// Address range: 0x1d0107f0 - 0x1d010acc
int32_t function_1d0107f0(int32_t a1, int32_t a2, uint32_t a3, int32_t a4, int32_t a5, uint32_t a6) {
    switch (a1) {
        case 3: {
            // 0x1d010848
            *(int32_t*)0xbf8860e4 = 512;
            *(int32_t*)0xbf8860c4 = 512;
            // break -> 0x1d01087c
            break;
        }
        case 4: {
            // 0x1d010864
            *(int32_t*)0xbf886064 = 256;
            *(int32_t*)0xbf886044 = 256;
            // break -> 0x1d01087c
            break;
        }
        case 2: {
            // 0x1d01082c
            *(int32_t*)0xbf8861a4 = 512;
            *(int32_t*)0xbf886184 = 512;
            // break -> 0x1d01087c
            break;
        }
    }
    char v1; // bp-7, 0x1d0107f0
    if (a4 == 0) {
        // 0x1d0108bc
        v1 = a3 / 8;
    } else {
        // 0x1d01088c
        v1 = a3 / 0x200000;
        __asm_ins(0, 0, 5);
        __asm_ext(a3, 16, 2);
    }
    int32_t * v2 = (int32_t*)0xbf805a20; // 0x1d0107f0
    int32_t * v3 = (int32_t*)0xbf805a10; // 0x1d0107f0
    int32_t result = 2; // 0x1d0107f0
    switch (a1) {
        case 3: {
            // 0x1d01091c
            v2 = (int32_t*)0xbf805820;
            v3 = (int32_t*)0xbf805810;
            goto lab_0x1d01092c;
        }
        case 4: {
            // 0x1d010908
            v2 = (int32_t*)0xbf805c20;
            v3 = (int32_t*)0xbf805c10;
            goto lab_0x1d01092c;
        }
        case 2: {
            goto lab_0x1d01092c;
        }
        default: {
            return result;
        }
    }
  lab_0x1d01092c:;
    uint32_t v4 = a6 % 256; // 0x1d0107f4
    int32_t v5 = v4 < 8 ? v4 : 8;
    int32_t v6 = &v1;
    *v2 = (int32_t)*(char *)(v6 - 1);
    int32_t v7 = v6 + 1; // 0x1d010940
    int32_t v8; // bp-2, 0x1d0107f0
    while (v6 != (int32_t)&v8) {
        // 0x1d010938
        v6 = v7;
        *v2 = (int32_t)*(char *)(v6 - 1);
        v7 = v6 + 1;
    }
    // 0x1d010950
    while ((*v3 & 0x1e000000) < 0x6000000) {
        // continue -> 0x1d010950
    }
    int32_t * v9 = (int32_t*)0xbf805a20; // 0x1d0107f0
    int32_t * v10 = (int32_t*)0xbf805a10; // 0x1d0107f0
    result = 2;
    switch (a1) {
        case 3: {
            // 0x1d0109c4
            v9 = (int32_t*)0xbf805820;
            v10 = (int32_t*)0xbf805810;
            goto lab_0x1d0109d4;
        }
        case 4: {
            // 0x1d0109b0
            v9 = (int32_t*)0xbf805c20;
            v10 = (int32_t*)0xbf805c10;
            goto lab_0x1d0109d4;
        }
        case 2: {
            goto lab_0x1d0109d4;
        }
        default: {
            return result;
        }
    }
  lab_0x1d0109d4:
    // 0x1d0109d4
    if (a5 == 0) {
        if (v5 != 0) {
            // 0x1d010a10
            *v9 = 0;
        }
    } else {
        // 0x1d0109ec
        if (v5 != 0) {
            int32_t v11 = a5 + 1;
            *v9 = (int32_t)*(char *)a5;
            int32_t v12 = v11; // 0x1d010a04
            while (v11 != v5 + a5) {
                // 0x1d0109f8
                v11 = v12 + 1;
                *v9 = (int32_t)*(char *)v12;
                v12 = v11;
            }
        }
    }
    // 0x1d010a24
    while ((*v10 & 0x1f000000) < 0x1000000 * v5) {
        // continue -> 0x1d010a28
    }
    // 0x1d010a5c
    result = 2;
    switch (a1) {
        case 3: {
            // 0x1d010a90
            *(int32_t*)0xbf8860e8 = 512;
            *(int32_t*)0xbf8860c4 = 512;
            result = 512;
            // break -> 0x1d010ac4
            break;
        }
        case 4: {
            // 0x1d010aac
            *(int32_t*)0xbf886068 = 256;
            *(int32_t*)0xbf886044 = 256;
            result = 256;
            // break -> 0x1d010ac4
            break;
        }
        case 2: {
            // 0x1d010a74
            *(int32_t*)0xbf8861a8 = 512;
            *(int32_t*)0xbf886184 = 512;
            result = 512;
            // break -> 0x1d010ac4
            break;
        }
    }
    // 0x1d010ac4
    return result;
}

// Address range: 0x1d012878 - 0x1d012b08
int32_t function_1d012878(int32_t * a1) {
    int32_t v1 = (int32_t)a1;
    int32_t v2; // 0x1d012878
    if ((*(int32_t *)(v2 - 0x7f40) & 32) != 0) {
        int32_t v3 = *(int32_t*)0xa0000cf8; // 0x1d0128a0
        uint32_t v4 = *(int32_t*)0xa0000cf4; // 0x1d0128a8
        uint32_t v5 = v4 % 0x1000; // 0x1d0128ac
        if (v5 != (v3 + 1) % 0x1000) {
            int32_t * v6 = (int32_t *)(v1 + 4); // 0x1d0128d0
            uint32_t v7 = *v6; // 0x1d0128d0
            int32_t v8 = __asm_ext(v7, 28, 1); // 0x1d0128d4
            int32_t v9; // 0x1d012878
            if (v8 == 0) {
                // 0x1d0128fc
                v9 = v4 % 2048;
            } else {
                // 0x1d0128e0
                v9 = __asm_ext(*v6, 10, 18) | 0x40000 * v5 & 0x1ffc0000;
            }
            int32_t v10 = 16 * v3 & 0xfff0; // 0x1d0128bc
            uint32_t v11 = v7 % 16; // 0x1d0128dc
            __asm_ins(v9, 0, 29);
            __asm_ins(v8, 29, 1);
            __asm_ins(v11, 30, 2);
            *(int32_t *)(v10 - 0x5ffff300) = __asm_ins(v11 / 4, 30, 2);
            __asm_ins(5, 27, 3);
            *(int32_t *)(v10 - 0x5ffff304) = __asm_ins(*(int32_t *)(v2 - 0x7f3c), 0, 27);
            __asm_lwl(*(int32_t *)(v1 + 11));
            int32_t v12 = __asm_lwr(*(int32_t *)(v1 + 8)); // 0x1d012940
            __asm_lwl(*(int32_t *)(v1 + 15));
            int32_t v13 = __asm_lwr(*(int32_t *)(v1 + 12)); // 0x1d012948
            *(int32_t *)(v10 - 0x5ffff2fc) = v12;
            *(int32_t *)(v10 - 0x5ffff2f8) = v13;
            uint32_t v14 = (*(int32_t*)0xa0000cf8 + 1) % 0x1000; // 0x1d012964
            if (*(int32_t*)0xa0000cf4 % 0x1000 != v14) {
                // 0x1d012978
                *(int32_t*)0xa0000cf8 = v14;
            }
        }
    }
    int32_t v15 = *(int32_t*)0xa00008e8 % 64; // 0x1d012a1c
    int32_t result2; // 0x1d012878
    if (v15 == *(int32_t*)0xa00008ec % 64) {
      lab_0x1d012ae4:;
        int32_t result = function_1d014270(a1); // 0x1d012ae8
        if (result != 0) {
            // 0x1d012af4
            return result;
        }
        int32_t v16 = *(int32_t*)0xa00008ec; // 0x1d012a78
        uint32_t v17 = (v16 + 1) % 64; // 0x1d012a84
        if (*(int32_t*)0xa00008e8 % 64 == v17) {
            // 0x1d012ad0
            *(int32_t*)0xa00008f0 = *(int32_t*)0xa00008f0 + 1;
            result2 = 0;
        } else {
            int32_t v18 = 16 * v16 & 1008; // 0x1d012a98
            *(int32_t *)(v18 - 0x5ffff70c) = v17;
            *(int32_t *)(v18 - 0x5ffff708) = *(int32_t *)(v1 + 4);
            *(int32_t *)(v18 - 0x5ffff704) = *(int32_t *)(v1 + 8);
            *(int32_t *)(v18 - 0x5ffff700) = *(int32_t *)(v1 + 12);
            *(int32_t*)0xa00008ec = v17;
            result2 = 1;
        }
        // 0x1d012af4
        return result2;
    }
    int32_t v19 = *(int32_t *)(16 * v15 - 0x5ffff70c); // bp-32, 0x1d012a4c
    while (function_1d014270(&v19) != 0) {
        int32_t v20 = *(int32_t*)0xa00008e8; // 0x1d012a68
        int32_t v21 = *(int32_t*)0xa00008ec; // 0x1d01298c
        int32_t v22 = v21; // 0x1d012998
        int32_t v23 = v20; // 0x1d012998
        if ((v21 ^ v20) % 64 != 0) {
            // 0x1d01299c
            v23 = (v20 + 1) % 64;
            *(int32_t*)0xa00008e8 = v23;
            v22 = *(int32_t*)0xa00008ec;
        }
        int32_t v24 = v23 % 64; // 0x1d012a1c
        if (v24 == v22 % 64) {
            goto lab_0x1d012ae4;
        }
        v19 = *(int32_t *)(16 * v24 - 0x5ffff70c);
    }
    int32_t v25 = *(int32_t*)0xa00008ec; // 0x1d0129ac
    uint32_t v26 = (v25 + 1) % 64; // 0x1d0129b8
    if (*(int32_t*)0xa00008e8 % 64 == v26) {
        // 0x1d012a04
        *(int32_t*)0xa00008f0 = *(int32_t*)0xa00008f0 + 1;
        result2 = 0;
    } else {
        int32_t v27 = 16 * v25 & 1008; // 0x1d0129cc
        *(int32_t *)(v27 - 0x5ffff70c) = v26;
        *(int32_t *)(v27 - 0x5ffff708) = *(int32_t *)(v1 + 4);
        *(int32_t *)(v27 - 0x5ffff704) = *(int32_t *)(v1 + 8);
        *(int32_t *)(v27 - 0x5ffff700) = *(int32_t *)(v1 + 12);
        *(int32_t*)0xa00008ec = v26;
        result2 = 1;
    }
    // 0x1d012af4
    return result2;
}

// Address range: 0x1d012ea4 - 0x1d012fb0
int32_t function_1d012ea4(int32_t * a1) {
    uint32_t v1 = (int32_t)a1;
    int32_t v2; // 0x1d012ea4
    if ((*(int32_t *)(v2 - 0x7f40) & 8) == 0) {
        // 0x1d012f9c
        return function_1d013f58(v1);
    }
    int32_t v3 = *(int32_t*)0xa0000cf8; // 0x1d012ec0
    if ((*(int32_t*)0xa0000cf4 ^ v3 + 1) % 0x1000 == 0) {
        // 0x1d012f9c
        return function_1d013f58(v1);
    }
    int32_t * v4 = (int32_t *)(v1 + 4); // 0x1d012ef0
    uint32_t v5 = *v4; // 0x1d012ef0
    int32_t v6 = __asm_ext(v5, 28, 1); // 0x1d012ef4
    int32_t v7; // 0x1d012ea4
    if (v6 == 0) {
        // 0x1d012f1c
        v7 = v1 % 2048;
    } else {
        // 0x1d012f00
        v7 = __asm_ext(*v4, 10, 18) | 0x40000 * v1 & 0x1ffc0000;
    }
    int32_t v8 = 16 * v3 & 0xfff0; // 0x1d012edc
    uint32_t v9 = v5 % 16; // 0x1d012efc
    __asm_ins(v7, 0, 29);
    __asm_ins(v6, 29, 1);
    __asm_ins(v9, 30, 2);
    *(int32_t *)(v8 - 0x5ffff300) = __asm_ins(v9 / 4, 30, 2);
    __asm_ins(3, 27, 3);
    *(int32_t *)(v8 - 0x5ffff304) = __asm_ins(*(int32_t *)(v2 - 0x7f3c), 0, 27);
    __asm_lwl(*(int32_t *)(v1 + 11));
    int32_t v10 = __asm_lwr(*(int32_t *)(v1 + 8)); // 0x1d012f60
    __asm_lwl(*(int32_t *)(v1 + 15));
    int32_t v11 = __asm_lwr(*(int32_t *)(v1 + 12)); // 0x1d012f68
    *(int32_t *)(v8 - 0x5ffff2fc) = v10;
    *(int32_t *)(v8 - 0x5ffff2f8) = v11;
    uint32_t v12 = (*(int32_t*)0xa0000cf8 + 1) % 0x1000; // 0x1d012f84
    if (*(int32_t*)0xa0000cf4 % 0x1000 != v12) {
        // 0x1d012f98
        *(int32_t*)0xa0000cf8 = v12;
    }
    // 0x1d012f9c
    return function_1d013f58(v1);
}

// Address range: 0x1d013f58 - 0x1d013fe8
int32_t function_1d013f58(int32_t a1) {
    int32_t v1 = function_1d01912c(1, 1); // 0x1d013f70
    int32_t result = 0; // 0x1d013f74
    if (v1 != 0) {
        // 0x1d013f7c
        __asm_lwl(*(int32_t *)(a1 + 3));
        int32_t v2 = __asm_lwr(1); // 0x1d013f80
        __asm_lwl(*(int32_t *)(a1 + 7));
        int32_t v3 = __asm_lwr(*(int32_t *)(a1 + 4)); // 0x1d013f88
        __asm_lwl(*(int32_t *)(a1 + 11));
        int32_t v4 = __asm_lwr(*(int32_t *)(a1 + 8)); // 0x1d013f90
        __asm_lwl(*(int32_t *)(a1 + 15));
        int32_t v5 = __asm_lwr(*(int32_t *)(a1 + 12)); // 0x1d013f98
        __asm_swl(v2, *(int32_t *)(v1 + 3));
        __asm_swr(v2, *(int32_t *)v1);
        __asm_swl(v3, *(int32_t *)(v1 + 7));
        __asm_swr(v3, *(int32_t *)(v1 + 4));
        __asm_swl(v4, *(int32_t *)(v1 + 11));
        __asm_swr(v4, *(int32_t *)(v1 + 8));
        __asm_swl(v5, *(int32_t *)(v1 + 15));
        __asm_swr(v5, *(int32_t *)(v1 + 12));
        function_1d01937c(1, 1);
        function_1d0193a8(1, 1);
        result = 1;
    }
    // 0x1d013fd8
    return result;
}

// Address range: 0x1d013fe8 - 0x1d014078
int32_t function_1d013fe8(int32_t * a1) {
    int32_t v1 = function_1d01912c(1, 2); // 0x1d014000
    int32_t result = 0; // 0x1d014004
    if (v1 != 0) {
        int32_t v2 = (int32_t)a1;
        __asm_lwl(*(int32_t *)(v2 + 3));
        int32_t v3 = __asm_lwr(1); // 0x1d014010
        __asm_lwl(*(int32_t *)(v2 + 7));
        int32_t v4 = __asm_lwr(*(int32_t *)(v2 + 4)); // 0x1d014018
        __asm_lwl(*(int32_t *)(v2 + 11));
        int32_t v5 = __asm_lwr(*(int32_t *)(v2 + 8)); // 0x1d014020
        __asm_lwl(*(int32_t *)(v2 + 15));
        int32_t v6 = __asm_lwr(*(int32_t *)(v2 + 12)); // 0x1d014028
        __asm_swl(v3, *(int32_t *)(v1 + 3));
        __asm_swr(v3, *(int32_t *)v1);
        __asm_swl(v4, *(int32_t *)(v1 + 7));
        __asm_swr(v4, *(int32_t *)(v1 + 4));
        __asm_swl(v5, *(int32_t *)(v1 + 11));
        __asm_swr(v5, *(int32_t *)(v1 + 8));
        __asm_swl(v6, *(int32_t *)(v1 + 15));
        __asm_swr(v6, *(int32_t *)(v1 + 12));
        function_1d01937c(1, 2);
        function_1d0193a8(1, 2);
        result = 1;
    }
    // 0x1d014068
    return result;
}

// Address range: 0x1d014270 - 0x1d014324
int32_t function_1d014270(int32_t * a1) {
    int32_t result = function_1d00f900(3); // 0x1d014288
    if (result == 0 || (function_1d00fe48(3) & 4) != 0) {
        // 0x1d014310
        return 0;
    }
    int32_t v1 = (int32_t)a1;
    int32_t * v2 = (int32_t *)(v1 + 4); // 0x1d0142ac
    uint32_t v3 = *v2; // 0x1d0142ac
    int32_t v4 = __asm_ext(v3, 28, 1); // 0x1d0142b0
    int32_t v5 = 3; // 0x1d0142b8
    if (v4 != 0) {
        // 0x1d0142bc
        v5 = __asm_ext(*v2, 10, 18) | 0xc0000;
    }
    // 0x1d0142e0
    function_1d0107f0(3, 0, v5, v4, v1 + 8, v3 % 16);
    function_1d010460(3, 0);
    // 0x1d014310
    return result;
}

// Address range: 0x1d01528c - 0x1d0153e4
int32_t function_1d01528c(int32_t * a1) {
    int32_t v1 = (int32_t)a1 + 4; // 0x1d01528c
    uint16_t v2 = *(int16_t *)v1; // 0x1d01528c
    int32_t v3; // 0x1d01528c
    *(int32_t *)(v3 - 0x7fb8) = (int32_t)v2;
    *(int32_t *)(v3 - 0x7fb4) = 100;
    int32_t v4 = *(int32_t *)v1; // 0x1d01529c
    int32_t v5 = __asm_ext(v4, 24, 1); // 0x1d0152a0
    int32_t v6 = __asm_ext(v4, 25, 1); // 0x1d0152a8
    uint32_t v7 = __asm_ext(v4, 27, 1); // 0x1d0152b0
    if (*(int32_t*)0xa00132bc == 0) {
        goto lab_0x1d0153c4;
    } else {
        if (v7 % 256 == 0) {
            goto lab_0x1d015314;
        } else {
            // 0x1d0152d8
            if (*(char*)0xa00132c3 == 0) {
                // 0x1d0152e8
                *(char*)0xa00132b1 = 1;
                int32_t * v8 = (int32_t *)(v3 - 0x7fc4); // 0x1d0152f4
                if (*v8 == 0) {
                    // 0x1d015300
                    *v8 = 1;
                    *(int32_t *)(v3 - 0x7fc8) = 3;
                }
                goto lab_0x1d0153c4;
            } else {
                goto lab_0x1d015314;
            }
        }
    }
  lab_0x1d0153c4:
    // 0x1d0153c4
    *(int32_t*)0xa00132bc = 100;
    *(char*)0xa00132c0 = (char)v5;
    *(char*)0xa00132c1 = (char)v6;
    *(char*)0xa00132c2 = 0;
    *(char*)0xa00132c3 = (char)v7;
    *(char*)0xa00132c4 = (char)((v4 & 0x74000000) != 0);
    return -0x5ffecd80;
  lab_0x1d015314:
    // 0x1d015314
    if (*(char*)0xa00132b0 != 0) {
        // 0x1d015320
        if (*(char*)0xa00132c0 != 0) {
            if ((v6 | v5) % 256 == 0) {
                // 0x1d015340
                if (*(char*)0xa0013291 == 0) {
                    // 0x1d015350
                    if (*(char*)0xa00132a9 == 0) {
                        // 0x1d015360
                        if (*(char*)0xa00132c1 == 0) {
                            char v9 = *(char *)(v3 - 0x7fc0); // 0x1d015378
                            if (v2 == 0 != (*(int32_t *)(v3 - 0x7fbc) == 0 || v9 == 1)) {
                                // 0x1d015394
                                *(char*)0xa00132b1 = 1;
                                *(char *)(v3 - 0x7fe8) = 0;
                                int32_t * v10 = (int32_t *)(v3 - 0x7fc4); // 0x1d0153a0
                                if (*v10 == 0) {
                                    // 0x1d0153ac
                                    *v10 = 1;
                                    *(int32_t *)(v3 - 0x7fc8) = 13;
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    goto lab_0x1d0153c4;
}

// Address range: 0x1d01543c - 0x1d015444
int32_t exit(void) {
    // 0x1d01543c
    int32_t v1; // 0x1d01543c
    return *(int32_t *)(v1 - 0x7fc4);
}

// Address range: 0x1d015468 - 0x1d015480
int32_t function_1d015468(void) {
    // 0x1d015468
    int32_t v1; // 0x1d015468
    int32_t v2 = *(int32_t *)(v1 - 0x7fc4); // 0x1d01546c
    return v2 == 1 ? (int32_t)*(char *)(v1 - 0x7fe8) : 0;
}

// Address range: 0x1d0161cc - 0x1d0161d8
int32_t function_1d0161cc(void) {
    // 0x1d0161cc
    int32_t v1; // 0x1d0161cc
    return (int32_t)*(char *)(v1 - 0x7fcf);
}

// Address range: 0x1d017968 - 0x1d017b00
int32_t pthread_cond_destroy(void) {
    // 0x1d017968
    int32_t v1; // 0x1d017968
    char * v2 = (char *)(v1 - 0x7f18); // 0x1d017968
    if (*v2 % 32 != 1) {
        // 0x1d017af8
        return 1;
    }
    char result = *(char *)(v1 - 0x7f14); // 0x1d01797c
    if (result != 0) {
        // 0x1d017af8
        return result;
    }
    char * v3 = (char *)(v1 - 0x7f17); // 0x1d01798c
    if (*v3 == 6) {
        // 0x1d0179a0
        switch (*(char *)(v1 - 0x7f15)) {
            case 33: {
                // 0x1d0179c4
                if (*(char *)(v1 - 0x7f28) == 1) {
                    // 0x1d0179d8
                    *(int32_t*)0xa0000480 = -0x62fe7916;
                    *(int16_t *)-0x5ffffb78 = 9;
                    *(char*)0xa0000484 = -64;
                }
                // break -> 0x1d017a20
                break;
            }
            case 34: {
                // 0x1d017a00
                *(int32_t*)0xa0000480 = -0x62fe796c;
                *(int16_t *)-0x5ffffb78 = 29;
                *(char*)0xa0000484 = -64;
                // break -> 0x1d017a20
                break;
            }
        }
    }
    // 0x1d017a20
    if ((*v2 & 96) != 32) {
        // 0x1d017af8
        return 32;
    }
    unsigned char result4 = *v3; // 0x1d017a34
    if (result4 == 3) {
        // 0x1d017abc
        *(int32_t*)0xa0000480 = v1 - 0x7ed7;
        *(int16_t *)-0x5ffffb78 = 1;
        *(char*)0xa0000484 = -127;
        return -0x5ffffb80;
    }
    if (result4 < 4) {
        // 0x1d017a50
        if (result4 != 2) {
            // 0x1d017a5c
            return -0x60000000;
        }
        // 0x1d017a7c
        *(int32_t*)0xa0000480 = v1 - 0x7ed8;
        *(int16_t *)-0x5ffffb78 = 1;
        *(char*)0xa0000484 = -63;
        return -0x5ffffb80;
    }
    // 0x1d017a64
    switch (result4) {
        case 10: {
            // 0x1d017aa0
            *(char*)0xa0000484 = -128;
            unsigned char result2 = *(char *)(v1 - 0x7f15); // 0x1d017ab0
            *(char *)(v1 - 0x7ed8) = result2;
            return result2;
        }
        case 11: {
            // 0x1d017ae4
            *(char*)0xa0000484 = -128;
            char result3 = *(char *)(v1 - 0x7f16); // 0x1d017af0
            *(char *)(v1 - 0x7ed7) = result3;
            // 0x1d017af8
            return result3;
        }
    }
    // 0x1d017a5c
    return result4;
}

// Address range: 0x1d01912c - 0x1d019170
int32_t function_1d01912c(int32_t a1, int32_t a2) {
    int32_t v1 = *(int32_t *)(4 * a1 - 0x5ffecd38) + 64 * a2; // 0x1d019144
    if (__asm_ext(*(int32_t *)(v1 + 864), 10, 1) == 0) {
        // 0x1d019168
        return 0;
    }
    // 0x1d019158
    return *(int32_t *)(v1 + 880) | -0x60000000;
}

// Address range: 0x1d01937c - 0x1d0193a8
int32_t function_1d01937c(int32_t a1, int32_t a2) {
    int32_t result = *(int32_t *)(4 * a1 - 0x5ffecd38) + 64 * a2; // 0x1d019394
    *(int32_t *)(result + 856) = 0x2000;
    return result;
}

// Address range: 0x1d0193a8 - 0x1d0193d4
int32_t function_1d0193a8(int32_t a1, int32_t a2) {
    int32_t result = *(int32_t *)(4 * a1 - 0x5ffecd38) + 64 * a2; // 0x1d0193c0
    *(int32_t *)(result + 856) = 8;
    return result;
}

// Address range: 0x1d0195b4 - 0x1d0195bc
int32_t exit3(void) {
    // 0x1d0195b4
    int32_t result; // 0x1d0195b4
    __asm_di(result);
    return result;
}

// --------------------- Meta-Information ---------------------

// Detected functions: 21
