//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int32_t exit(void);
int32_t exit2(void);
int32_t exit3(void);
int32_t function_1d008924(void);
int32_t function_1d00921c(int32_t * a1);
int32_t function_1d010328(int32_t a1);
int32_t function_1d010870(int32_t a1);
int32_t function_1d010e88(int32_t a1, uint32_t a2);
int32_t function_1d011218(int32_t a1, int32_t a2, uint32_t a3, int32_t a4, int32_t a5, uint32_t a6);
int32_t function_1d0133c0(int32_t * a1);
int32_t function_1d014b44(int32_t a1);
int32_t function_1d014bd4(int32_t * a1);
int32_t function_1d014e5c(int32_t * a1);
int32_t function_1d015134(int32_t * a1);
int32_t function_1d015f10(int32_t * a1);
int32_t function_1d01612c(void);
int32_t function_1d017444(void);
int32_t function_1d01acd8(char a1);
int32_t function_1d01ae28(int32_t a1, int32_t a2);
int32_t function_1d01b078(int32_t a1, int32_t a2);
int32_t function_1d01b0a4(int32_t a1, int32_t a2);
int32_t pthread_cond_destroy(int32_t * a1);
int32_t pthread_cond_destroy2(int32_t * a1);
int32_t pthread_cond_destroy3(void);
int32_t time(int32_t a1);

// ------------------------ Functions -------------------------

// Address range: 0x1d008924 - 0x1d0089c0
int32_t function_1d008924(void) {
    // 0x1d008924
    if (*(int32_t*)0xa0013244 < 101) {
        // 0x1d0089b8
        return 8;
    }
    int32_t v1 = 938; // bp-24, 0x1d008948
    if (*(int32_t*)0xa00132c4 < 3) {
        // 0x1d008984
        __asm_ins(2, 4, 4);
    } else {
        // 0x1d008960
        __asm_ins(15, 4, 4);
    }
    // 0x1d008998
    __asm_ins(1, 15, 1);
    // 0x1d0089b8
    return pthread_cond_destroy2(&v1);
}

// Address range: 0x1d00921c - 0x1d0094cc
int32_t function_1d00921c(int32_t * a1) {
    int32_t v1 = (int32_t)a1;
    *(char *)a1 = 0;
    *(char *)(v1 + 1) = 0;
    int32_t v2 = v1 + 2; // 0x1d009230
    *(char *)v2 = 0;
    *(char *)(v1 + 3) = 0;
    int32_t v3 = v1 + 4; // 0x1d009238
    *(char *)v3 = 0;
    *(char *)(v1 + 5) = 0;
    char * v4 = (char *)(v1 + 6); // 0x1d009240
    *v4 = 0;
    char * v5 = (char *)(v1 + 7); // 0x1d009244
    *v5 = 0;
    *(int16_t *)a1 = (int16_t)*(int32_t*)0xa001354c;
    int32_t v6 = *(int32_t*)0xa0013548; // 0x1d009258
    *(int16_t *)v2 = (int16_t)((int32_t)(0x51eb851f * (int64_t)v6 / 0x2000000000) - (v6 >> 31));
    int32_t v7; // 0x1d00921c
    int32_t v8; // 0x1d00921c
    if (*(int32_t*)0xa001316c < 4) {
        // 0x1d00936c
        v8 = 0;
        goto lab_0x1d009374;
    } else {
        int32_t v9 = *(int32_t*)0xa001318c; // 0x1d009294
        v7 = v9;
        if (v9 >= 4) {
            // 0x1d00943c
            v7 = v9;
            if (*(int32_t*)0xa00130b8 >= 4) {
                // 0x1d0092ac
                v7 = v9;
                if (*(int32_t*)0xa0013068 >= 4) {
                    unsigned char v10 = *(char*)0xa0013062; // 0x1d009458
                    unsigned char v11 = *(char*)0xa0013063; // 0x1d009460
                    *(int16_t *)v3 = 256 * (int16_t)v10 | (int16_t)v11;
                    *v4 = *(char*)0xa0013160 ^ -128;
                    v8 = 0;
                    if (*(int32_t*)0xa001316c >= 4) {
                        // 0x1d009454
                        v7 = *(int32_t*)0xa001318c;
                        goto lab_0x1d0092c0;
                    } else {
                        goto lab_0x1d009374;
                    }
                } else {
                    goto lab_0x1d0092c0;
                }
            } else {
                goto lab_0x1d0092c0;
            }
        } else {
            goto lab_0x1d0092c0;
        }
    }
  lab_0x1d009374:
    // 0x1d009374
    __asm_ins(v8, 0, 1);
    *v5 = (char)__asm_ins((int32_t)*(char*)0xa00134ee, 1, 1);
    *v5 = (char)__asm_ins(function_1d017444(), 2, 1);
    *v5 = (char)__asm_ins((int32_t)(exit() != 0), 3, 1);
    int32_t v12 = 1; // 0x1d0093bc
    if (*(int32_t*)0xa00130b8 >= 4) {
        // 0x1d0093c0
        v12 = *(int32_t*)0xa0013068 < 4;
    }
    // 0x1d0093d0
    *v5 = (char)__asm_ins(v12, 4, 1);
    int32_t v13 = 1; // 0x1d0093f0
    if (*(int32_t*)0xa001316c >= 4) {
        // 0x1d0093f4
        v13 = *(int32_t*)0xa001318c < 4;
    }
    // 0x1d009404
    *v5 = (char)__asm_ins(v13, 5, 1);
    *v5 = (char)__asm_ins((int32_t)*(char*)0xa00134ef, 6, 1);
    int32_t result = __asm_ins((int32_t)(*(int32_t*)0xa00131dc == 0), 7, 1); // 0x1d009430
    *v5 = (char)result;
    return result;
  lab_0x1d0092c0:
    // 0x1d0092c0
    v8 = 0;
    if (v7 >= 4) {
        // 0x1d009490
        v8 = 0;
        if (*(int32_t*)0xa00130b8 >= 4) {
            // 0x1d0092d8
            v8 = 0;
            if (*(int32_t*)0xa0013068 >= 4) {
                // 0x1d0094a8
                v8 = 0;
                if (*(int32_t*)0xa00131dc == 0) {
                    goto lab_0x1d009374;
                } else {
                    // 0x1d0092f0
                    v8 = 0;
                    if (__asm_ext(*(int32_t*)0xa00131d4, 16, 1) == 0) {
                        goto lab_0x1d009374;
                    } else {
                        // 0x1d009300
                        v8 = 0;
                        if (*(char*)0xa00134ee == 0) {
                            // 0x1d009310
                            v8 = 0;
                            if (*(char*)0xa00134ef == 0) {
                                // 0x1d009320
                                if (exit() == 0) {
                                    goto lab_0x1d009340;
                                } else {
                                    // 0x1d009330
                                    v8 = 0;
                                    if (function_1d01612c() == 0) {
                                        goto lab_0x1d009374;
                                    } else {
                                        goto lab_0x1d009340;
                                    }
                                }
                            } else {
                                goto lab_0x1d009374;
                            }
                        } else {
                            goto lab_0x1d009374;
                        }
                    }
                }
            } else {
                goto lab_0x1d009374;
            }
        } else {
            goto lab_0x1d009374;
        }
    } else {
        goto lab_0x1d009374;
    }
  lab_0x1d009340:
    // 0x1d009340
    v8 = 0;
    if (function_1d017444() == 0) {
        // 0x1d009350
        v8 = 1;
        if ((*(int32_t*)0xa0013160 & 0xc00000) == 0x800000) {
            goto lab_0x1d009374;
        } else {
            // 0x1d00936c
            v8 = 0;
            goto lab_0x1d009374;
        }
    } else {
        goto lab_0x1d009374;
    }
}

// Address range: 0x1d0094cc - 0x1d009600
int32_t time(int32_t a1) {
    // 0x1d0094cc
    int32_t v1; // bp-16, 0x1d0094cc
    int32_t v2; // bp-24, 0x1d0094cc
    if (*(char*)0xa00134ed == 0) {
        // 0x1d009560
        if (a1 != 0) {
            // 0x1d0095f8
            return -0x5fff0000;
        }
    } else {
        int32_t v3 = 0; // 0x1d0094ec
        if (*(int32_t*)0xa00130b4 != 0) {
            // 0x1d0094f0
            v3 = __asm_ins(0, 23, 1);
        }
        // 0x1d009514
        v1 = v3;
        v2 = 936;
        if (a1 != 0) {
            // 0x1d009528
            *(int32_t*)0xbf8860e8 = 32;
            // 0x1d0095f8
            return function_1d014bd4(&v2);
        }
        // 0x1d009544
        pthread_cond_destroy(&v2);
        *(int32_t*)0xbf8860e4 = 32;
    }
    // 0x1d009568
    if (*(int32_t*)0xa00134e8 == 0) {
        // 0x1d009574
        v2 = 101;
        function_1d00921c(&v1);
        function_1d015f10(&v1);
        function_1d0133c0(&v2);
    }
    // 0x1d0095a0
    if (*(int32_t*)0xa00131ac != 0) {
        // 0x1d0095ac
        if (__asm_ext(*(int32_t*)0xa00131a8, 24, 1) != 0) {
            // 0x1d0095f8
            return function_1d008924();
        }
    }
    // 0x1d0095c0
    if (*(int32_t*)0xa00131cc != 0) {
        // 0x1d0095cc
        if (__asm_ext(*(int32_t*)0xa00131c8, 24, 1) != 0) {
            // 0x1d0095f8
            return function_1d008924();
        }
    }
    // 0x1d0095e0
    if (*(char*)0xa00134ed == 0) {
        // 0x1d0095f8
        return 0;
    }
    // 0x1d0095f8
    return function_1d008924();
}

// Address range: 0x1d00e5c4 - 0x1d00e7ec
int32_t exit2(void) {
    // 0x1d00e5c4
    *(int32_t*)0xbf881074 = 0x2000000;
    *(int32_t*)0xbf885220 = 255;
    *(int32_t*)0xbf885200 = 255;
    *(int32_t*)0xbf885300 = 0;
    *(int32_t*)0xbf885310 = 0;
    *(int32_t*)0xbf885320 = 0;
    *(int32_t*)0xbf885330 = 0;
    *(int32_t*)0xbf8852e0 = 0;
    *(int32_t*)0xbf885230 = 159;
    *(int32_t*)0xbf885210 = 159;
    *(int32_t*)0xbf885070 = *(int32_t*)0xbf885070 % 16;
    *(char*)0xbf885080 = (char)__asm_ins(1, 0, 1);
    uint32_t v1 = __asm_ext(-0x5ffffc00, 0, 29); // 0x1d00e650
    *(int32_t*)0xbf8852d0 = v1 / 0x1000000;
    *(int32_t*)0xbf8852c0 = v1 / 0x10000;
    *(int32_t*)0xbf885270 = v1 / 256;
    int32_t v2 = 0; // 0x1d00e688
    int32_t v3 = 0; // 0x1d00e688
    *(int32_t *)(v2 - 0x5ffffc00) = 0;
    *(int32_t *)(v2 - 0x5ffffbfc) = 0;
    v3++;
    v2 = 8 * v3;
    while (v3 != 16) {
        // 0x1d00e68c
        *(int32_t *)(v2 - 0x5ffffc00) = 0;
        *(int32_t *)(v2 - 0x5ffffbfc) = 0;
        v3++;
        v2 = 8 * v3;
    }
    // 0x1d00e6ac
    *(char*)0xbf885250 = (char)__asm_ins(1, 1, 1);
    *(int32_t*)0xbf885260 = 0;
    *(char*)0xbf885250 = (char)__asm_ins(0, 5, 1);
    *(char*)0xbf885250 = (char)__asm_ins(0, 1, 1);
    if ((*(int32_t*)0xbf885200 & 8) != 0) {
        *(int32_t*)0xbf885200 = 8;
        *(char*)0xa0000484 = 0;
        *(char*)0xa00004d4 = 0;
        *(int32_t*)0xa00004d4 = __asm_ins(0, 8, 16);
        while ((*(int32_t*)0xbf885200 & 8) != 0) {
            // 0x1d00e704
            *(int32_t*)0xbf885200 = 8;
            *(char*)0xa0000484 = 0;
            *(char*)0xa00004d4 = 0;
            *(int32_t*)0xa00004d4 = __asm_ins(0, 8, 16);
        }
    }
    // 0x1d00e734
    int32_t v4; // 0x1d00e5c4
    *(int32_t *)(v4 - 0x7f24) = 1;
    *(int32_t *)(v4 - 0x7f1c) = 1;
    *(int32_t *)(v4 - 0x7eec) = 0;
    *(int32_t *)(v4 - 0x7ee8) = 0;
    *(int32_t *)(v4 - 0x7f08) = 0;
    int32_t v5 = -0x5ffffe00; // 0x1d00e768
    int32_t v6 = -0x5ffffdf0; // 0x1d00e768
    int32_t v7 = 0; // 0x1d00e768
    *(int32_t *)v6 = 0;
    *(int32_t *)v5 = 0;
    int32_t v8 = v7 + v4;
    *(char *)(v8 - 0x7ed4) = 0;
    *(char *)(v8 - 0x7f04) = 0;
    v7++;
    v5 += 4;
    v6 += 4;
    while (v7 != 4) {
        // 0x1d00e76c
        *(int32_t *)v6 = 0;
        *(int32_t *)v5 = 0;
        v8 = v7 + v4;
        *(char *)(v8 - 0x7ed4) = 0;
        *(char *)(v8 - 0x7f04) = 0;
        v7++;
        v5 += 4;
        v6 += 4;
    }
    // 0x1d00e794
    *(int32_t*)0xa0000210 = -0x5ffffbf0;
    *(int32_t*)0xbf885300 = 13;
    *(int32_t*)0xa0000404 = __asm_ext(v4 - 0x7f10, 0, 29);
    *(int16_t *)-0x5ffffbfe = (int16_t)__asm_ins(64, 0, 10);
    *(int16_t *)-0x5ffffc00 = 132;
    *(char *)(v4 - 0x7f20) = 0;
    *(int32_t *)(v4 - 0x7ee4) = 0;
    return 132;
}

// Address range: 0x1d010328 - 0x1d010338
int32_t function_1d010328(int32_t a1) {
    // 0x1d010328
    int32_t v1; // 0x1d010328
    return (int32_t)*(char *)(a1 - 0x7f3c + v1);
}

// Address range: 0x1d010870 - 0x1d010aa4
int32_t function_1d010870(int32_t a1) {
    switch (a1) {
        case 3: {
            // 0x1d0108a8
            *(int32_t*)0xbf8860e4 = 512;
            *(int32_t*)0xbf8860c4 = 512;
            *(int32_t*)0xbf805820 = 160;
            while ((*(int32_t*)0xbf805810 & 0x1f000000) == 0) {
                // continue -> 0x1d01093c
            }
            // 0x1d0109d0
            *(int32_t*)0xbf805820 = 0;
            while ((*(int32_t*)0xbf805810 & 0x1f000000) == 0) {
                // continue -> 0x1d0109dc
            }
            // 0x1d0109ec
            *(int32_t*)0xbf8860e8 = 512;
            *(int32_t*)0xbf8860c4 = 512;
            return 0;
        }
        case 4: {
            // 0x1d0108c4
            *(int32_t*)0xbf886064 = 256;
            *(int32_t*)0xbf886044 = 256;
            *(int32_t*)0xbf805c20 = 160;
            while ((*(int32_t*)0xbf805c10 & 0x1f000000) == 0) {
                // continue -> 0x1d01096c
            }
            // 0x1d0109fc
            *(int32_t*)0xbf805c20 = 0;
            while ((*(int32_t*)0xbf805c10 & 0x1f000000) == 0) {
                // continue -> 0x1d010a08
            }
            // 0x1d010a18
            *(int32_t*)0xbf886068 = 256;
            *(int32_t*)0xbf886044 = 256;
            return 0;
        }
        case 2: {
            // 0x1d01088c
            *(int32_t*)0xbf8861a4 = 512;
            *(int32_t*)0xbf886184 = 512;
            *(int32_t*)0xbf805a20 = 160;
            while ((*(int32_t*)0xbf805a10 & 0x1f000000) == 0) {
                // continue -> 0x1d01090c
            }
            // 0x1d0109a4
            *(int32_t*)0xbf805a20 = 0;
            while ((*(int32_t*)0xbf805a10 & 0x1f000000) == 0) {
                // continue -> 0x1d0109b0
            }
            // 0x1d0109c0
            *(int32_t*)0xbf8861a8 = 512;
            *(int32_t*)0xbf886184 = 512;
            return 0;
        }
    }
    // 0x1d010a9c
    return 0;
}

// Address range: 0x1d010e88 - 0x1d011040
int32_t function_1d010e88(int32_t a1, uint32_t a2) {
    switch (a1) {
        case 3: {
            // 0x1d010ed8
            *(int32_t*)0xbf8860e4 = 512;
            *(int32_t*)0xbf8860c4 = 512;
            *(int32_t*)0xbf805820 = (1 << a2 % 4) % 128 | 128;
            while ((*(int32_t*)0xbf805810 & 0x1f000000) == 0) {
                // continue -> 0x1d010f90
            }
            // 0x1d01100c
            *(int32_t*)0xbf8860e8 = 512;
            *(int32_t*)0xbf8860c4 = 512;
            return 512;
        }
        case 4: {
            // 0x1d010f00
            *(int32_t*)0xbf886064 = 256;
            *(int32_t*)0xbf886044 = 256;
            *(int32_t*)0xbf805c20 = (1 << a2 % 4) % 128 | 128;
            while ((*(int32_t*)0xbf805c10 & 0x1f000000) == 0) {
                // continue -> 0x1d010fbc
            }
            // 0x1d011028
            *(int32_t*)0xbf886068 = 256;
            *(int32_t*)0xbf886044 = 256;
            return 256;
        }
        case 2: {
            // 0x1d010eac
            *(int32_t*)0xbf8861a4 = 512;
            *(int32_t*)0xbf886184 = 512;
            *(int32_t*)0xbf805a20 = (1 << a2 % 4) % 128 | 128;
            while ((*(int32_t*)0xbf805a10 & 0x1f000000) == 0) {
                // continue -> 0x1d010f64
            }
            // 0x1d010ff0
            *(int32_t*)0xbf8861a8 = 512;
            *(int32_t*)0xbf886184 = 512;
            // 0x1d011000
            return 512;
        }
    }
    // 0x1d011000
    return 512;
}

// Address range: 0x1d011218 - 0x1d0114f4
int32_t function_1d011218(int32_t a1, int32_t a2, uint32_t a3, int32_t a4, int32_t a5, uint32_t a6) {
    switch (a1) {
        case 3: {
            // 0x1d011270
            *(int32_t*)0xbf8860e4 = 512;
            *(int32_t*)0xbf8860c4 = 512;
            // break -> 0x1d0112a4
            break;
        }
        case 4: {
            // 0x1d01128c
            *(int32_t*)0xbf886064 = 256;
            *(int32_t*)0xbf886044 = 256;
            // break -> 0x1d0112a4
            break;
        }
        case 2: {
            // 0x1d011254
            *(int32_t*)0xbf8861a4 = 512;
            *(int32_t*)0xbf886184 = 512;
            // break -> 0x1d0112a4
            break;
        }
    }
    char v1; // bp-7, 0x1d011218
    if (a4 == 0) {
        // 0x1d0112e4
        v1 = a3 / 8;
    } else {
        // 0x1d0112b4
        v1 = a3 / 0x200000;
        __asm_ins(0, 0, 5);
        __asm_ext(a3, 16, 2);
    }
    int32_t * v2 = (int32_t*)0xbf805a20; // 0x1d011218
    int32_t * v3 = (int32_t*)0xbf805a10; // 0x1d011218
    int32_t result = 2; // 0x1d011218
    switch (a1) {
        case 3: {
            // 0x1d011344
            v2 = (int32_t*)0xbf805820;
            v3 = (int32_t*)0xbf805810;
            goto lab_0x1d011354;
        }
        case 4: {
            // 0x1d011330
            v2 = (int32_t*)0xbf805c20;
            v3 = (int32_t*)0xbf805c10;
            goto lab_0x1d011354;
        }
        case 2: {
            goto lab_0x1d011354;
        }
        default: {
            return result;
        }
    }
  lab_0x1d011354:;
    uint32_t v4 = a6 % 256; // 0x1d01121c
    int32_t v5 = v4 < 8 ? v4 : 8;
    int32_t v6 = &v1;
    *v2 = (int32_t)*(char *)(v6 - 1);
    int32_t v7 = v6 + 1; // 0x1d011368
    int32_t v8; // bp-2, 0x1d011218
    while (v6 != (int32_t)&v8) {
        // 0x1d011360
        v6 = v7;
        *v2 = (int32_t)*(char *)(v6 - 1);
        v7 = v6 + 1;
    }
    // 0x1d011378
    while ((*v3 & 0x1e000000) < 0x6000000) {
        // continue -> 0x1d011378
    }
    int32_t * v9 = (int32_t*)0xbf805a20; // 0x1d011218
    int32_t * v10 = (int32_t*)0xbf805a10; // 0x1d011218
    result = 2;
    switch (a1) {
        case 3: {
            // 0x1d0113ec
            v9 = (int32_t*)0xbf805820;
            v10 = (int32_t*)0xbf805810;
            goto lab_0x1d0113fc;
        }
        case 4: {
            // 0x1d0113d8
            v9 = (int32_t*)0xbf805c20;
            v10 = (int32_t*)0xbf805c10;
            goto lab_0x1d0113fc;
        }
        case 2: {
            goto lab_0x1d0113fc;
        }
        default: {
            return result;
        }
    }
  lab_0x1d0113fc:
    // 0x1d0113fc
    if (a5 == 0) {
        if (v5 != 0) {
            // 0x1d011438
            *v9 = 0;
        }
    } else {
        // 0x1d011414
        if (v5 != 0) {
            int32_t v11 = a5 + 1;
            *v9 = (int32_t)*(char *)a5;
            int32_t v12 = v11; // 0x1d01142c
            while (v11 != v5 + a5) {
                // 0x1d011420
                v11 = v12 + 1;
                *v9 = (int32_t)*(char *)v12;
                v12 = v11;
            }
        }
    }
    // 0x1d01144c
    while ((*v10 & 0x1f000000) < 0x1000000 * v5) {
        // continue -> 0x1d011450
    }
    // 0x1d011484
    result = 2;
    switch (a1) {
        case 3: {
            // 0x1d0114b8
            *(int32_t*)0xbf8860e8 = 512;
            *(int32_t*)0xbf8860c4 = 512;
            result = 512;
            // break -> 0x1d0114ec
            break;
        }
        case 4: {
            // 0x1d0114d4
            *(int32_t*)0xbf886068 = 256;
            *(int32_t*)0xbf886044 = 256;
            result = 256;
            // break -> 0x1d0114ec
            break;
        }
        case 2: {
            // 0x1d01149c
            *(int32_t*)0xbf8861a8 = 512;
            *(int32_t*)0xbf886184 = 512;
            result = 512;
            // break -> 0x1d0114ec
            break;
        }
    }
    // 0x1d0114ec
    return result;
}

// Address range: 0x1d0133c0 - 0x1d013650
int32_t function_1d0133c0(int32_t * a1) {
    int32_t v1 = (int32_t)a1;
    int32_t v2; // 0x1d0133c0
    if ((*(int32_t *)(v2 - 0x7f34) & 32) != 0) {
        int32_t v3 = *(int32_t*)0xa0000cf8; // 0x1d0133e8
        uint32_t v4 = *(int32_t*)0xa0000cf4; // 0x1d0133f0
        uint32_t v5 = v4 % 0x1000; // 0x1d0133f4
        if (v5 != (v3 + 1) % 0x1000) {
            int32_t * v6 = (int32_t *)(v1 + 4); // 0x1d013418
            uint32_t v7 = *v6; // 0x1d013418
            int32_t v8 = __asm_ext(v7, 28, 1); // 0x1d01341c
            int32_t v9; // 0x1d0133c0
            if (v8 == 0) {
                // 0x1d013444
                v9 = v4 % 2048;
            } else {
                // 0x1d013428
                v9 = __asm_ext(*v6, 10, 18) | 0x40000 * v5 & 0x1ffc0000;
            }
            int32_t v10 = 16 * v3 & 0xfff0; // 0x1d013404
            uint32_t v11 = v7 % 16; // 0x1d013424
            __asm_ins(v9, 0, 29);
            __asm_ins(v8, 29, 1);
            __asm_ins(v11, 30, 2);
            *(int32_t *)(v10 - 0x5ffff300) = __asm_ins(v11 / 4, 30, 2);
            __asm_ins(5, 27, 3);
            *(int32_t *)(v10 - 0x5ffff304) = __asm_ins(*(int32_t *)(v2 - 0x7f30), 0, 27);
            __asm_lwl(*(int32_t *)(v1 + 11));
            int32_t v12 = __asm_lwr(*(int32_t *)(v1 + 8)); // 0x1d013488
            __asm_lwl(*(int32_t *)(v1 + 15));
            int32_t v13 = __asm_lwr(*(int32_t *)(v1 + 12)); // 0x1d013490
            *(int32_t *)(v10 - 0x5ffff2fc) = v12;
            *(int32_t *)(v10 - 0x5ffff2f8) = v13;
            uint32_t v14 = (*(int32_t*)0xa0000cf8 + 1) % 0x1000; // 0x1d0134ac
            if (*(int32_t*)0xa0000cf4 % 0x1000 != v14) {
                // 0x1d0134c0
                *(int32_t*)0xa0000cf8 = v14;
            }
        }
    }
    int32_t v15 = *(int32_t*)0xa00008e8 % 64; // 0x1d013564
    int32_t result2; // 0x1d0133c0
    if (v15 == *(int32_t*)0xa00008ec % 64) {
      lab_0x1d01362c:;
        int32_t result = function_1d014e5c(a1); // 0x1d013630
        if (result != 0) {
            // 0x1d01363c
            return result;
        }
        int32_t v16 = *(int32_t*)0xa00008ec; // 0x1d0135c0
        uint32_t v17 = (v16 + 1) % 64; // 0x1d0135cc
        if (*(int32_t*)0xa00008e8 % 64 == v17) {
            // 0x1d013618
            *(int32_t*)0xa00008f0 = *(int32_t*)0xa00008f0 + 1;
            result2 = 0;
        } else {
            int32_t v18 = 16 * v16 & 1008; // 0x1d0135e0
            *(int32_t *)(v18 - 0x5ffff70c) = v17;
            *(int32_t *)(v18 - 0x5ffff708) = *(int32_t *)(v1 + 4);
            *(int32_t *)(v18 - 0x5ffff704) = *(int32_t *)(v1 + 8);
            *(int32_t *)(v18 - 0x5ffff700) = *(int32_t *)(v1 + 12);
            *(int32_t*)0xa00008ec = v17;
            result2 = 1;
        }
        // 0x1d01363c
        return result2;
    }
    int32_t v19 = *(int32_t *)(16 * v15 - 0x5ffff70c); // bp-32, 0x1d013594
    while (function_1d014e5c(&v19) != 0) {
        int32_t v20 = *(int32_t*)0xa00008e8; // 0x1d0135b0
        int32_t v21 = *(int32_t*)0xa00008ec; // 0x1d0134d4
        int32_t v22 = v21; // 0x1d0134e0
        int32_t v23 = v20; // 0x1d0134e0
        if ((v21 ^ v20) % 64 != 0) {
            // 0x1d0134e4
            v23 = (v20 + 1) % 64;
            *(int32_t*)0xa00008e8 = v23;
            v22 = *(int32_t*)0xa00008ec;
        }
        int32_t v24 = v23 % 64; // 0x1d013564
        if (v24 == v22 % 64) {
            goto lab_0x1d01362c;
        }
        v19 = *(int32_t *)(16 * v24 - 0x5ffff70c);
    }
    int32_t v25 = *(int32_t*)0xa00008ec; // 0x1d0134f4
    uint32_t v26 = (v25 + 1) % 64; // 0x1d013500
    if (*(int32_t*)0xa00008e8 % 64 == v26) {
        // 0x1d01354c
        *(int32_t*)0xa00008f0 = *(int32_t*)0xa00008f0 + 1;
        result2 = 0;
    } else {
        int32_t v27 = 16 * v25 & 1008; // 0x1d013514
        *(int32_t *)(v27 - 0x5ffff70c) = v26;
        *(int32_t *)(v27 - 0x5ffff708) = *(int32_t *)(v1 + 4);
        *(int32_t *)(v27 - 0x5ffff704) = *(int32_t *)(v1 + 8);
        *(int32_t *)(v27 - 0x5ffff700) = *(int32_t *)(v1 + 12);
        *(int32_t*)0xa00008ec = v26;
        result2 = 1;
    }
    // 0x1d01363c
    return result2;
}

// Address range: 0x1d013650 - 0x1d0138e0
int32_t pthread_cond_destroy2(int32_t * a1) {
    int32_t v1 = (int32_t)a1;
    int32_t v2; // 0x1d013650
    if ((*(int32_t *)(v2 - 0x7f34) & 128) != 0) {
        int32_t v3 = *(int32_t*)0xa0000cf8; // 0x1d013678
        uint32_t v4 = *(int32_t*)0xa0000cf4; // 0x1d013680
        uint32_t v5 = v4 % 0x1000; // 0x1d013684
        if (v5 != (v3 + 1) % 0x1000) {
            int32_t * v6 = (int32_t *)(v1 + 4); // 0x1d0136a8
            uint32_t v7 = *v6; // 0x1d0136a8
            int32_t v8 = __asm_ext(v7, 28, 1); // 0x1d0136ac
            int32_t v9; // 0x1d013650
            if (v8 == 0) {
                // 0x1d0136d4
                v9 = v4 % 2048;
            } else {
                // 0x1d0136b8
                v9 = __asm_ext(*v6, 10, 18) | 0x40000 * v5 & 0x1ffc0000;
            }
            int32_t v10 = 16 * v3 & 0xfff0; // 0x1d013694
            uint32_t v11 = v7 % 16; // 0x1d0136b4
            __asm_ins(v9, 0, 29);
            __asm_ins(v8, 29, 1);
            __asm_ins(v11, 30, 2);
            *(int32_t *)(v10 - 0x5ffff300) = __asm_ins(v11 / 4, 30, 2);
            __asm_ins(7, 27, 3);
            *(int32_t *)(v10 - 0x5ffff304) = __asm_ins(*(int32_t *)(v2 - 0x7f30), 0, 27);
            __asm_lwl(*(int32_t *)(v1 + 11));
            int32_t v12 = __asm_lwr(*(int32_t *)(v1 + 8)); // 0x1d013718
            __asm_lwl(*(int32_t *)(v1 + 15));
            int32_t v13 = __asm_lwr(*(int32_t *)(v1 + 12)); // 0x1d013720
            *(int32_t *)(v10 - 0x5ffff2fc) = v12;
            *(int32_t *)(v10 - 0x5ffff2f8) = v13;
            uint32_t v14 = (*(int32_t*)0xa0000cf8 + 1) % 0x1000; // 0x1d01373c
            if (*(int32_t*)0xa0000cf4 % 0x1000 != v14) {
                // 0x1d013750
                *(int32_t*)0xa0000cf8 = v14;
            }
        }
    }
    int32_t v15 = *(int32_t*)0xa00004dc % 64; // 0x1d0137f4
    int32_t result2; // 0x1d013650
    if (v15 == *(int32_t*)0xa00004e0 % 64) {
      lab_0x1d0138bc:;
        int32_t result = function_1d015134(a1); // 0x1d0138c0
        if (result != 0) {
            // 0x1d0138cc
            return result;
        }
        int32_t v16 = *(int32_t*)0xa00004e0; // 0x1d013850
        uint32_t v17 = (v16 + 1) % 64; // 0x1d01385c
        if (*(int32_t*)0xa00004dc % 64 == v17) {
            // 0x1d0138a8
            *(int32_t*)0xa00004e4 = *(int32_t*)0xa00004e4 + 1;
            result2 = 0;
        } else {
            int32_t v18 = 16 * v16 & 1008; // 0x1d013870
            *(int32_t *)(v18 - 0x5ffffb18) = v17;
            *(int32_t *)(v18 - 0x5ffffb14) = *(int32_t *)(v1 + 4);
            *(int32_t *)(v18 - 0x5ffffb10) = *(int32_t *)(v1 + 8);
            *(int32_t *)(v18 - 0x5ffffb0c) = *(int32_t *)(v1 + 12);
            *(int32_t*)0xa00004e0 = v17;
            result2 = 1;
        }
        // 0x1d0138cc
        return result2;
    }
    int32_t v19 = *(int32_t *)(16 * v15 - 0x5ffffb18); // bp-32, 0x1d013824
    while (function_1d015134(&v19) != 0) {
        int32_t v20 = *(int32_t*)0xa00004dc; // 0x1d013840
        int32_t v21 = *(int32_t*)0xa00004e0; // 0x1d013764
        int32_t v22 = v21; // 0x1d013770
        int32_t v23 = v20; // 0x1d013770
        if ((v21 ^ v20) % 64 != 0) {
            // 0x1d013774
            v23 = (v20 + 1) % 64;
            *(int32_t*)0xa00004dc = v23;
            v22 = *(int32_t*)0xa00004e0;
        }
        int32_t v24 = v23 % 64; // 0x1d0137f4
        if (v24 == v22 % 64) {
            goto lab_0x1d0138bc;
        }
        v19 = *(int32_t *)(16 * v24 - 0x5ffffb18);
    }
    int32_t v25 = *(int32_t*)0xa00004e0; // 0x1d013784
    uint32_t v26 = (v25 + 1) % 64; // 0x1d013790
    if (*(int32_t*)0xa00004dc % 64 == v26) {
        // 0x1d0137dc
        *(int32_t*)0xa00004e4 = *(int32_t*)0xa00004e4 + 1;
        result2 = 0;
    } else {
        int32_t v27 = 16 * v25 & 1008; // 0x1d0137a4
        *(int32_t *)(v27 - 0x5ffffb18) = v26;
        *(int32_t *)(v27 - 0x5ffffb14) = *(int32_t *)(v1 + 4);
        *(int32_t *)(v27 - 0x5ffffb10) = *(int32_t *)(v1 + 8);
        *(int32_t *)(v27 - 0x5ffffb0c) = *(int32_t *)(v1 + 12);
        *(int32_t*)0xa00004e0 = v26;
        result2 = 1;
    }
    // 0x1d0138cc
    return result2;
}

// Address range: 0x1d0139ec - 0x1d013af8
int32_t pthread_cond_destroy(int32_t * a1) {
    uint32_t v1 = (int32_t)a1;
    int32_t v2; // 0x1d0139ec
    if ((*(int32_t *)(v2 - 0x7f34) & 8) == 0) {
        // 0x1d013ae4
        return function_1d014b44(v1);
    }
    int32_t v3 = *(int32_t*)0xa0000cf8; // 0x1d013a08
    if ((*(int32_t*)0xa0000cf4 ^ v3 + 1) % 0x1000 == 0) {
        // 0x1d013ae4
        return function_1d014b44(v1);
    }
    int32_t * v4 = (int32_t *)(v1 + 4); // 0x1d013a38
    uint32_t v5 = *v4; // 0x1d013a38
    int32_t v6 = __asm_ext(v5, 28, 1); // 0x1d013a3c
    int32_t v7; // 0x1d0139ec
    if (v6 == 0) {
        // 0x1d013a64
        v7 = v1 % 2048;
    } else {
        // 0x1d013a48
        v7 = __asm_ext(*v4, 10, 18) | 0x40000 * v1 & 0x1ffc0000;
    }
    int32_t v8 = 16 * v3 & 0xfff0; // 0x1d013a24
    uint32_t v9 = v5 % 16; // 0x1d013a44
    __asm_ins(v7, 0, 29);
    __asm_ins(v6, 29, 1);
    __asm_ins(v9, 30, 2);
    *(int32_t *)(v8 - 0x5ffff300) = __asm_ins(v9 / 4, 30, 2);
    __asm_ins(3, 27, 3);
    *(int32_t *)(v8 - 0x5ffff304) = __asm_ins(*(int32_t *)(v2 - 0x7f30), 0, 27);
    __asm_lwl(*(int32_t *)(v1 + 11));
    int32_t v10 = __asm_lwr(*(int32_t *)(v1 + 8)); // 0x1d013aa8
    __asm_lwl(*(int32_t *)(v1 + 15));
    int32_t v11 = __asm_lwr(*(int32_t *)(v1 + 12)); // 0x1d013ab0
    *(int32_t *)(v8 - 0x5ffff2fc) = v10;
    *(int32_t *)(v8 - 0x5ffff2f8) = v11;
    uint32_t v12 = (*(int32_t*)0xa0000cf8 + 1) % 0x1000; // 0x1d013acc
    if (*(int32_t*)0xa0000cf4 % 0x1000 != v12) {
        // 0x1d013ae0
        *(int32_t*)0xa0000cf8 = v12;
    }
    // 0x1d013ae4
    return function_1d014b44(v1);
}

// Address range: 0x1d014b44 - 0x1d014bd4
int32_t function_1d014b44(int32_t a1) {
    int32_t v1 = function_1d01ae28(1, 1); // 0x1d014b5c
    int32_t result = 0; // 0x1d014b60
    if (v1 != 0) {
        // 0x1d014b68
        __asm_lwl(*(int32_t *)(a1 + 3));
        int32_t v2 = __asm_lwr(1); // 0x1d014b6c
        __asm_lwl(*(int32_t *)(a1 + 7));
        int32_t v3 = __asm_lwr(*(int32_t *)(a1 + 4)); // 0x1d014b74
        __asm_lwl(*(int32_t *)(a1 + 11));
        int32_t v4 = __asm_lwr(*(int32_t *)(a1 + 8)); // 0x1d014b7c
        __asm_lwl(*(int32_t *)(a1 + 15));
        int32_t v5 = __asm_lwr(*(int32_t *)(a1 + 12)); // 0x1d014b84
        __asm_swl(v2, *(int32_t *)(v1 + 3));
        __asm_swr(v2, *(int32_t *)v1);
        __asm_swl(v3, *(int32_t *)(v1 + 7));
        __asm_swr(v3, *(int32_t *)(v1 + 4));
        __asm_swl(v4, *(int32_t *)(v1 + 11));
        __asm_swr(v4, *(int32_t *)(v1 + 8));
        __asm_swl(v5, *(int32_t *)(v1 + 15));
        __asm_swr(v5, *(int32_t *)(v1 + 12));
        function_1d01b078(1, 1);
        function_1d01b0a4(1, 1);
        result = 1;
    }
    // 0x1d014bc4
    return result;
}

// Address range: 0x1d014bd4 - 0x1d014c64
int32_t function_1d014bd4(int32_t * a1) {
    int32_t v1 = function_1d01ae28(1, 2); // 0x1d014bec
    int32_t result = 0; // 0x1d014bf0
    if (v1 != 0) {
        int32_t v2 = (int32_t)a1;
        __asm_lwl(*(int32_t *)(v2 + 3));
        int32_t v3 = __asm_lwr(1); // 0x1d014bfc
        __asm_lwl(*(int32_t *)(v2 + 7));
        int32_t v4 = __asm_lwr(*(int32_t *)(v2 + 4)); // 0x1d014c04
        __asm_lwl(*(int32_t *)(v2 + 11));
        int32_t v5 = __asm_lwr(*(int32_t *)(v2 + 8)); // 0x1d014c0c
        __asm_lwl(*(int32_t *)(v2 + 15));
        int32_t v6 = __asm_lwr(*(int32_t *)(v2 + 12)); // 0x1d014c14
        __asm_swl(v3, *(int32_t *)(v1 + 3));
        __asm_swr(v3, *(int32_t *)v1);
        __asm_swl(v4, *(int32_t *)(v1 + 7));
        __asm_swr(v4, *(int32_t *)(v1 + 4));
        __asm_swl(v5, *(int32_t *)(v1 + 11));
        __asm_swr(v5, *(int32_t *)(v1 + 8));
        __asm_swl(v6, *(int32_t *)(v1 + 15));
        __asm_swr(v6, *(int32_t *)(v1 + 12));
        function_1d01b078(1, 2);
        function_1d01b0a4(1, 2);
        result = 1;
    }
    // 0x1d014c54
    return result;
}

// Address range: 0x1d014e5c - 0x1d014f10
int32_t function_1d014e5c(int32_t * a1) {
    int32_t result = function_1d010328(3); // 0x1d014e74
    if (result == 0 || (function_1d010870(3) & 4) != 0) {
        // 0x1d014efc
        return 0;
    }
    int32_t v1 = (int32_t)a1;
    int32_t * v2 = (int32_t *)(v1 + 4); // 0x1d014e98
    uint32_t v3 = *v2; // 0x1d014e98
    int32_t v4 = __asm_ext(v3, 28, 1); // 0x1d014e9c
    int32_t v5 = 3; // 0x1d014ea4
    if (v4 != 0) {
        // 0x1d014ea8
        v5 = __asm_ext(*v2, 10, 18) | 0xc0000;
    }
    // 0x1d014ecc
    function_1d011218(3, 0, v5, v4, v1 + 8, v3 % 16);
    function_1d010e88(3, 0);
    // 0x1d014efc
    return result;
}

// Address range: 0x1d015134 - 0x1d0151e8
int32_t function_1d015134(int32_t * a1) {
    int32_t result = function_1d010328(2); // 0x1d01514c
    if (result == 0 || (function_1d010870(2) & 4) != 0) {
        // 0x1d0151d4
        return 0;
    }
    int32_t v1 = (int32_t)a1;
    int32_t * v2 = (int32_t *)(v1 + 4); // 0x1d015170
    uint32_t v3 = *v2; // 0x1d015170
    int32_t v4 = __asm_ext(v3, 28, 1); // 0x1d015174
    int32_t v5 = 2; // 0x1d01517c
    if (v4 != 0) {
        // 0x1d015180
        v5 = __asm_ext(*v2, 10, 18) | 0x80000;
    }
    // 0x1d0151a4
    function_1d011218(2, 0, v5, v4, v1 + 8, v3 % 16);
    function_1d010e88(2, 0);
    // 0x1d0151d4
    return result;
}

// Address range: 0x1d015f10 - 0x1d0160a8
int32_t function_1d015f10(int32_t * a1) {
    int32_t v1 = (int32_t)a1 + 4; // 0x1d015f28
    uint16_t v2 = *(int16_t *)v1; // 0x1d015f28
    int32_t v3; // 0x1d015f10
    *(int32_t *)(v3 - 0x7fac) = (int32_t)v2;
    *(int32_t *)(v3 - 0x7fa8) = 100;
    int32_t v4 = *(int32_t *)v1; // 0x1d015f38
    int32_t v5 = __asm_ext(v4, 24, 1); // 0x1d015f3c
    int32_t v6 = __asm_ext(v4, 25, 1); // 0x1d015f44
    uint32_t v7 = __asm_ext(v4, 27, 1); // 0x1d015f4c
    if (*(int32_t*)0xa0013594 == 0) {
        goto lab_0x1d016070;
    } else {
        if (v7 % 256 == 0) {
            goto lab_0x1d015fb0;
        } else {
            // 0x1d015f74
            if (*(char*)0xa001359b == 0) {
                // 0x1d015f84
                *(char*)0xa0013589 = 1;
                int32_t * v8 = (int32_t *)(v3 - 0x7fb8); // 0x1d015f90
                if (*v8 == 0) {
                    // 0x1d015f9c
                    *v8 = 1;
                    *(int32_t *)(v3 - 0x7fbc) = 3;
                }
                goto lab_0x1d016070;
            } else {
                goto lab_0x1d015fb0;
            }
        }
    }
  lab_0x1d016070:
    // 0x1d016070
    *(int32_t*)0xa0013594 = 100;
    *(char*)0xa0013598 = (char)v5;
    *(char*)0xa0013599 = (char)v6;
    *(char*)0xa001359a = 0;
    *(char*)0xa001359b = (char)v7;
    *(char*)0xa001359c = (char)((v4 & 0x74000000) != 0);
    return -0x5ffecaa8;
  lab_0x1d015fb0:
    // 0x1d015fb0
    if (*(char*)0xa0013588 != 0) {
        // 0x1d015fbc
        if (*(char*)0xa0013598 != 0) {
            if ((v6 | v5) % 256 == 0) {
                // 0x1d015fdc
                if (*(char*)0xa0013569 == 0) {
                    // 0x1d015fec
                    if (*(char*)0xa0013581 == 0) {
                        // 0x1d015ffc
                        if (*(char*)0xa0013599 == 0) {
                            char v9 = *(char *)(v3 - 0x7fb4); // 0x1d016014
                            if (v2 == 0 != (*(int32_t *)(v3 - 0x7fb0) == 0 || v9 == 1)) {
                                // 0x1d01602c
                                if (function_1d01acd8(v9) == 0) {
                                    // 0x1d01603c
                                    *(char*)0xa0013589 = 1;
                                    *(char *)(v3 - 0x7fe8) = 0;
                                    int32_t * v10 = (int32_t *)(v3 - 0x7fb8); // 0x1d01604c
                                    if (*v10 == 0) {
                                        // 0x1d016058
                                        *v10 = 1;
                                        *(int32_t *)(v3 - 0x7fbc) = 13;
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    goto lab_0x1d016070;
}

// Address range: 0x1d016100 - 0x1d016108
int32_t exit(void) {
    // 0x1d016100
    int32_t v1; // 0x1d016100
    return *(int32_t *)(v1 - 0x7fb8);
}

// Address range: 0x1d01612c - 0x1d016144
int32_t function_1d01612c(void) {
    // 0x1d01612c
    int32_t v1; // 0x1d01612c
    int32_t v2 = *(int32_t *)(v1 - 0x7fb8); // 0x1d016130
    return v2 == 1 ? (int32_t)*(char *)(v1 - 0x7fe8) : 0;
}

// Address range: 0x1d017444 - 0x1d017458
int32_t function_1d017444(void) {
    // 0x1d017444
    return (int32_t)*(char*)0xa00001ee;
}

// Address range: 0x1d01957c - 0x1d019714
int32_t pthread_cond_destroy3(void) {
    // 0x1d01957c
    int32_t v1; // 0x1d01957c
    char * v2 = (char *)(v1 - 0x7f10); // 0x1d01957c
    if (*v2 % 32 != 1) {
        // 0x1d01970c
        return 1;
    }
    char result = *(char *)(v1 - 0x7f0c); // 0x1d019590
    if (result != 0) {
        // 0x1d01970c
        return result;
    }
    char * v3 = (char *)(v1 - 0x7f0f); // 0x1d0195a0
    if (*v3 == 6) {
        // 0x1d0195b4
        switch (*(char *)(v1 - 0x7f0d)) {
            case 33: {
                // 0x1d0195d8
                if (*(char *)(v1 - 0x7f20) == 1) {
                    // 0x1d0195ec
                    *(int32_t*)0xa0000480 = -0x62fe5ec6;
                    *(int16_t *)-0x5ffffb78 = 9;
                    *(char*)0xa0000484 = -64;
                }
                // break -> 0x1d019634
                break;
            }
            case 34: {
                // 0x1d019614
                *(int32_t*)0xa0000480 = -0x62fe5f1c;
                *(int16_t *)-0x5ffffb78 = 29;
                *(char*)0xa0000484 = -64;
                // break -> 0x1d019634
                break;
            }
        }
    }
    // 0x1d019634
    if ((*v2 & 96) != 32) {
        // 0x1d01970c
        return 32;
    }
    unsigned char result4 = *v3; // 0x1d019648
    if (result4 == 3) {
        // 0x1d0196d0
        *(int32_t*)0xa0000480 = v1 - 0x7ecf;
        *(int16_t *)-0x5ffffb78 = 1;
        *(char*)0xa0000484 = -127;
        return -0x5ffffb80;
    }
    if (result4 < 4) {
        // 0x1d019664
        if (result4 != 2) {
            // 0x1d019670
            return -0x60000000;
        }
        // 0x1d019690
        *(int32_t*)0xa0000480 = v1 - 0x7ed0;
        *(int16_t *)-0x5ffffb78 = 1;
        *(char*)0xa0000484 = -63;
        return -0x5ffffb80;
    }
    // 0x1d019678
    switch (result4) {
        case 10: {
            // 0x1d0196b4
            *(char*)0xa0000484 = -128;
            unsigned char result2 = *(char *)(v1 - 0x7f0d); // 0x1d0196c4
            *(char *)(v1 - 0x7ed0) = result2;
            return result2;
        }
        case 11: {
            // 0x1d0196f8
            *(char*)0xa0000484 = -128;
            char result3 = *(char *)(v1 - 0x7f0e); // 0x1d019704
            *(char *)(v1 - 0x7ecf) = result3;
            // 0x1d01970c
            return result3;
        }
    }
    // 0x1d019670
    return result4;
}

// Address range: 0x1d01acd8 - 0x1d01ace4
int32_t function_1d01acd8(char a1) {
    // 0x1d01acd8
    return (int32_t)*(char*)0x9d017b84;
}

// Address range: 0x1d01ae28 - 0x1d01ae6c
int32_t function_1d01ae28(int32_t a1, int32_t a2) {
    int32_t v1 = *(int32_t *)(4 * a1 - 0x5ffeccc8) + 64 * a2; // 0x1d01ae40
    if (__asm_ext(*(int32_t *)(v1 + 864), 10, 1) == 0) {
        // 0x1d01ae64
        return 0;
    }
    // 0x1d01ae54
    return *(int32_t *)(v1 + 880) | -0x60000000;
}

// Address range: 0x1d01b078 - 0x1d01b0a4
int32_t function_1d01b078(int32_t a1, int32_t a2) {
    int32_t result = *(int32_t *)(4 * a1 - 0x5ffeccc8) + 64 * a2; // 0x1d01b090
    *(int32_t *)(result + 856) = 0x2000;
    return result;
}

// Address range: 0x1d01b0a4 - 0x1d01b0d0
int32_t function_1d01b0a4(int32_t a1, int32_t a2) {
    int32_t result = *(int32_t *)(4 * a1 - 0x5ffeccc8) + 64 * a2; // 0x1d01b0bc
    *(int32_t *)(result + 856) = 8;
    return result;
}

// Address range: 0x1d01b2c0 - 0x1d01b2c8
int32_t exit3(void) {
    // 0x1d01b2c0
    int32_t result; // 0x1d01b2c0
    __asm_di(result);
    return result;
}

// --------------------- Meta-Information ---------------------

// Detected functions: 25
