//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int32_t exit(void);
int32_t exit2(void);
int32_t function_1d026c7c(int32_t result, uint16_t a2, int32_t a3);
int32_t Stolx(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t Stolx2(int32_t a1, int32_t a2, uint32_t a3, int32_t a4);

// ------------------------ Functions -------------------------

// Address range: 0x1d015c34 - 0x1d015e5c
int32_t exit(void) {
    // 0x1d015c34
    *(int32_t*)0xbf881074 = 0x2000000;
    *(int32_t*)0xbf885220 = 255;
    *(int32_t*)0xbf885200 = 255;
    *(int32_t*)0xbf885300 = 0;
    *(int32_t*)0xbf8852e0 = 0;
    *(int32_t*)0xbf885230 = 159;
    *(int32_t*)0xbf885210 = 159;
    uint32_t v1 = *(int32_t*)0xbf885070 % 16; // 0x1d015c6c
    *(int32_t*)0xbf885070 = v1;
    uint32_t v2 = __asm_ext(-0x5ffffc00, 0, 29); // 0x1d015c78
    *(int32_t*)0xbf885070 = v1;
    *(char*)0xbf885080 = (char)__asm_ins(1, 0, 1);
    *(int32_t*)0xbf885310 = 0;
    *(int32_t*)0xbf8852d0 = v2 / 0x1000000;
    *(int32_t*)0xbf885320 = 0;
    *(int32_t*)0xbf8852c0 = v2 / 0x10000;
    *(int32_t*)0xbf885330 = 0;
    *(int32_t*)0xbf885270 = v2 / 256;
    *(int32_t*)0xa0000400 = 0;
    *(int32_t*)0xa0000404 = 0;
    *(int32_t*)0xa0000408 = 0;
    *(int32_t*)0xa000040c = 0;
    *(int32_t*)0xa0000410 = 0;
    *(int32_t*)0xa0000414 = 0;
    *(int32_t*)0xa0000418 = 0;
    *(int32_t*)0xa000041c = 0;
    *(int32_t*)0xa0000420 = 0;
    *(int32_t*)0xa0000424 = 0;
    *(int32_t*)0xa0000428 = 0;
    *(int32_t*)0xa000042c = 0;
    *(int32_t*)0xa0000430 = 0;
    *(int32_t*)0xa0000434 = 0;
    *(int32_t*)0xa0000438 = 0;
    *(int32_t*)0xa000043c = 0;
    *(int32_t*)0xa0000440 = 0;
    *(int32_t*)0xa0000444 = 0;
    *(int32_t*)0xa0000448 = 0;
    *(int32_t*)0xa000044c = 0;
    *(int32_t*)0xa0000450 = 0;
    *(int32_t*)0xa0000454 = 0;
    *(int32_t*)0xa0000458 = 0;
    *(int32_t*)0xa000045c = 0;
    *(int32_t*)0xa0000460 = 0;
    *(int32_t*)0xa0000464 = 0;
    *(int32_t*)0xa0000468 = 0;
    *(int32_t*)0xa000046c = 0;
    *(int32_t*)0xa0000470 = 0;
    *(int32_t*)0xa0000474 = 0;
    *(int32_t*)0xa0000478 = 0;
    *(int32_t*)0xa000047c = 0;
    *(char*)0xbf885250 = (char)__asm_ins(1, 1, 1);
    *(int32_t*)0xbf885260 = 0;
    *(char*)0xbf885250 = (char)__asm_ins(0, 5, 1);
    *(char*)0xbf885250 = (char)__asm_ins(0, 1, 1);
    if ((*(int32_t*)0xbf885200 & 8) != 0) {
        *(int32_t*)0xbf885200 = 8;
        *(char*)0xa0000484 = 0;
        *(char*)0xa00004d4 = 0;
        *(int32_t*)0xa00004d4 = __asm_ins(0, 8, 16);
        while ((*(int32_t*)0xbf885200 & 8) != 0) {
            // 0x1d015d88
            *(int32_t*)0xbf885200 = 8;
            *(char*)0xa0000484 = 0;
            *(char*)0xa00004d4 = 0;
            *(int32_t*)0xa00004d4 = __asm_ins(0, 8, 16);
        }
    }
    // 0x1d015db0
    int32_t v3; // 0x1d015c34
    *(int32_t *)(v3 - 0x7f00) = 1;
    *(int32_t *)(v3 - 0x7ef8) = 1;
    *(int32_t *)(v3 - 0x7ec8) = 0;
    *(int32_t *)(v3 - 0x7ec4) = 0;
    *(int32_t *)(v3 - 0x7ee4) = 0;
    *(char *)(v3 - 0x7eb0) = 0;
    *(char *)(v3 - 0x7ee0) = 0;
    *(char *)(v3 - 0x7eaf) = 0;
    *(char *)(v3 - 0x7edf) = 0;
    *(char *)(v3 - 0x7eae) = 0;
    *(char *)(v3 - 0x7ede) = 0;
    *(char *)(v3 - 0x7ead) = 0;
    *(char *)(v3 - 0x7edd) = 0;
    *(int32_t*)0xbf885300 = 13;
    *(int32_t*)0xa0000404 = __asm_ext(v3 - 0x7eec, 0, 29);
    *(int16_t *)-0x5ffffbfe = (int16_t)__asm_ins(64, 0, 10);
    *(int32_t*)0xa0000200 = 0;
    *(int16_t *)-0x5ffffc00 = 132;
    *(int32_t*)0xa0000214 = 0;
    *(char *)(v3 - 0x7efc) = 0;
    *(int32_t*)0xa0000204 = 0;
    *(int32_t*)0xa0000218 = 0;
    *(int32_t*)0xa0000208 = 0;
    *(int32_t*)0xa000021c = 0;
    *(int32_t*)0xa000020c = 0;
    *(int32_t*)0xa0000210 = -0x5ffffbf0;
    *(int32_t *)(v3 - 0x7ec0) = 0;
    return -0x5ffffbf0;
}

// Address range: 0x1d0238e0 - 0x1d023bd4
int32_t Stolx2(int32_t a1, int32_t a2, uint32_t a3, int32_t a4) {
    // 0x1d0238e0
    char v1; // 0x1d0238e0
    int32_t v2; // 0x1d0238e0
    if (a4 == 0) {
        // 0x1d0238e0
        int32_t v3; // 0x1d0238e0
        v1 = v3;
    } else {
        // 0x1d023920
        *(int32_t *)a4 = 0;
        v1 = *(char *)&v2;
    }
    int32_t v4 = v1; // 0x1d023924
    int32_t v5 = *(int32_t*)0xa00001f0; // 0x1d02392c
    v2 = v5;
    int32_t v6 = a1; // 0x1d023948
    int32_t v7 = a1; // 0x1d023948
    int32_t v8 = v4; // 0x1d023948
    if ((*(int16_t *)((2 * v4 & 510) + v5) & 324) != 0) {
        v6++;
        int32_t v9 = (int32_t)*(char *)v6; // 0x1d023950
        v7 = v6;
        v8 = v9;
        while ((*(int16_t *)((2 * v9 & 510) + v5) & 324) != 0) {
            // 0x1d023950
            v6++;
            v9 = (int32_t)*(char *)v6;
            v7 = v6;
            v8 = v9;
        }
    }
    int32_t v10 = v7; // 0x1d0238e0
    int32_t v11 = 43; // 0x1d0238e0
    switch (v8) {
        case 45: {
            // 0x1d023b04
            v10 = v7 + 1;
            v11 = 45;
            // break -> 0x1d023988
            break;
        }
        case 43: {
            v10 = v7 + 1;
            v11 = 43;
            // break -> 0x1d023988
            break;
        }
    }
    if (a3 == 1 || a3 >= 37) {
        // 0x1d0239a0
        if (a2 != 0) {
            *(int32_t *)a2 = a1;
        }
        // 0x1d0239b0
        return 0;
    }
    int32_t v12 = a3; // 0x1d0238e0
    int32_t v13 = v10; // 0x1d0238e0
    char v14; // 0x1d0238e0
    int32_t v15; // 0x1d0238e0
    int32_t v16; // 0x1d0238e0
    int32_t v17; // 0x1d0238e0
    int32_t v18; // 0x1d0238e0
    int32_t v19; // 0x1d0238e0
    int32_t v20; // 0x1d0238e0
    int32_t v21; // 0x1d0238e0
    switch (a3) {
        case 0: {
            char v22 = *(char *)v10; // 0x1d023b0c
            v14 = v22;
            v21 = 10;
            v18 = v10;
            v15 = v10;
            if (v22 == 48) {
                // 0x1d023ba0
                v19 = 8;
                v16 = v10;
                if (__asm_ins(0, 5, 1) == 88) {
                    // 0x1d023bc0
                    v12 = 16;
                    v13 = v10 + 2;
                    goto lab_0x1d0239f0;
                } else {
                    goto lab_0x1d023a00;
                }
            } else {
                goto lab_0x1d023a18;
            }
        }
        case 16: {
            char v23 = *(char *)v10; // 0x1d023b60
            v14 = v23;
            v21 = 16;
            v18 = v10;
            v15 = v10;
            if (v23 == 48) {
                // 0x1d023b70
                v2 = 48;
                v20 = 16;
                v17 = v10;
                if (__asm_ins(0, 5, 1) == 88) {
                    // 0x1d023b84
                    v12 = 16;
                    v13 = v10 + 2;
                    goto lab_0x1d0239f0;
                } else {
                    goto lab_0x1d023a08;
                }
            } else {
                goto lab_0x1d023a18;
            }
        }
        default: {
            goto lab_0x1d0239f0;
        }
    }
  lab_0x1d0239f0:;
    char v24 = *(char *)v13; // 0x1d0239f0
    v19 = v12;
    v16 = v13;
    v14 = v24;
    v21 = v12;
    v18 = v13;
    v15 = v13;
    if (v24 == 48) {
        goto lab_0x1d023a00;
    } else {
        goto lab_0x1d023a18;
    }
  lab_0x1d023a00:
    // 0x1d023a00
    v2 = 48;
    v20 = v19;
    v17 = v16;
    goto lab_0x1d023a08;
  lab_0x1d023a18:;
    int16_t v28 = *(int16_t *)(*(int32_t*)0xa00139fc + 2 * (int32_t)v14); // 0x1d023a58
    int32_t v29 = function_1d026c7c(-0x62fd94cc, v28, v21); // 0x1d023a60
    int32_t v30 = v29 + 0x62fd94cc; // 0x1d023a70
    v2 = v30;
    int32_t v31 = 0; // 0x1d023a70
    int32_t v32 = v15; // 0x1d023a70
    int32_t v33 = 0; // 0x1d023a70
    int32_t v34; // 0x1d0238e0
    if (v29 != 0) {
        int32_t v35 = 0;
        int32_t v36 = 0x1000000 * v30 / 0x1000000; // 0x1d023a2c
        int32_t v37 = v36 + v35 * v21; // 0x1d023a38
        int32_t v38 = v15 + 1; // 0x1d023a3c
        int32_t v39 = *(int32_t*)0xa00139fc; // 0x1d023a50
        int16_t v40 = *(int16_t *)(2 * (int32_t)*(char *)v38 + v39); // 0x1d023a58
        int32_t v41 = function_1d026c7c(-0x62fd94cc, v40, v21); // 0x1d023a60
        int32_t v42 = v41 + 0x62fd94cc; // 0x1d023a70
        v2 = v42;
        int32_t v43 = v38; // 0x1d023a70
        v31 = v35;
        v34 = v36;
        v32 = v38;
        v33 = v37;
        while (v41 != 0) {
            // 0x1d023a2c
            v35 = v37;
            v36 = 0x1000000 * v42 / 0x1000000;
            v37 = v36 + v35 * v21;
            v38 = v43 + 1;
            v39 = *(int32_t*)0xa00139fc;
            v40 = *(int16_t *)(2 * (int32_t)*(char *)v38 + v39);
            v41 = function_1d026c7c(-0x62fd94cc, v40, v21);
            v42 = v41 + 0x62fd94cc;
            v2 = v42;
            v43 = v38;
            v31 = v35;
            v34 = v36;
            v32 = v38;
            v33 = v37;
        }
    }
    // 0x1d023a74
    if (v32 == v18) {
        // 0x1d023b8c
        if (a2 != 0) {
            // 0x1d023b98
            *(int32_t *)a2 = a1;
        }
        // 0x1d0239b0
        return 0;
    }
    uint32_t v44 = v33;
    char v45 = *(char *)(v21 - 0x62fd94f4); // 0x1d023a88
    int32_t v46 = v32 - v15 - (int32_t)v45; // 0x1d023a90
    int32_t result; // 0x1d0238e0
    if (v46 < 0) {
        // 0x1d023b54
        result = v11 == 45 ? -v44 : v44;
        goto lab_0x1d023ac4;
    } else {
        // 0x1d023a9c
        if (v44 < v34 || v46 != 0) {
            goto lab_0x1d023aa8;
        } else {
            // 0x1d023b38
            if (v31 == (v44 - v34) / v21) {
                // 0x1d023b54
                result = v11 == 45 ? -v44 : v44;
                goto lab_0x1d023ac4;
            } else {
                goto lab_0x1d023aa8;
            }
        }
    }
  lab_0x1d023a08:;
    int32_t v25 = v17 + 1;
    char v26 = *(char *)v25; // 0x1d023a0c
    int32_t v27 = v25; // 0x1d023a10
    v14 = v26;
    v21 = v20;
    v18 = v17;
    v15 = v25;
    while (v26 == 48) {
        // 0x1d023a0c
        v25 = v27 + 1;
        v26 = *(char *)v25;
        v27 = v25;
        v14 = v26;
        v21 = v20;
        v18 = v17;
        v15 = v25;
    }
    goto lab_0x1d023a18;
  lab_0x1d023ac4:
    // 0x1d023ac4
    if (a2 != 0) {
        // 0x1d023ad0
        *(int32_t *)a2 = v32;
        return result;
    }
    // 0x1d0239b0
    return result;
  lab_0x1d023aa8:
    // 0x1d023aa8
    *(int32_t*)0xa00001ec = 34;
    result = -1;
    if (a4 != 0) {
        // 0x1d023abc
        *(int32_t *)a4 = 1;
        result = -1;
    }
    goto lab_0x1d023ac4;
}

// Address range: 0x1d024db0 - 0x1d024f6c
int32_t Stolx(int32_t a1, int32_t a2, int32_t a3, int32_t a4) {
    int32_t v1 = *(int32_t*)0xa00001f0; // 0x1d024dd8
    int32_t v2 = a1; // 0x1d024e00
    int32_t v3 = a1; // 0x1d024e00
    int32_t v4; // 0x1d024db0
    int32_t v5 = 0x1000000 * v4 / 0x1000000; // 0x1d024e00
    if ((*(int16_t *)(v1 + (2 * v4 & 510)) & 324) != 0) {
        v2++;
        int32_t v6 = (int32_t)*(char *)v2; // 0x1d024e08
        v3 = v2;
        v5 = v6;
        while ((*(int16_t *)((2 * v6 & 510) + v1) & 324) != 0) {
            // 0x1d024e08
            v2++;
            v6 = (int32_t)*(char *)v2;
            v3 = v2;
            v5 = v6;
        }
    }
    // 0x1d024e28
    int32_t v7; // bp-32, 0x1d024db0
    int32_t v8 = a2 == 0 ? (int32_t)&v7 : a2; // 0x1d024df8
    int32_t v9; // 0x1d024db0
    int32_t v10; // 0x1d024db0
    int32_t v11; // 0x1d024db0
    int32_t v12; // 0x1d024db0
    int32_t v13; // 0x1d024db0
    switch (v5) {
        case 45: {
            goto lab_0x1d024f0c;
        }
        case 43: {
            goto lab_0x1d024f0c;
        }
        default: {
            int32_t v14 = Stolx2(v3, v8, a3, a4); // 0x1d024e48
            int32_t * v15 = (int32_t *)v8; // 0x1d024e4c
            int32_t v16 = *v15; // 0x1d024e4c
            v11 = v14;
            v13 = v16;
            v9 = 43;
            if (v16 == v3) {
                *v15 = a1;
                v12 = v14;
                v10 = 43;
                goto lab_0x1d024f30;
            } else {
                goto lab_0x1d024e58;
            }
        }
    }
  lab_0x1d024f0c:;
    int32_t v17 = v3 + 1; // 0x1d024f0c
    int32_t v18 = Stolx2(v17, v8, a3, a4); // 0x1d024f1c
    int32_t * v19 = (int32_t *)v8; // 0x1d024f20
    int32_t v20 = *v19; // 0x1d024f20
    v11 = v18;
    v13 = v20;
    v9 = v5;
    if (v20 == v17) {
        // 0x1d024f2c
        *v19 = a1;
        v12 = v18;
        v10 = v5;
        goto lab_0x1d024f30;
    } else {
        goto lab_0x1d024e58;
    }
  lab_0x1d024e58:;
    int32_t result = v11; // 0x1d024e5c
    int32_t v21 = v9; // 0x1d024e5c
    v12 = v11;
    v10 = v9;
    if (v13 == a1) {
        goto lab_0x1d024f30;
    } else {
        goto lab_0x1d024e64;
    }
  lab_0x1d024f30:
    // 0x1d024f30
    result = 0;
    v21 = v10;
    int32_t v22 = v10; // 0x1d024f30
    if (v12 == 0) {
        goto lab_0x1d024e64;
    } else {
        goto lab_0x1d024ea8;
    }
  lab_0x1d024e64:
    // 0x1d024e64
    switch (v21) {
        case 43: {
            // 0x1d024f40
            v22 = 43;
            if (result >= 0) {
                // 0x1d024e74
                return result;
            }
            // break -> 0x1d024ea8
            break;
        }
        case 45: {
            // 0x1d024e94
            v22 = 45;
            if (result < 0x80000001) {
                // 0x1d024eec
                return -result;
            }
            // break -> 0x1d024ea8
            break;
        }
        default: {
            // 0x1d024e74
            return result;
        }
    }
    goto lab_0x1d024ea8;
  lab_0x1d024ea8:
    // 0x1d024ea8
    *(int32_t*)0xa00001ec = 34;
    if (a4 != 0) {
        // 0x1d024eb4
        *(int32_t *)a4 = 1;
    }
    // 0x1d024e74
    return v22 == 45 ? -0x80000000 : 0x7fffffff;
}

// Address range: 0x1d026c7c - 0x1d026cc4
int32_t function_1d026c7c(int32_t result, uint16_t a2, int32_t a3) {
    // 0x1d026c7c
    if (a3 == 0) {
        // 0x1d026cb0
        return 0;
    }
    int32_t v1 = a2 % 256; // 0x1d026c80
    if (result % 256 == v1) {
        // 0x1d026cb0
        return result;
    }
    int32_t v2 = result; // 0x1d026c94
    v2++;
    int32_t result2 = 0; // 0x1d026cac
    while (v2 != a3 + result) {
        // 0x1d026c98
        result2 = v2;
        if (v1 == (int32_t)*(char *)v2) {
            // break -> 0x1d026cb0
            break;
        }
        v2++;
        result2 = 0;
    }
    // 0x1d026cb0
    return result2;
}

// Address range: 0x1d026fd4 - 0x1d026fdc
int32_t exit2(void) {
    // 0x1d026fd4
    int32_t result; // 0x1d026fd4
    __asm_di(result);
    return result;
}

// --------------------- Meta-Information ---------------------

// Detected functions: 5
